-- ════════════════════════════════════════════════════════
-- 219 — `brands.source` n'est plus un varchar(500)
-- ────────────────────────────────────────────────────────
-- CE QUI EST ARRIVE. `brands.source` etait un varchar(500). Les sources
-- ecrites depuis la migration 204 — un titre d'article, sa date, les
-- faits qu'il etablit, le second article, le site de la maison — font
-- souvent six a neuf cents caracteres. MySQL les a coupees a 500 SANS
-- ERREUR, exactement comme `moderation_log.detail` coupait a 255 : le
-- meme defaut, sur une autre colonne, un mois plus tard. 53 fiches
-- s'arretaient au milieu d'un mot, et les CONCAT des lots 5, 5 bis et
-- des requalifications ajoutaient a une valeur deja pleine — Drew
-- Estate n'a jamais recu sa note du lot 5 bis.
--
-- Decouvert par un controle de la 218 qui verifiait que treize sources
-- portaient « lot 5 bis : » — douze le portaient.
--
-- CE QUE FAIT CETTE MIGRATION. La colonne passe en TEXT. Puis chaque
-- source tronquee est reecrite dans sa version complete, reconstruite
-- depuis les generateurs (207 a 218) et les migrations ecrites a la main
-- (204 a 206), dans l'ordre ou elles ont ete posees puis prolongees. Le
-- generateur a verifie pour chacune que la valeur tronquee en base est
-- un PREFIXE de la valeur reconstruite : sinon il refuse d'ecrire.
--
-- Un test de campagne verifie desormais le type de la colonne, pour que
-- la production ne puisse pas rester en varchar(500).
-- ════════════════════════════════════════════════════════

ALTER TABLE `brands` MODIFY `source` TEXT NULL;

UPDATE `brands` SET `source` = 'en.wikipedia.org « A. J. Fernandez Cigars » et cigaraficionado.com (Tabacalera Fernández fondée à Estelí en 2003 avec six rouleurs ; San Lotano, marque du grand-père à San Luís, reprise en 2010) — le champ de date disait « années 2000 », précisé par la migration 197 ; lot 5 : ajfernandezcigars.com (Enclave, cape Habano d''Équateur, 2016 ; Días de Gloria, puro nicaraguayen, 2020) ; requalification : cigaraficionado.com « A.J. Fernandez To Acquire Sosa Cigars » (19 décembre 2016 : rachat des seules marques de la famille Sosa — Sosa Classic, Imperio Cubano, Santa Julia… — faites jusque-là à la fabrique n° 4 de Tabacalera A. Fuente par Juan Sosa, chez Fuente depuis 1997 ; production passée au Nicaragua chez A.J. Fernández dès janvier 2017)' WHERE `name` = 'A.J. Fernandez';
UPDATE `brands` SET `source` = 'halfwheel.com « ADV & McKay Cigars Co. to Make IPCPR Debut with ADVentura The Conqueror » (fondée en 2016, coopération entre Henderson Ventura, de Tabacalera William Ventura, et Marcel Knobel, sommelier, producteur et détaillant de café suisse ; The Conqueror en cape Habano 2000 d''Équateur, sous-cape Sumatra d''Équateur, tripes dominicaine et nicaraguayenne ; The Explorer et The Navigator) ; adventuracigars.com (The Royal Return, Barbarroja''s Invasion, Blue Eyed Jack''s Revenge) ; smokingpipes.com' WHERE `name` = 'ADVentura';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Q&A: Indiana Ortez, Agrotabacos » (5 février 2019 : « In 1995, Agroindustrial Nicaraguense de Tabacos S.A. (Agrotabacos) was born as a family business » ; fondée par Omar Ortez ; Jalapa, Condega et Estelí ; 40 % de la production sous Omar Ortez Originals et Maduro, 60 % pour des tiers — Altadis USA, Zander-Greg, Flor de González, Kretek International ; Fathers, Friends and Fire avec Ventura ; Indiana Ortez, 25 ans, contrôle qualité et marketing, formée par le superviseur Fausto) ; halfwheel.com (Casa de Ortez présente La Malinche à la PCA 2023 ; Psyko Seven Nicaragua pour Ventura) ; cigar-coop.com (janvier 2025 : Indiana Ortez ambassadrice de fabrique pour Best Cigar Prices)' WHERE `name` = 'Agrotabacos';
UPDATE `brands` SET `source` = 'tobaccobusiness.com « Going All In: All Saints Cigars » et cigar-coop.com « PCA 2021 Report: All Saints Cigars » (fondée en 2018 par Micky Pegg avec Frank Layo et Martin Corboy ; chaque cigare roulé à la TAVICUSA de Rocky Patel, née d''une longue relation entre Pegg et Patel ; Solamente, édition limitée en un seul format 5×58, le premier succès ; Dedicación, première production régulière ; Saint Francis, d''après François d''Assise, en 2021) ; allsaintscigars.com ; bovedainc.com (entretien avec Micky Pegg)' WHERE `name` = 'All Saints Cigars';
UPDATE `brands` SET `source` = 'halfwheel.com « Balmoral Añejo XO Announced as Royal Agio''s Latest Release » (11 juillet 2015 : suite de l''Añejo 18 de l''année précédente ; cape brésilienne cultivée au soleil, sous-cape olor dominicaine, tripes du Brésil, de Rép. dominicaine et du Nicaragua ; faite à la fabrique de Royal Agio à San Pedro de Macorís ; distribuée alors par Drew Estate) et « STG Discontinuing Agio''s Balmoral, San Pedro de Macorís in the U.S. » (1er mai 2020 : STG a finalisé le rachat d''Agio en janvier ; Balmoral quitte le marché américain — ventes et incertitude FDA — mais continue ailleurs ; la fabrique de San Pedro de Macorís est convertie au seul cigare de machine, et General Cigar Dominicana, à Santiago, roulera Balmoral pour les marchés hors États-Unis ; Serie Signaturas : Dueto avec Ernesto Perez-Carrillo en 2018, Paso Doble avec Litto Gomez en 2019) ; cigar-coop.com « Analysis of STG''s Pending Acquisition of Royal Agio Cigars » ; hacico.de et cigarquality.com (Añejo XO en vente en Europe)' WHERE `name` = 'Balmoral';
UPDATE `brands` SET `source` = 'blancocigars.com « History » et neptunecigar.com « About Blanco Cigars » (fondée en 1998 par Cesar A. Blanco, son frère Francisco et son fils David, sur les bases posées par Cesar Sr. au début des années 1900 ; famille de Pinar del Río, cousins des Plasencia depuis quatre-vingts ans ; roulée au Nicaragua chez Plasencia, qui tient culture et fabrication à Danlí et à Estelí ; David Blanco assembleur ; Liga Exclusiva de Familia, l''ancienne ligne privée des frères, en Connecticut pour Cesar et en Pennsylvania Broadleaf Maduro pour David ; Nine) ; yelp.com (boutique à Seminole, Floride)' WHERE `name` = 'Blanco Cigars';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Bombay Tobak Ships M.Esteli » (30 août 2019 : Mel Shah, propriétaire ; M.Estelí, sa ligne la plus corsée, cape Habano 2000 d''Équateur, sous-cape dominicaine, tripe surtout nicaraguayenne avec du Piloto Cubano ; comme tous les cigares de la maison, produite à la fabrique Tabacos de Costa Rica) et « MBombay Puts Cigars In A Can » (fondée en mai 2014 par Mel Shah, propriétaire du Fame Lounge de Palm Springs, pour distribuer nationalement ses cigares maison) ; halfwheel.com « MBombay Gaaja » (juillet 2016, un seul format toro pressé 6 × 54, du mot gaja — l''éléphant de la culture hindoue) ; cigar-coop.com « Cigar Review: MBombay Classic Torpedo » (Connecticut d''Équateur, tripes du Nicaragua, du Pérou et de Rép. dominicaine)' WHERE `name` = 'Bombay Tobak';
UPDATE `brands` SET `source` = 'cigarjournal.com « Brun del Ré: Costa Rican Cigar Pride » (31 janvier 2019 : Carlo Corazza, Suisse installé de longue date au Costa Rica et propriétaire d''une société horlogère, arrête la cigarette en 1999, découvre le cigare à Cuba en 2001, ouvre un lounge ; en 2006, avec son associé Sam Capuano, décide de fabriquer ; trouve une fabrique à San José en 2007 ; nom de sa grand-mère et d''un blason suisse ; lignes Gold, Premium, Colonial, 1787 Libertad — son premier cigare 100 % costaricien, d''un planteur du sud du pays —, 1638 ; vingt-deux pays, surtout en Europe ; une quinzaine d''employés, 25 à 30 000 cigares par mois) ; brundelrecigars.com ; zigarrenversand.ch et casadelpuro.com (fabrique familiale à Escazú)' WHERE `name` = 'Brun del Ré';
UPDATE `brands` SET `source` = 'casdaglicigars.com « The Story of Casdagli Cigars » (fondée en 1997 sous le nom de Bespoke Cigars, rebaptisée au printemps 2018 ; roulage à Cuba par Carlos Valdez Mosquera jusqu''en 2013, puis Kelner Boutique Factory, puis IGM à San José et Tabacos de Costa Rica à Puriscal) et « Casdagli Cigars launches the Villa Casdagli Line » (« Tabacos de Costa Rica SA, then known as Vegas Santiago », coopération depuis 2012 ; maître assembleur Don Olman Guzman ; cape et sous-cape Équateur, tripe Pérou/Nicaragua/Équateur/Rép. dominicaine)' WHERE `name` = 'Casdagli';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Two Cigars for 10 Years of Cavalier Genève » (30 mars 2026 : dix ans, donc 2016 ; « rolled at the company''s Fabrica Centroamericana de Tabaco S.A. in Danlí, Honduras » ; la feuille d''or en losange sur chaque cigare ; « I really feel like this is what the American dream is like ») ; cigarlifeguy.com « Sebastien Decoppet: A Switzerland to Honduras Cigar Journey » (grandi à Genève près du siège de Davidoff, premier cigare vers vingt ans dans une boutique Davidoff ; parti au Honduras apprendre le métier ; échec d''une première entrée aux États-Unis par un distributeur ; Original Diamond Series avec la White Series, Black II, Viso, Prospektor, Inner Circle, Domaine Rouge pour son père né en 1956, Tres Delincuentes ; ambition de cultiver)' WHERE `name` = 'Cavalier Genève';
UPDATE `brands` SET `source` = 'halfwheel.com « Chogüí Dos77 Corojo Rogusto » (2 juin 2022 : marque de Víctor Nicolás, fumeur dominicain qui a voulu faire ses cigares avec les tabacs de Leo Reyes et la petite fabrique de Francisco « Chico » Rivas, surnommée le nid secret d''après l''oiseau de la marque ; Primera Edición lancée en 2014 ; Nicolás quitte le métier en 2018 ; retour annoncé en février 2022 avec un Dos77 refait — cape corojo dominicaine cultivée au soleil, piloto mejorado dans la tripe — distribué par Venture 1492, la société de Kyle Gellis de Warped ; la maison dit tirer fierté de ses cigares 100 % dominicains) ; smallbatchcigar.com « Interview with Chogui Cigars (Victor Nicolas) » (Primera Edición, novembre 2014, réservée aux détaillants dominicains, 6 000 cigares ; rencontre avec Rivas fin 2013)' WHERE `name` = 'Chogüí';
UPDATE `brands` SET `source` = 'cigardojo.com « Cuban Stock Cigar Co. Announces Company Updates » (31 mars 2016 : Yaniv Levy, fondateur et président ; vingt ans dans deux fabriques précédentes de moins de 10 000 pieds carrés ; nouvelle usine de 20 000 pieds carrés dans la zone franche de Tamboril ouverte fin février 2016 ; capacité portée de 1,8 à 10 millions, objectif 3 millions ; 40 puis 100 employés ; plus de vingt marques actives — Chubbys, Delicioso, Everyday Joe, Limitado, Reserve, Triumph, 231 ; pas de vente directe) ; cubanstockcigars.com' WHERE `name` = 'Cuban Stock Cigar Co.';
UPDATE `brands` SET `source` = 'cigaraficionado.com « De Los Reyes — A Field and a Factory » (Leo frère d''Augusto, Nirka FILLE d''Augusto et nièce de Leo ; ferme de Navarrete créée en 1961, 20 à 30 acres, première plantation de Rép. dominicaine à cultiver le Piloto Cubano, cape Negrito ; 2 à 2,5 millions de cigares par an ; marques propres Saga, Saga Short Tales et Don Julio ; sous contrat Patoro, Debonaire, Indian Motorcycle) ; halfwheel.com (Arsen emploie la cape de Navarrete) ; en.wikipedia.org « Arsen (company) », notice signalée comme promotionnelle depuis mars 2022 (Arsen Gasparian, 2010, Hecho a Mano)' WHERE `name` = 'De Los Reyes Cigars';
UPDATE `brands` SET `source` = 'cigar-coop.com « Spotlight on Debonaire House at the 2018 IPCPR » et « Debonaire Daybreak » (Debonaire House réunit deux marques, Debonaire et Indian Motorcycle Cigars ; Habano et Maduro pour chacune, puis Daybreak en Connecticut d''Équateur, cinquième assemblage) ; halfwheel.com PCA 2021 et 2025 (Phil Zanghi, fondation en 2012 avec Daniel Sinclair ; produite chez De Los Reyes sous la supervision de Zanghi) ; stogiepress.com (distribution du Daybreak avec Drew Estate) ; tobaccobusiness.com « The Power of Positivity »' WHERE `name` = 'Debonaire House';
UPDATE `brands` SET `source` = 'don-collins.com « Our History » (la Puerto Rico Tobacco Corporation fait Don Collins depuis 1991 ; la maison affirme descendre d''une Porto Rico Leaf Company de 1506, puis de la Porto Rican-American Tobacco Company de 1898-1899 — le premier point n''est pas vérifiable, le second cite l''arrêt United States v. American Tobacco Co. de 1911) ; supreme.justia.com « United States v. American Tobacco Co., 221 U.S. 106 (1911) » (l''American Tobacco fait organiser en 1899 la Porto Rican-American Tobacco Company, qui reprend Rucabado y Portela, fabricant de cigares et de cigarettes) ; tripadvisor.com (atelier-boutique de la calle del Cristo, rouleurs visibles)' WHERE `name` = 'Don Collins';
UPDATE `brands` SET `source` = 'blindmanspuff.com « Editorial: Don Lucas Cigar Factory | Mundo Autentico » (1er janvier 2018 : petite fabrique familiale dans le complexe Mundo Auténtico de Punta Cana, avec le café, le chocolat et le rhum ; tabacs des fermes autour de Santiago et d''ailleurs ; environ 60 % des cigares vendus sur place, le reste dans une vingtaine de boutiques américaines et cinq ou six en Colombie ; lignes Classic — Connecticut d''Équateur —, HS — Sumatra —, AL — broadleaf américain —, 20th Anniversary — puro dominicain —, Family Reserve ; boîtes de cèdre faites sur place) ; kupi.com et getyourguide.com (fondée en 1992 par le Belge Philippe Gillet, deux rouleurs et 150 cigares par jour au départ, plus de 45 employés) ; donlucascigars.com' WHERE `name` = 'Don Lucas';
UPDATE `brands` SET `source` = 'cigaraficionado.com et halfwheel.com (Jonathan Drew et Marvin Samel, 1996 à New York, l''installation à Estelí, la manufacture de 1999) ; en.wikipedia.org (Drew Estate) ; lot 5 : cigaraficionado.com « Willy Herrera Named Master Blender of Drew Estate » et halfwheel.com « Herrera Esteli Toro Especial » (Willy Herrera, assembleur d''El Titan de Bronze à Miami, engagé en 2011 ; Herrera Estelí lancée début 2013 sur un assemblage composé lors de sa première visite en 2010) ; drewestate.com (Kentucky Fire Cured) ; lot 5 bis : drewestate.com (Nica Rustica, 2013, broadleaf, le cigare du rouleur ; Herrera Estelí Norteño, 2015, San Andrés)' WHERE `name` = 'Drew Estate';
UPDATE `brands` SET `source` = 'premiumcigars.org « The Precision of Premium: How El Septimo is Changing the Game » (fondée au début des années 2000 et connue en Europe et au Moyen-Orient depuis 2005 ; rachetée par Zaya Younan en mars 2019 ; fabrique au Costa Rica ; collection Alexandra lancée en juin 2019, pensée pour les femmes ; Sacred Arts Collection présentée à la PCA 2021, sept cigares au nom d''artistes et des sept jours de la création ; la maison dit appliquer à ses champs les méthodes de ses vignobles de Bordeaux et de Saint-Émilion) ; halfwheel.com « El Septimo Releasing Two New Cigars, New Accessory Line at TPE 2021 » ; cigaraficionado.com « El Septimo Launches Cigar Line for Women » ; elseptimo.com (fondée à Genève en 2005 ; cape, sous-cape et tripe entièrement costariciennes, cultivées et roulées au Costa Rica)' WHERE `name` = 'El Septimo';
UPDATE `brands` SET `source` = 'cigarlifeguy.com « Interview: Dean Parsons, Founder of Epic Cigars » (Canadien, dix ans dans la police, parti en 2005 aux Turks et Caicos ; marque Turks Select 2006-2010 ; installé en Rép. dominicaine en 2009, lance Epic en 2010 avec Maduro et Corojo, toujours au catalogue ; distribuée au Canada depuis 2015) ; halfwheel.com « Epic Corojo Reserva Double Corona » et « Epic Maduro Reserva Robusto » (roulés à la fabrique Charles Fairmorn, qui fait aussi Kristoff ; Corojo d''Équateur et Arapiraca du Brésil) ; cigar-coop.com « Summer of ''20 Spotlight: Epic Cigars/Nat Cicco » (Zander-Greg, distributeur californien propriétaire de Nat Cicco depuis 2007, rachète Epic fin 2019 et garde Parsons) ; epiccigars.com' WHERE `name` = 'Epic Cigars';
UPDATE `brands` SET `source` = 'wantedonline.co.za « Cigars from Esteban Carreras explore the best of Nicaragua » (2 janvier 2026 : origines que la presse elle-même dit mystérieuses — un rouleur cubain anonyme dans les années 1990, un nom emprunté à un passeur d''après la révolution ; depuis le début ou le milieu des années 2000, Craig Cunningham, entrepreneur américain, possède et dirige la maison et a établi la Tabacalera Carreras à Estelí ; siège en Californie ; treize lignes dont Cashmere, Dictator''s Hand, Hellcat, Chupacabra, Unforsaken, Black Cross, Brown Cross, Bloodline, Mr Brownstone ; Chupacabra 10 Años en cape San Andrés ; roule aussi pour d''autres marques ; à l''Inter-tabac 2024, distribution mondiale avec Kopp Tobaccos) ; estebancarreras.com (la majorité des cigares sont des puros nicaraguayens) ; klarocigars.com (entretien avec Cunningham à la TPE 2024 : la légende du nom, liée à une semence corojo sortie de Cuba)' WHERE `name` = 'Esteban Carreras';
UPDATE `brands` SET `source` = 'cigar-coop.com « Ezra Zion All My EX''s » et « Fred Rewey Sells Nomad Cigar Company to Ezra Zion » (septembre 2018) ; halfwheel.com « Ezra Zion Honor Series FHK Truth » (débuts en juillet 2012 avec l''Honor Series Reagan et Inception, devenue Jamais Vu ; Tantrum ; les trois premiers assemblages sont des puros nicaraguayens ; collaboration avec la fabrique Aromas de Jalapa de Noel Rojas) ; tinderbox.com (fondée au Texas par Chris Kelly et Kyle Hoover) ; blindmanspuff.com (rachat de Cigar Federation)' WHERE `name` = 'Ezra Zion';
UPDATE `brands` SET `source` = 'halfwheel.com « Fable Returns to Market, Moves Production to Córdoba & Morales » (16 octobre 2025 : lancée en 2016 par Sean Kremenetski et Mitul Shah, absente du marché près de la moitié du temps depuis ; Fourth Prime passe de Nica Sueño à Córdoba & Morales, même assemblage sur le papier — cape broadleaf de Pennsylvanie, sous-cape Habano ligero d''Équateur, tripes dominicaine et nicaraguayenne ; sept vitoles avant, quatre au retour ; boîtes de 56 devenues 21 ; distributeur Pospiech) ; cigar-coop.com « Fable Cigars Announces Relaunch » (la maison explique sur son site que Fourth Prime raconte le nombre 7, quatrième nombre premier, et que le triangle du logo en est fait de sept traits) ; fablecigars.com' WHERE `name` = 'Fable Cigars';
UPDATE `brands` SET `source` = 'halfwheel.com « Luciano Cigars & Empresa Madeirense de Tabacos S.A. Launch Constella Group » (2 avril 2025 : EMT, 142 ans d''histoire, exploite la Fábrica de Tabacos Estrela à São Miguel, qui fait surtout des cigarettes et des cigarillos avec un petit atelier de cigares main ; Constella devient la maison mère de Luciano) ; visitpontadelgada.pt « Estrela Tobacco Factory » (fondée en 1882 par José Medeiros Cogumbreiro ; seule à faire ses cigares entièrement à la main ; tripes du Brésil, de Cuba et de Rép. dominicaine, capes des États-Unis et d''Indonésie ; deux jours en moule, séchage à basse température ; Meia Coroa, Coroa, Robusto Estrela) ; lifecooler.com (le cigare est un complément petit mais prestigieux d''une fabrique de cigarettes ; boîtes en bois, personnalisables) ; agroportal.pt (136e anniversaire fêté en 2018)' WHERE `name` = 'Fábrica de Tabaco Estrela';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Agape Lifestyle Inc. Launches Freud Cigar Co. » et cigar-coop.com « Freud Cigar Company to Debut with SuperEgo » (avril 2022 : fondée par Luis Torres et David Stadnyk, filiale d''Agape Lifestyle Inc. ; SuperEgo, du nom du surmoi de la théorie de Freud, produit par Tabacalera William Ventura) ; finetobacconyc.com (lancement à New York, mai 2022) ; halfwheel.com « Freud SuperEgo Robusto Extra » ; kohnhed.com (AlterEgo, 2023) ; la fiche Tabacalera William Ventura de cet atlas (la fabrique a brûlé le 26 septembre 2022, cinq mois après le lancement)' WHERE `name` = 'Freud Cigar Co.';
UPDATE `brands` SET `source` = 'generalcigar.com et en.wikipedia.org « General Cigar Company » (1906 ; Macanudo, Punch et Partagás non cubains ; Santiago, Danlí et Estelí ; propriété de Scandinavian Tobacco Group depuis 2005) ; requalification : cigaraficionado.com « General Cigar Acquires All Toraño Brands » et halfwheel.com « General Cigar Co. Acquiring Toraño Brands » (septembre 2014 : General rachète tout le portefeuille de Toraño Family Cigar, pas la société, qui cesse ; Charlie Toraño consultant) ; cigar-coop.com « Carlos Toraño Passes Away » (février 2022)' WHERE `name` = 'General Cigar';
UPDATE `brands` SET `source` = 'ghcigars.com « The Gran Habano Legacy » (« The Rico family history in tobacco stretches back to 1920, when Guillermo Rico''s grandfather began growing dark tobacco in Colombia » ; usine de Danlí en 1998 ; marque en 2003 par le père et le fils ; Connecticut No. 1, Habano No. 3, Corojo No. 5 ; établie à Miami) ; famous-smoke.com « Master Blenders: George Rico » (Guillermo Rico installé à Miami en 1995 ; STC Cigar Manufacturers) ; cigaraficionado.com (Gran Habano 3 Siglos n° 20 du Top 25 de 2007 ; Blue in Green) ; neptunecigar.com (fermes et usine G.R. Tabacaleras Unidas, la majorité de la feuille cultivée en propre)' WHERE `name` = 'Gran Habano';
UPDATE `brands` SET `source` = 'cigaraficionado.com « A $20 Nassau » (Enrico Garzaroli, propriétaire de l''hôtel-restaurant Graycliff, fait sortir de Cuba Avelino Lara en 1993 ; l''assemblage — tabacs du Brésil, du Nicaragua, du Honduras, parfois d''Équateur et du Cameroun, cape d''Indonésie, bétune au sauternes — vendu aux États-Unis dès octobre 1997 ; atelier de rouleurs cubains retraités, moyenne d''âge 64 ans ; 650 000 cigares en 1999 ; marque Bahiba) ; graycliff.com (production commencée en janvier 1997 avec un seul rouleur dans l''entrée du restaurant ; seize rouleurs ; Enrico et Paolo Garzaroli assemblent depuis le départ de Lara en 2000)' WHERE `name` = 'Graycliff';
UPDATE `brands` SET `source` = 'cigarjournal.com « Visiting China''s Premium Cigar Production » (reportage de Samuel Spurr, édition d''automne 2017 : née en 1918 comme Yichuan Industry Society ; le cigare 132 roulé main pour Mao dans les années 1960 ; 560 millions de cigares de machine et 1,5 million roulés main par an, objectif 2 millions ; site actuel achevé en 2007 ; trois maîtres rouleuses encadrent près de cent rouleuses ; partenariats avec Altadis et Agio ; semence cubaine introduite seize ans plus tôt ; essais à Hainan ; achats de feuilles en Rép. dominicaine, au Mexique et en Indonésie ; 400 000 cigares en vieillissement) et « CTIHK and Sichuan Tobacco Sign Global Deal for Great Wall Cigars » (23 juillet 2025 : accord mondial exclusif hors Chine continentale ; Inter-tabac 2025) ; cigaraficionado.com « New Cigars Unveiled At Great Wall Cigar Festival » ; tobaccoasia.com « Cigars: Made in Asia »' WHERE `name` = 'Great Wall Cigars';
UPDATE `brands` SET `source` = 'halfwheel.com « Hiram & Solomon Moving All Production to PDR Cigars » (18 juin 2022 : fin de l''accord de fulfillment avec Blanco Cigars deux semaines plus tôt ; tout le portefeuille passe chez PDR, à Tamboril — Entered Apprentice, Fellow Craft, Master Mason, Veiled Prophet, Traveling Man, Shriner, Grand Architect, 300th Anniversary, Unity ; Fouad et Romy Kashouty travaillent avec Abe Flores depuis 2021 ; Curamus, février 2021, Châbal, Revival et Sublime Prince 32, 2022, déjà chez PDR ; Abe Flores dit à la presse qu''ils ont voulu travailler avec lui seul) ; cigar-coop.com « IPCPR 2019 Spotlight: Hiram & Solomon » (fondée en 2015 par Fouad Kashouty et George Dakrat ; production d''abord en Rép. dominicaine, puis chez Plasencia ; tabac paraguayen dans Entered Apprentice et Veiled Prophet) ; cigarsnobmag.com' WHERE `name` = 'Hiram & Solomon';
UPDATE `brands` SET `source` = 'jcnewman.com et cigarjournal.com « J. C. Newman Cigar Co. — America''s Oldest Cigar Family » (Julius Caeser Newman, 1895 à Cleveland puis Tampa ; la fabrique El Reloj) — ⚠ le champ GAMME de cette fiche a été vidé de ses cigares de machine par la migration 187 : El Reloj en fabrique, l''atlas ne les porte pas ; lot 5 : halfwheel.com « J.C. Newman Renames PENSA Factory » (25 avril 2018 : PENSA — Puros de Estelí Nicaragua S.A. — ouverte en 2011 avec Quorum et El Baton, puis Perla del Mar, puis Brick House rapatriée d''une autre fabrique ; plus de 100 000 cigares par jour ; co-dirigée par Omar Ortez et Lázaro López) ; cigaraficionado.com « J.C. Newman Opens Nicaraguan Cigar Factory »' WHERE `name` = 'J.C. Newman';
UPDATE `brands` SET `source` = 'halfwheel.com « Jake Wyatt Cigar Co. Releases Value-Focused Titan Series » (1er avril 2026 : lancée en février 2020 par Neil Garcia et Gerard Abajian, le nom vient des prénoms de leurs fils ; toute la production vient d''être transférée à la Tabacalera San Jerónimo de Danlí après une poignée de fabriques dominicaines ; Neil Garcia, président, dit que la gamme entière a été refaite sur des tabacs honduriens et nicaraguayens ; série Titan — Goliad, Colossus, Omega — boîtes de 22) ; cigarlifeguy.com « Jake Wyatt Cigars: Interview with Gerard Abajian » (Abajian, dix ans pompier, fils d''un détaillant californien ; la maison disait alors posséder une fabrique de 20 000 pieds carrés nommée Casamorabo ; la boîte de 22 vient du numéro de maillot de Garcia au baseball) ; jakewyattcigars.com' WHERE `name` = 'Jake Wyatt Cigar Co.';
UPDATE `brands` SET `source` = 'newsroompanama.com « Joyas de Panamá Cigars: History of Cigars in Panama » (14 septembre 2025 : « In February 1986 Sra. Miriam Padilla founded the Joyas de Panama Cigar Factory in La Pintada de Cocle » ; première fabrique permanente du pays ; semence cubaine, techniques cubaines de roulage ; tabac de Sortová, Sonadora et La Pintada ; activité jusqu''en 2023, reprise par son fils Braulio Zurita) ; dopanama.com (Miriam Padilla directrice de production chez Gilberto Oliva avant de fonder la sienne) ; lonelyplanet.com pour l''atelier de La Pintada' WHERE `name` = 'Joyas de Panamá';
UPDATE `brands` SET `source` = 'cigaraficionado.com « An All-Dominican Cigar from Kafie 1901 Coming Next Month » (29 août 2022 : usine de Danlí fermée en novembre 2021 — ouragans, chaîne d''approvisionnement — et toute la production transférée à La Aurora ; Serie L Natural avec Manuel Inoa, le L pour les cinquante ans de Kafie en juillet 2021) ; halfwheel.com « Kafie 1901 Cigars Opens New Honduran Factory » (société en 2013 chez Puros Aliados ; usine de 2 000 pieds carrés à Danlí, 20 personnes dont 12 rouleurs, 150 000 cigares par an ; lignes Don Fernando Maduro, Connecticut, Sumatra, San Andrés) ; kafiecigars.com (Gaby Kafie, chirurgien du pied, retiré à 38 ans en 2007 pour une maladie des yeux ; famille à Tegucigalpa depuis 1901) ; cigarjournal.com (dixième anniversaire, 2023)' WHERE `name` = 'Kafie 1901';
UPDATE `brands` SET `source` = 'tobaccobusiness.com « Karen Berger: Dream Chaser » (Tobacco Businesswoman of the Year 2021 ; Don Kiki Berger fonde l''affaire dans les années 1990, meurt en 2014 ; fabrique Tabacalera Estelí ; ferme ; K by Karen Berger en 2016 ; Don Kiki Cigars Superstore à Daytona Beach) ; cigaraficionado.com « Kiki Berger of Cuban Crafters, 56, Dies » et cigar-coop.com (septembre 2014 ; co-propriétaire de la boutique et de la marque Cuban Crafters à Miami) ; cigarinspector.com « Cigar Industry Legends – Don Kiki Berger » (Max Berger, parti de Pologne en 1940 pour Cuba, fabrique à Pinar del Río ; entrée de Kiki dans le métier en 1996 ; Tabacalera Estelí et la ferme Vegas de 200 acres) ; karenbergercigars.com' WHERE `name` = 'Karen Berger Cigars';
UPDATE `brands` SET `source` = 'halfwheel.com (fondée en 2012 par Hendrik Kelner Jr. après dix-huit ans chez Tabadom auprès de son père ; The 73, du nom de son année de naissance, avec Privada Cigar Club ; Klaas Pieter Kelner, de la même famille, ouvre sa propre fabrique dans la zone franche de Santiago en 2023) ; casdaglicigars.com « KBF Factory » (Casdagli y a été roulée de 2013 à 2016) ; leafenthusiast.com (Henke Kelner, maître de tabac de Davidoff, fondateur de Tabadom, plus de trente ans) ; cigarjournal.com (Principle y est faite)' WHERE `name` = 'Kelner Boutique Factory';
UPDATE `brands` SET `source` = 'cigaraficionado.com « A Q&A with Luciano Meirelles, ACE Prime Cigars » (10 août 2020 : Meirelles brésilien, finance puis conseil politique ; présenté à Eradio Pichardo par Ernesto Perez-Carrillo en 2008 ; Pichardo parti de Cuba en 2005, ancien de Habanos S.A. ; Dhatuey Tabacos février 2005, Tabacalera Pichardo janvier 2009 ; 64 rouleurs, 123 employés, 3,1 millions de cigares en 2019 ; ACE Prime janvier 2018 avec Tiago Splitter ; roule Crowned Heads) ; halfwheel.com et cigar-coop.com (rebaptisée Luciano Cigars en septembre 2022, la fabrique devient Luciano Cigar Factory) ; roule aussi pour Ozgener Family Cigars' WHERE `name` = 'Luciano Cigars';
UPDATE `brands` SET `source` = 'cigaraficionado.com « A Conversation with Nestor Miranda » (janvier-février 2007 : né à Cuba ; vingt-cinq ans dans les spiritueux, Southern Wine & Spirits puis Seagram, retiré en 1995 ; société fondée en 1989 avec Mariana, 80 000 cigares la première année à l''usine d''UST au Honduras ; Don Lino nommé d''après un homme de la fabrique, 1,5 million en 1994, 12 millions en 1996 ; UST cesse en novembre 1996, marque hors marché en 1997-1998, reprise début 1999 chez La Aurora grâce à Guillermo León ; distributeur exclusif de La Aurora aux États-Unis depuis la fin des années 1980 ; Tatiana, Don Lino Africa) ; « Mariana and Nestor Miranda, Miami Cigar & Co. » (40 000 cigares distribués la première année, plus de 20 millions aujourd''hui) ; halfwheel.com (le 25e anniversaire fait chez La Aurora et My Father ; la Nestor Miranda Collection chez My Father Cigars S.A.)' WHERE `name` = 'Miami Cigar & Co.';
UPDATE `brands` SET `source` = 'halfwheel.com « Puro Sabor 2017: Day 5 » (la fabrique d''origine, Nicaragua American Tobacco S.A. — NATSA —, lancée en 1995 par Juan Francisco Bermejo avec des associés dont Lew Rothman, ancien propriétaire de JR Cigar ; elle roulait exclusivement pour JR, des cigares bon marché ; nouveau bâtiment deux ans plus tôt ; Raúl Disla engagé pour la production ; clients Asylum et Mi Querida de Saka ; Finca Guadalupe, la ferme de la famille Oliva Tobacco) ; cigaraficionado.com « Larry Palombo Joins Nicaraguan Cigar Factory » (13 janvier 2016 : NACSA, ex-NATSA, détenue en partie par l''Oliva Tobacco Co. de Tampa — fondée par Angel Oliva Sr. dans les années 1930, sans lien avec Oliva Cigars ; Palombo, quarante-quatre ans de métier, ancien vice-président tabac d''Altadis USA, vient réassembler les marques déposées de la fabrique : Red Dot, Villar y Villar, La Rosa Especial, Aristoff) ; cigar-coop.com (Patina roulée à NACSA depuis 2019)' WHERE `name` = 'NACSA';
UPDATE `brands` SET `source` = 'cigar-coop.com « Cigar Review: Patina Anniversary » (fondée en 2015 par Mo Maali à Chicago ; premiers assemblages chez Mombacho en 2017 ; rupture en 2019 et production transférée à NACSA, Estelí) ; halfwheel.com « Patina Cigars Adds Oro de Nicaragua as New Core Line » et « Patina Prepares to Ship Red Pill » (Red Pill expédié le 28 octobre 2025) ; cigar-review.com (Patina y Viso Verdigris, 2025, collaboration avec Viso Horny de Tyler Jeffery, faite à NACSA, 3 000 cigares, dix boutiques) ; patinacigars.com' WHERE `name` = 'Patina Cigars';
UPDATE `brands` SET `source` = 'patoro.com « History » et cigar-coop.com « Patoro Vintage Robusto Launched for U.S. Market at 2017 IPCPR » (Patrick J. Martin, Suisse ; vend en Europe depuis 2001 ; Gran Añejo Reserva en 2001, Platino en 2003, puis Vintage, VA, Brasil, Serie P ; la Serie P américaine diffère de l''européenne — cape et sous-cape brésiliennes, tripe dominicaine) ; cigaraficionado.com « CLE to Distribute Patoro Serie P U.S.A. Edition » (distribution américaine par C.L.E.) ; neptunecigar.com (faite à la fabrique d''Augusto Reyes) ; halfwheel.com « Patoro Platino Perfecto »' WHERE `name` = 'Patoro';
UPDATE `brands` SET `source` = 'cigaraficionado.com « The Formidable Factory » (juillet-août 2015 : Abe Flores né en 1975 dans le Queens, en République dominicaine à trois ans, diplômé de Merrimack en 1999, informatique avant le cigare ; marque Pinar del Río lancée au salon de 2008, PDR 1878 en 2009, nouvelle usine en 2011 ; A. Flores 1975 Serie Privada n° 10 du Top 25 de 2014 ; 60 rouleurs, 4,5 à 5 millions par an, moitié en propre, moitié à façon — La Palina Black et Classic, Gurkha 125th, Kristoff, Viaje TNT et C4) ; pdrcigars.com ; halfwheel.com et cigar-coop.com (Hiram & Solomon y est roulée depuis juin 2022)' WHERE `name` = 'PDR Cigars';
UPDATE `brands` SET `source` = 'halfwheel.com « Powstanie Coming From Cigar Hustler & NicaSueño » (28 mars 2015 : les frères Mike et Greg Szczepankewicz, propriétaires de la boutique Cigar Hustler à Deltona, Floride, lancent leur marque, roulée à la Fábrica de Tabacos Nica Sueño — première marque hors RoMa Craft vendue par la fabrique à plusieurs détaillants ; nom polonais, « insurrection », logo inspiré des symboles de la résistance polonaise ; deux assemblages composés chacun par un frère avec Esteban Disla et Skip Martin, choisis en aveugle par les clients — Habano en mai, Maduro en août ; boîtes de 21) ; halfwheel.com « Powstanie San Andrés Corona Gorda » et « Powstanie Connecticut Perfecto » ; cigar-coop.com « PCA 2023: Powstanie Cigars » (Pospiech Cigars distribue aussi Fable et Chogüí)' WHERE `name` = 'Powstanie';
UPDATE `brands` SET `source` = 'principletrading.com « About Principle Cigars » (Darren Cioffi, chasseur de trésors et collectionneur d''étiquettes de boîtes anciennes, avec une bibliothèque de cigares remontant aux années 1870 ; un an et demi de sélection de tabacs avec Hendrik Kelner Jr. ; roulage à la Kelner Boutique Factory de Santiago par quatre rouleurs, jusqu''à dix cigares par jour pour certaines vitoles) ; wina-mp.pl (fondée en 2013 — devise de la maison « Pleasing All Senses Since 2013 » ; Time To Burn, projet des dix ans en 2023, fait à Casa Carrillo) ; cigarlifeguy.com « From Passion to Principle Cigars » (Aviator, art déco industriel américain de la fin des années 1940 ; Accomplice, style français des années 1930 ; Martinique, colonial du XVIIIe siècle) ; halfwheel.com « Principle Cigars Releases Engagement », « Principle Martinique Corona »' WHERE `name` = 'Principle Cigars';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Oliva Cigar Co. Acquires Cuba Aliados and Puros Indios Brands » (6 août 2021 : Cuba Aliados, Puros Indios et Roly vendues par Carlos Diez, petit-fils du fondateur ; l''usine de Danlí exclue de la vente ; fabrication passée au Nicaragua ; la famille continue Premier, Classic, Vintage, Cienfuegos et le travail à façon), « CLE to Distribute Reyes Family Cigars » (1er septembre 2016 : distribution par C.L.E. de Christian Eiroa dès le 12 septembre) et « Cigar Kings » (Cuba Aliados née dans les années 1970 au New Jersey ; consolidation à Danlí en 1990 ; Puros Indios en 1995 ; cinq millions de cigares par an) ; halfwheel.com ; en.wikipedia.org « Rolando Reyes Sr. » (1923–2012). Kafie y a fait rouler ses cigares de 2013 à 2017' WHERE `name` = 'Reyes Family Cigars';
UPDATE `brands` SET `source` = 'stogiephile.blog « Oliva Black Swan? Rocky Patel Black Swan? WTF? » (édition Black Swan de janvier 2024 UNIQUEMENT) — le reste de la fiche est antérieur et n''a pas de source enregistrée ; lot 5 : cigaraficionado.com « Hamlet Paredes Departs Rocky Patel » (12 septembre 2022 : Hamlet Paredes, ancien rouleur de Partagás et ambassadeur d''Habanos, engagé en 2015 ; Tabaquero, sa première ligne, la même année ; parti fin août 2022 ; Rocky Patel garde la marque Hamlet — Liberation by Hamlet, Hamlet 25th Year — et arrête Tabaquero) ; requalification : rockypatel.com (Indian Tabac Cigar Company, la première marque de Rocky Patel, années 1990, avant que la maison ne prenne son nom)' WHERE `name` = 'Rocky Patel';
UPDATE `brands` SET `source` = 'halfwheel.com « Noel Rojas Announces New Nicaraguan Factory » et « PCA 2025: Rojas Cigars » (Rojas Cigar Factory, ancien cinéma d''Estelí, un peu plus de 7 000 pieds carrés) ; cigar-coop.com (Guayacan 2012, premier salon 2013 ; ateliers précédents Aromas de Jalapa, Tabacalera New Order of the Ages, Sabor de Estelí, tous fermés ; a fait le Draig Cayuquero d''Emilio, le Nomad LE Estelí Lot 1386, les cigares d''Ezra Zion) ; cigarinspector.com et stogiepress.com (né à Cuba, Miami vers vingt ans, puis le Nicaragua ; Tabacalera Flor de San Luis en 2019 pour KSG, Bluebonnets, Statement ; roule Stolen Throne)' WHERE `name` = 'Rojas Cigars';
UPDATE `brands` SET `source` = 'cigar-coop.com « Cigar Review: Sindicato » et cigardojo.com « Sindicato Corona Gorda » (fondée en 2013 par un groupe de détaillants devenus propriétaires de marque ; Jim Colucci, ancien vice-président d''Altadis USA, président ; Sindicato fait chez Casa Fernández sur les tabacs des fermes Fernández ; lancement avec Hex — cape Habano d''Équateur —, Affinity et Casa Bella — Connecticut d''Équateur, tripes du Nicaragua et de Rép. dominicaine) ; halfwheel.com « Particulares #1 » ; leafenthusiast.com « Brand Overview: Sindicato » ; sindicatocigars.com' WHERE `name` = 'Sindicato Cigar Group';
UPDATE `brands` SET `source` = 'pt.wikipedia.org « Suerdieck Charutos » (« No ano 2000 [...] fechou sua última unidade na cidade de Cruz das Almas, dispensando os cem funcionários » ; environ cinq millions de pièces produites en 1999, premier fabricant brésilien) et gestoesinspiradoras.ufba.br « August Wilhelm Suerdieck » (arrivé en Bahia en 1888 ; société de 1892 ; fabrication à Maragojipe dès 1905 ; fin des activités à la fin de 1999) — réserve levée : l''arrêt de l''activité et la fermeture de la dernière usine sont deux moments, pas une contradiction' WHERE `name` = 'Suerdieck';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Fire in the Free Zone » (26 septembre 2022 : incendie avant 3 h, bâtiment partagé avec Intercigar perdu, ~800 000 cigares de Ventura et ~700 000 d''Intercigar, une centaine d''employés, aucun blessé ; roulait Room101, Caldwell, La Barba, Freud) ; cigarworld.com (William Ventura chef de production chez Davidoff, déjà en 1991 ; Wiber Ventura vingt ans chez Davidoff, parti en 2019 ; Nataly Ventura ; rouverte en mars 2024) ; halfwheel.com (El Maestro, Partagás Y Nada Más). Fondation : 2007 ou 2008 selon la source' WHERE `name` = 'Tabacalera William Ventura';
UPDATE `brands` SET `source` = 'tabaqueria.com (Gabriel « El Magnifico » Ripoll Jr., gérant et consultant du cigare depuis les années 1960, de Hong Kong à la Rép. dominicaine ; à sa retraite en 1993, un petit atelier sur Taft Avenue à Manille avec quatre anciens employés et son plus jeune fils ; ses trois fils le dirigent, plus de 250 personnes ; Isabela pais et tripe de semence cubaine sous cape de Java) ; tobaccoasia.com « Cigars: Made in Asia » (cinq rouleurs dans une maison d''avant-guerre louée du vieux Manille ; plus de 200 employés dans une usine à San Pedro, Laguna ; tabac des plantations de la vallée de Tubao, Luzon du Nord ; 15 000 cigares par jour ; marques Antonio Gimenez, Independencia 1898, Flor de Filipinas ; cape indonésienne, tout le reste philippin ; boîtes de narra faites maison)' WHERE `name` = 'Tabaqueria de Filipinas';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Te-Amo''s Alberto and Alejandro Turrent » (janvier-février 2009 : l''arrière-grand-père cultive dès 1880 ; Alberto Turrent entre dans l''affaire en 1960 à vingt-deux ans, comme chauffeur de camion ; « 1966 : Te-Amo brand created » ; la famille rachète la société Te-Amo en 1972 à la mort de l''associé new-yorkais ; deux millions de cigares invendus au départ, puis 170 points de vente autour de New York et 60 % des ventes dans les années 1970 ; 2 000 acres à San Andrés, premier producteur de tabac à cigares du Mexique, San Andrés Negro de semence Criollo et Sumatra ; Alejandro Turrent, fils, entre en 1998) ; « Te Amo Attempts a Comeback » (16 février 2024 : relance par Altadis, « The original San Andrés Valley cigar », trois formats, après le Te-Amo Revolution d''il y a plus de dix ans) ; halfwheel.com (1963 selon halfwheel — l''atlas retient 1966, la date donnée par Alberto Turrent lui-même) ; altadisusa.com' WHERE `name` = 'Te Amo';
UPDATE `brands` SET `source` = 'villigercigars.com « New Villiger cigar factory in Nicaragua » (la branche nicaraguayenne) ; la fiche de la maison mère Villiger Söhne porte ses propres sources (migration 195) ; requalification : houseofgrauer.com « Villiger Cigars » et havanahouse.co.uk (Havana Club, ancienne marque cubaine relancée par Villiger en 2007 comme cigare dominicain, roulée à l''ABAM, la fabrique de Villiger en République dominicaine) — et les deux entrées de machine, Premium No. 6 et Export, retirées du gamme en application de la règle 187' WHERE `name` = 'Villiger';
UPDATE `brands` SET `source` = 'cigaraficionado.com « Q&A: Kyle Gellis, Owner of Warped Cigars » (TABSA à Estelí, El Titan de Bronze à Miami, l''emploi quasi exclusif du tabac Aganorsa) — ⚠ L''ANNÉE DIVERGE : cet entretien dit que Gellis a lancé Warped en 2009, encore étudiant ; d''autres sources donnent 2007, année que l''atlas retient ; lot 5 : halfwheel.com « Guardian of the Farm Apollo Selección de Warped » (Guardian of the Farm, collaboration avec Casa Fernández lancée en 2016, hommage aux bouledogues qui gardent les fermes Aganorsa ; formats aux noms des chiens — Apollo, JJ, Campeón, Rambo)' WHERE `name` = 'Warped';

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 219';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 219','systeme','source_varchar_500_tronquait','marque',0,
   'brands.source etait un varchar(500) : 53 fiches coupees a 500 caracteres sans erreur depuis la 204, comme detail coupait a 255. Colonne passee en TEXT, sources reconstruites depuis les generateurs, chaque tronquee verifiee prefixe de sa reconstruction');

SELECT
  (SELECT COUNT(*) FROM `brands` WHERE CHAR_LENGTH(`source`) = 500 AND `name` <> 'ADVentura') = 0 AS plus_aucune_a_500,
  (SELECT COUNT(*) FROM `brands` WHERE CHAR_LENGTH(`source`) > 500) >= 52 AS reconstruites,
  (SELECT DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'brands' AND COLUMN_NAME = 'source') = 'text' AS colonne_text,
  (SELECT `source` LIKE '%lot 5 bis :%' FROM `brands` WHERE `name` = 'Drew Estate') AS drew_estate_complete;
