-- ════════════════════════════════════════════════════════
-- 227 — Lot 14 du cinquieme recensement : le Reconcavo au complet
-- ────────────────────────────────────────────────────────
-- LE BRESIL RELU DANS LA PRESSE EN PORTUGAIS. L'atlas portait deux
-- fabriques en activite (Dannemann, Menendez Amerino), une fermee
-- (Suerdieck) et une fiche de cape (Arturo Fuente Maduro). Bahia en
-- compte une dizaine. QUATRE ENTRENT :
--   Leite & Alves   Cachoeira, 1854 ou 1881 a Niteroi, Cachoeira 1936 ;
--                   Talvis, Le Cigar ; musee du tabac
--   Monte Pascoal   Tabacos Mata Fina, Cruz das Almas, 2007, Lorenzo
--                   Orsi — president de l'Apcab
--   JAMM Cigar      Alagoinhas, 2020 — 4 500 cigares par jour (2024)
--   Chaba           Alagoinhas, 1998 — heritiere de marques Suerdieck ;
--                   aucune presse depuis 2012, registre actif : ETAT DIT
-- DEUX ZONES : Cachoeira et Sao Felix (53), Alagoinhas (54) — ids
-- explicites (regle 143). DEUX FICHES COMPLETEES (Menendez Amerino :
-- 1977/1978 et les chiffres de 2012 ; Dannemann : 2012, 1892, l'Apcab)
-- par un paragraphe garde par le marqueur « Apcab ». Les notes du pays
-- disent le recensement et ce qu'il n'a PAS trouve : aucun atelier
-- hors de Bahia.
--
-- Non ecrites : San Francisco Charutos (une source, 2012, sept
-- personnes), Josefina (2001), Angelina, Julien Bahia, Paraguacu —
-- des noms, rien d'autre.
--
-- Et une retouche venue de la 226 : `founded` de Jose L. Piedra, que
-- le gabarit « Fondee en … » rendait illisible.
-- ════════════════════════════════════════════════════════

-- ── ZONES ──
INSERT INTO `production_zones` (`id`, `country_id`, `name`, `lat`, `lon`, `color`, `note`, `note_en`, `note_es`, `note_de`, `note_zh`, `note_ar`)
VALUES (53, 'brazil', 'Cachoeira et São Félix', -12.606, -38.968, '#8B5A2B', 'Les deux villes qui se font face sur le Paraguaçu : la fabrique de 1936 de Leite & Alves à Cachoeira, le Centro Dannemann à São Félix, où fut ouverte en 1842 la première fabrique de cigares du pays', 'The two towns facing each other across the Paraguaçu: Leite & Alves'' factory of 1936 in Cachoeira, the Centro Dannemann in São Félix, where the country''s first cigar factory opened in 1842', 'Las dos ciudades frente a frente sobre el Paraguaçu: la fábrica de 1936 de Leite & Alves en Cachoeira, el Centro Dannemann en São Félix, donde abrió en 1842 la primera fábrica de puros del país', 'Die beiden Städte, die sich über den Paraguaçu gegenüberliegen: die Fabrik von 1936 von Leite & Alves in Cachoeira, das Centro Dannemann in São Félix, wo 1842 die erste Zigarrenfabrik des Landes öffnete', '隔着帕拉瓜苏河相望的两座城：卡舒埃拉的 Leite & Alves 1936年工厂，圣费利克斯的 Centro Dannemann——1842年全国第一家雪茄厂就开在那里', 'المدينتان المتقابلتان على نهر باراغواسو: مصنع Leite & Alves من 1936 في كاشويرا، وCentro Dannemann في ساو فيليكس حيث فُتح سنة 1842 أوّل مصنع سيجار في البلاد')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `name` = VALUES(`name`), `lat` = VALUES(`lat`), `lon` = VALUES(`lon`), `color` = VALUES(`color`), `note` = VALUES(`note`), `note_en` = VALUES(`note_en`), `note_es` = VALUES(`note_es`), `note_de` = VALUES(`note_de`), `note_zh` = VALUES(`note_zh`), `note_ar` = VALUES(`note_ar`);

INSERT INTO `production_zones` (`id`, `country_id`, `name`, `lat`, `lon`, `color`, `note`, `note_en`, `note_es`, `note_de`, `note_zh`, `note_ar`)
VALUES (54, 'brazil', 'Alagoinhas', -12.1355, -38.4193, '#B8860B', 'Hors du Recôncavo, à 124 km de Salvador vers le nord : la fabrique et la ferme FEANBE de JAMM Cigar en bord de BR-110, et Chaba, l''héritière de marques Suerdieck', 'Outside the Recôncavo, 124 km north of Salvador: JAMM Cigar''s factory and FEANBE farm on the BR-110, and Chaba, heir to Suerdieck brands', 'Fuera del Recôncavo, a 124 km de Salvador hacia el norte: la fábrica y la hacienda FEANBE de JAMM Cigar junto a la BR-110, y Chaba, heredera de marcas Suerdieck', 'Außerhalb des Recôncavo, 124 km nördlich von Salvador: die Fabrik und die Farm FEANBE von JAMM Cigar an der BR-110, und Chaba, Erbin von Suerdieck-Marken', '在雷孔卡沃之外，萨尔瓦多以北124公里：JAMM Cigar 在 BR-110 公路旁的工厂和 FEANBE 农场，以及继承了 Suerdieck 品牌的 Chaba', 'خارج ريكونكافو، على 124 كم شمال سلفادور: مصنع JAMM Cigar ومزرعته FEANBE على طريق BR-110، وChaba وريثة علامات Suerdieck')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `name` = VALUES(`name`), `lat` = VALUES(`lat`), `lon` = VALUES(`lon`), `color` = VALUES(`color`), `note` = VALUES(`note`), `note_en` = VALUES(`note_en`), `note_es` = VALUES(`note_es`), `note_de` = VALUES(`note_de`), `note_zh` = VALUES(`note_zh`), `note_ar` = VALUES(`note_ar`);

-- ── Leite & Alves ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Leite & Alves',
        'brazil',
        '1854 ou 1881 — Niterói ; Cachoeira depuis 1936',
        'Fabrique propre à Cachoeira (Bahia) depuis 1936, avec un musée du tabac ; marques Talvis, Le Cigar et Leite & Alves ; tout à la main, tripe longue',
        'vilacharutaria.com.br, page Leite & Alves (fondée en 1854 à Niterói comme fabrique de cigarettes São Domingos ; Salvador en 1881, où commence le cigare ; Cachoeira depuis 1936 ; tabacs Mata Fina, Mata Sul et Mata Norte) ; pt.wikibooks.org « Charuto/História » (l''Imperial e Antiga Fábrica de Cigarros São Domingos fondée en 1881 à Niterói — divergence de date avec 1854, écrite) ; correiobraziliense.com.br « Muito além de Cuba » (10 février 2017 : Cachoeira, 1936, marques Talvis et Leite & Alves, 100 % artisanal) ; charutoso.com.br (13 mai 2020 : tripe longue, feuilles entières ; Petit Corona, Rothschild) ; blog.festivalorigens.com.br (visite de la fabrique, musée du tabac, Talvis l''une des plus anciennes lignes du pays) ; abras.com.br reprenant Valor Econômico (28 août 2012 : niche des cigares religieux) — sources en portugais',
        'Leite & Alves est la fabrique de Cachoeira, sur la rive du Paraguaçu qui fait face à São Félix, et l''une des plus anciennes maisons de cigares du Brésil — mais son âge dépend de ce qu''on compte. La maison fait remonter son origine à 1854, à Niterói, en face de Rio, où naquit une fabrique de cigarettes, São Domingos ; un manuel d''histoire du cigare date cette même fabrique impériale de 1881 ; la fiche écrit les deux. Ce qui ne diverge pas : en 1881 l''entreprise est à Salvador et commence le cigare, et en 1936 elle s''installe à Cachoeira, où elle est toujours.

Tout y est roulé à la main, en tripe longue, avec les tabacs du Recôncavo — Mata Fina, Mata Sul, Mata Norte — sous trois marques : Talvis, que la maison présente comme l''une des plus anciennes lignes de cigares du pays, Le Cigar, et Leite & Alves. La fabrique abrite un musée du tabac, documents, photographies et outils de l''histoire du cigare bahianais, que les visiteurs du festival du Recôncavo traversent avant la galerie des rouleuses.

La presse économique de 2012 la voyait chercher une niche — les cigares pour cérémonies religieuses — dans une Bahia où la production s''effondrait. L''atlas, qui portait Dannemann de l''autre côté du fleuve, porte désormais les deux rives.',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"L''une des plus anciennes lignes de cigares du pays, dit la maison ; Corona et Petit Corona en tripe longue."},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"Mata Fina ou Mata Norte (Bahia)","vitolas":[],"story":"La ligne au nom de la maison — Petit Corona, Rothschild ; Mata Fina, Mata Sul et Mata Norte, feuilles entières."},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"La troisième marque de la fabrique de Cachoeira."}]',
        'Leite & Alves is the Cachoeira factory, on the bank of the Paraguaçu facing São Félix, and one of Brazil''s oldest cigar houses — but its age depends on what one counts. The house traces its origin to 1854, in Niterói, across from Rio, where a cigarette factory, São Domingos, was born; a cigar history handbook dates that same imperial factory to 1881; the entry writes both. What does not differ: in 1881 the company is in Salvador and starts making cigars, and in 1936 it settles in Cachoeira, where it still is.

Everything is hand-rolled there, long filler, with the Recôncavo''s tobaccos — Mata Fina, Mata Sul, Mata Norte — under three brands: Talvis, which the house presents as one of the country''s oldest cigar lines, Le Cigar, and Leite & Alves. The factory houses a tobacco museum, documents, photographs and tools of the history of Bahian cigars, which visitors of the Recôncavo festival cross before the rollers'' gallery.

The business press of 2012 saw it seeking a niche — cigars for religious ceremonies — in a Bahia whose production was collapsing. This atlas, which carried Dannemann across the river, now carries both banks.',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"One of the country''s oldest cigar lines, says the house; Corona and Petit Corona in long filler."},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"Mata Fina or Mata Norte (Bahia)","vitolas":[],"story":"The line in the house''s name — Petit Corona, Rothschild; Mata Fina, Mata Sul and Mata Norte, whole leaves."},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"The Cachoeira factory''s third brand."}]',
        'Leite & Alves es la fábrica de Cachoeira, en la orilla del Paraguaçu que mira a São Félix, y una de las casas de puros más antiguas de Brasil — pero su edad depende de lo que se cuente. La casa remonta su origen a 1854, en Niterói, frente a Río, donde nació una fábrica de cigarrillos, São Domingos; un manual de historia del puro fecha esa misma fábrica imperial en 1881; la ficha escribe las dos. Lo que no diverge: en 1881 la empresa está en Salvador y empieza el puro, y en 1936 se instala en Cachoeira, donde sigue.

Todo se lía allí a mano, con tripa larga, con los tabacos del Recôncavo — Mata Fina, Mata Sul, Mata Norte — bajo tres marcas: Talvis, que la casa presenta como una de las líneas de puros más antiguas del país, Le Cigar, y Leite & Alves. La fábrica alberga un museo del tabaco, documentos, fotografías y herramientas de la historia del puro bahiano, que los visitantes del festival del Recôncavo atraviesan antes de la galería de las torcedoras.

La prensa económica de 2012 la veía buscar un nicho — los puros para ceremonias religiosas — en una Bahía cuya producción se hundía. Este atlas, que recogía a Dannemann al otro lado del río, recoge ahora las dos orillas.',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"Mata Fina (Bahía)","vitolas":[],"story":"Una de las líneas de puros más antiguas del país, dice la casa; Corona y Petit Corona con tripa larga."},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"Mata Fina o Mata Norte (Bahía)","vitolas":[],"story":"La línea con el nombre de la casa — Petit Corona, Rothschild; Mata Fina, Mata Sul y Mata Norte, hojas enteras."},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"Mata Fina (Bahía)","vitolas":[],"story":"La tercera marca de la fábrica de Cachoeira."}]',
        'Leite & Alves ist die Fabrik von Cachoeira, am Ufer des Paraguaçu gegenüber São Félix, und eines der ältesten Zigarrenhäuser Brasiliens — doch ihr Alter hängt davon ab, was man zählt. Das Haus führt seinen Ursprung auf 1854 zurück, in Niterói, gegenüber von Rio, wo eine Zigarettenfabrik entstand, São Domingos; ein Handbuch der Zigarrengeschichte datiert dieselbe kaiserliche Fabrik auf 1881; der Eintrag schreibt beide. Was nicht abweicht: 1881 ist das Unternehmen in Salvador und beginnt mit Zigarren, und 1936 lässt es sich in Cachoeira nieder, wo es noch ist.

Alles wird dort von Hand gerollt, Longfiller, mit den Tabaken des Recôncavo — Mata Fina, Mata Sul, Mata Norte — unter drei Marken: Talvis, die das Haus als eine der ältesten Zigarrenlinien des Landes vorstellt, Le Cigar und Leite & Alves. Die Fabrik beherbergt ein Tabakmuseum, Dokumente, Fotografien und Werkzeuge der Geschichte der bahianischen Zigarre, das die Besucher des Recôncavo-Festivals vor der Galerie der Rollerinnen durchqueren.

Die Wirtschaftspresse von 2012 sah sie eine Nische suchen — Zigarren für religiöse Zeremonien — in einem Bahia, dessen Produktion einbrach. Dieser Atlas, der Dannemann auf der anderen Flussseite führte, führt nun beide Ufer.',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Eine der ältesten Zigarrenlinien des Landes, sagt das Haus; Corona und Petit Corona in Longfiller."},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"Mata Fina oder Mata Norte (Bahia)","vitolas":[],"story":"Die Linie im Namen des Hauses — Petit Corona, Rothschild; Mata Fina, Mata Sul und Mata Norte, ganze Blätter."},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Die dritte Marke der Fabrik von Cachoeira."}]',
        'Leite & Alves 是卡舒埃拉的工厂，坐落在帕拉瓜苏河面对圣费利克斯的这一岸，是巴西较老的雪茄之家之一——但它的年龄取决于从哪里算起。公司把起源追溯到1854年里约对岸的尼泰罗伊，一家名为 São Domingos 的卷烟厂在那里诞生；一本雪茄史手册把这家帝国时期的工厂定在1881年；词条两者都写。没有分歧的是：1881年公司已在萨尔瓦多并开始做雪茄，1936年迁到卡舒埃拉，至今仍在。

那里全部手工卷制，长茄芯，用雷孔卡沃的烟叶——Mata Fina、Mata Sul、Mata Norte——分三个品牌：Talvis，公司称之为全国较老的雪茄产品线之一；Le Cigar；以及 Leite & Alves。工厂设有一座烟草博物馆，收藏巴伊亚雪茄史的文件、照片和工具，雷孔卡沃节的访客先经过博物馆再进入卷工车间。

2012年的经济媒体看到它在一个产量崩塌的巴伊亚寻找细分市场——宗教仪式用雪茄。本图集原本只收录河对岸的 Dannemann，如今两岸都有。',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"Mata Fina（巴伊亚）","vitolas":[],"story":"公司称是全国较老的雪茄产品线之一；Corona 和 Petit Corona，长茄芯。"},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"Mata Fina 或 Mata Norte（巴伊亚）","vitolas":[],"story":"以公司命名的产品线——Petit Corona、Rothschild；Mata Fina、Mata Sul、Mata Norte，整叶。"},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"Mata Fina（巴伊亚）","vitolas":[],"story":"卡舒埃拉工厂的第三个品牌。"}]',
        'Leite & Alves مصنع كاشويرا، على ضفّة نهر باراغواسو المواجهة لساو فيليكس، ومن أقدم دور السيجار في البرازيل — لكنّ عمرها يتوقّف على ما يُحسب. تعيد الدار أصلها إلى 1854 في نيتيروي، قبالة ريو، حيث وُلد مصنع سجائر اسمه São Domingos؛ ويؤرّخ كتاب في تاريخ السيجار المصنعَ الإمبراطوري نفسه بسنة 1881؛ تكتب البطاقة الاثنتين. وما لا يختلف: سنة 1881 الشركة في سلفادور وتبدأ السيجار، وسنة 1936 تستقرّ في كاشويرا حيث ما زالت.

يُلفّ كلّ شيء هناك يدويًّا، بحشوة طويلة، بتبغ ريكونكافو — ماتا فينا وماتا سول وماتا نورتي — تحت ثلاث علامات: Talvis، التي تقدّمها الدار بوصفها من أقدم خطوط السيجار في البلاد، وLe Cigar، وLeite & Alves. ويضمّ المصنع متحفًا للتبغ، وثائق وصورًا وأدوات من تاريخ السيجار الباهياني، يعبره زوّار مهرجان ريكونكافو قبل قاعة اللفّافات.

رأتها الصحافة الاقتصادية سنة 2012 تبحث عن سوق ضيّقة — سيجار الطقوس الدينية — في باهيا كان إنتاجها ينهار. وهذا الأطلس، الذي كان يحمل Dannemann على الضفّة الأخرى، يحمل الآن الضفّتين.',
        '[{"name":"Talvis","color":"#8B4513","force":"Mild-Medium","wrapper":"ماتا فينا (باهيا)","vitolas":[],"story":"من أقدم خطوط السيجار في البلاد كما تقول الدار؛ Corona وPetit Corona بحشوة طويلة."},{"name":"Leite & Alves","color":"#6B4226","force":"Mild-Medium","wrapper":"ماتا فينا أو ماتا نورتي (باهيا)","vitolas":[],"story":"الخطّ باسم الدار — Petit Corona وRothschild؛ ماتا فينا وماتا سول وماتا نورتي، أوراق كاملة."},{"name":"Le Cigar","color":"#A0522D","force":"Medium","wrapper":"ماتا فينا (باهيا)","vitolas":[],"story":"العلامة الثالثة لمصنع كاشويرا."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Monte Pascoal ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Monte Pascoal',
        'brazil',
        '2007 — Cruz das Almas (Bahia) ; Lorenzo Orsi',
        'Tabacos Mata Fina, Cruz das Almas (Recôncavo) — la fabrique de Lorenzo Orsi ; tout à la main, feuilles entières, tabac cent pour cent brésilien',
        'charutoso.com.br « Descubra sobre os charutos Monte Pascoal » (9 avril 2024 : marque de Tabacos Mata Fina, Cruz das Almas ; Lorenzo Orsi ; tabac cent pour cent national, Mata Fina et Mata Norte ; roulé main ; maturation d''au moins trois mois ; boîtes de 25 et de 10) ; vilacharutaria.com.br, page Monte Pascoal (fondée en 2007 par Lorenzo Orsi ; six vitoles en feuilles entières ; la découverte du Brésil sur les boîtes) ; www.fortenoreconcavo.com.br « Projeto para charutos do Recôncavo entra em fase final » (23 juillet 2026 : Lorenzo Orsi président de l''Apcab ; dénomination d''origine Tabaco Mata Fina e Charutos Artesanais do Recôncavo Baiano en préparation à l''INPI ; quatre fabricants pour environ 85 % du segment artisanal) ; blog.festivalorigens.com.br (Monte Pascoal parmi les fabriques visitées) — sources en portugais',
        'Monte Pascoal est la marque de Tabacos Mata Fina, la fabrique que Lorenzo Orsi a fondée en 2007 à Cruz das Almas, au cœur du Recôncavo, avec l''idée d''un cigare brésilien de haut de gamme qui ne ressemble à rien d''autre parce qu''il ne vient que d''ici : tabac cent pour cent national, Mata Fina pour l''arôme, Mata Norte pour la force, et chaque vitole avec son propre dosage des deux. Le nom est celui du mont que Cabral aperçut en 1500, et les boîtes racontent la découverte du Brésil ; le matériel graphique, dit la presse du cigare, est imprimé aux Pays-Bas.

Tout est roulé à la main, en feuilles entières ; chaque cigare passe un contrôle de tirage, de finition et de couleur de cape, puis attend au moins trois mois avant la vente. Six vitoles, en boîtes de vingt-cinq et de dix.

Lorenzo Orsi préside l''Apcab, l''association des producteurs de cigares artisanaux du Brésil, qui portait en juillet 2026 à l''INPI une dénomination d''origine pour le tabac Mata Fina et les cigares artisanaux du Recôncavo — quatre fabricants, dit le projet, pour environ 85 % du segment artisanal du pays. L''atlas, qui portait le Recôncavo par une seule fabrique en activité, en porte désormais quatre.',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"Mata Fina ou Mata Norte (Bahia)","vitolas":[],"story":"Six vitoles, chacune avec son dosage de Mata Fina et de Mata Norte ; tout à la main, feuilles entières, trois mois de repos avant la vente."}]',
        'Monte Pascoal is the brand of Tabacos Mata Fina, the factory Lorenzo Orsi founded in 2007 in Cruz das Almas, in the heart of the Recôncavo, with the idea of a premium Brazilian cigar that resembles nothing else because it comes only from here: one hundred percent national tobacco, Mata Fina for aroma, Mata Norte for strength, and each size with its own dose of the two. The name is that of the mount Cabral sighted in 1500, and the boxes tell the discovery of Brazil; the graphic material, says the cigar press, is printed in the Netherlands.

Everything is hand-rolled, in whole leaves; each cigar passes a check of draw, finish and wrapper colour, then waits at least three months before sale. Six sizes, in boxes of twenty-five and of ten.

Lorenzo Orsi chairs Apcab, the association of Brazil''s artisanal cigar producers, which in July 2026 was bringing to the INPI a designation of origin for Mata Fina tobacco and the Recôncavo''s artisanal cigars — four manufacturers, says the project, for about 85% of the country''s artisanal segment. This atlas, which carried the Recôncavo through a single working factory, now carries four.',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"Mata Fina or Mata Norte (Bahia)","vitolas":[],"story":"Six sizes, each with its own dose of Mata Fina and Mata Norte; all by hand, whole leaves, three months of rest before sale."}]',
        'Monte Pascoal es la marca de Tabacos Mata Fina, la fábrica que Lorenzo Orsi fundó en 2007 en Cruz das Almas, en el corazón del Recôncavo, con la idea de un puro brasileño de alta gama que no se parezca a nada porque solo viene de aquí: tabaco cien por cien nacional, Mata Fina para el aroma, Mata Norte para la fuerza, y cada vitola con su propia dosis de los dos. El nombre es el del monte que Cabral avistó en 1500, y las cajas cuentan el descubrimiento de Brasil; el material gráfico, dice la prensa del puro, se imprime en los Países Bajos.

Todo se lía a mano, en hojas enteras; cada puro pasa un control de tiro, de acabado y de color de capa, y luego espera al menos tres meses antes de la venta. Seis vitolas, en cajas de veinticinco y de diez.

Lorenzo Orsi preside la Apcab, la asociación de productores de puros artesanales de Brasil, que en julio de 2026 llevaba al INPI una denominación de origen para el tabaco Mata Fina y los puros artesanales del Recôncavo — cuatro fabricantes, dice el proyecto, para cerca del 85 % del segmento artesanal del país. Este atlas, que recogía el Recôncavo por una sola fábrica en actividad, recoge ahora cuatro.',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"Mata Fina o Mata Norte (Bahía)","vitolas":[],"story":"Seis vitolas, cada una con su dosis de Mata Fina y Mata Norte; todo a mano, hojas enteras, tres meses de reposo antes de la venta."}]',
        'Monte Pascoal ist die Marke von Tabacos Mata Fina, der Fabrik, die Lorenzo Orsi 2007 in Cruz das Almas im Herzen des Recôncavo gründete, mit der Idee einer brasilianischen Premiumzigarre, die nichts anderem gleicht, weil sie nur von hier kommt: hundert Prozent nationaler Tabak, Mata Fina für das Aroma, Mata Norte für die Stärke, und jedes Format mit seiner eigenen Dosierung der beiden. Der Name ist der des Berges, den Cabral 1500 sichtete, und die Kisten erzählen die Entdeckung Brasiliens; das grafische Material, sagt die Zigarrenpresse, wird in den Niederlanden gedruckt.

Alles wird von Hand gerollt, aus ganzen Blättern; jede Zigarre besteht eine Prüfung von Zug, Verarbeitung und Deckblattfarbe und wartet dann mindestens drei Monate vor dem Verkauf. Sechs Formate, in Kisten zu fünfundzwanzig und zu zehn.

Lorenzo Orsi führt die Apcab, den Verband der handwerklichen Zigarrenhersteller Brasiliens, der im Juli 2026 beim INPI eine Ursprungsbezeichnung für den Mata-Fina-Tabak und die handwerklichen Zigarren des Recôncavo einreichte — vier Hersteller, sagt das Projekt, für etwa 85 % des handwerklichen Segments des Landes. Dieser Atlas, der den Recôncavo mit einer einzigen tätigen Fabrik führte, führt nun vier.',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"Mata Fina oder Mata Norte (Bahia)","vitolas":[],"story":"Sechs Formate, jedes mit seiner Dosierung von Mata Fina und Mata Norte; ganz von Hand, ganze Blätter, drei Monate Ruhe vor dem Verkauf."}]',
        'Monte Pascoal 是 Tabacos Mata Fina 的品牌，那是洛伦佐·奥尔西2007年在雷孔卡沃腹地克鲁斯-达斯阿尔马斯创办的工厂，想法是做一支不像任何别处、因为只来自此地的巴西高档雪茄：百分之百本国烟叶，Mata Fina 出香气，Mata Norte 出劲道，每种规格有自己的两者配比。名字取自卡布拉尔1500年望见的那座山，盒子讲述巴西的发现；雪茄媒体说，印刷品在荷兰印制。

全部手工卷制，整叶；每支雪茄要经过抽吸、做工和茄衣色泽的检查，然后至少等三个月才出售。六种规格，二十五支和十支装。

洛伦佐·奥尔西任 Apcab（巴西手工雪茄生产者协会）主席，该协会2026年7月正向 INPI 提交 Mata Fina 烟草与雷孔卡沃手工雪茄的原产地命名——项目称，四家制造商占全国手工雪茄市场约85%。本图集原本只通过一家在营工厂收录雷孔卡沃，如今有四家。',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"Mata Fina 或 Mata Norte（巴伊亚）","vitolas":[],"story":"六种规格，各有自己的 Mata Fina 与 Mata Norte 配比；全手工，整叶，售前静置三个月。"}]',
        'Monte Pascoal علامة Tabacos Mata Fina، المصنع الذي أسّسه لورينزو أورسي سنة 2007 في كروز داس ألماس، في قلب ريكونكافو، بفكرة سيجار برازيلي راقٍ لا يشبه شيئًا آخر لأنّه لا يأتي إلّا من هنا: تبغ وطني مئة بالمئة، ماتا فينا للعطر وماتا نورتي للقوّة، ولكلّ قياس جرعته الخاصّة من الاثنين. الاسم اسم الجبل الذي أبصره كابرال سنة 1500، والعلب تروي اكتشاف البرازيل؛ أمّا المواد المطبوعة فتُطبع في هولندا، كما تقول صحافة السيجار.

كلّ شيء يُلفّ يدويًّا بأوراق كاملة؛ ويجتاز كلّ سيجار فحصًا للسحب والإتقان ولون الغلاف، ثمّ ينتظر ثلاثة شهور على الأقلّ قبل البيع. ستّة قياسات، في علب من خمسة وعشرين ومن عشرة.

يرأس لورينزو أورسي جمعية Apcab، جمعية منتجي السيجار الحرفي في البرازيل، التي كانت في يوليو 2026 تحمل إلى معهد INPI تسمية منشأ لتبغ ماتا فينا والسيجار الحرفي في ريكونكافو — أربعة صانعين، يقول المشروع، لنحو 85 % من القطاع الحرفي في البلاد. وهذا الأطلس، الذي كان يحمل ريكونكافو بمصنع واحد عامل، يحمل الآن أربعة.',
        '[{"name":"Monte Pascoal","color":"#2E5E3A","force":"Medium","wrapper":"ماتا فينا أو ماتا نورتي (باهيا)","vitolas":[],"story":"ستّة قياسات، لكلّ منها جرعته من ماتا فينا وماتا نورتي؛ كلّه باليد، أوراق كاملة، ثلاثة شهور من الراحة قبل البيع."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── JAMM Cigar ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('JAMM Cigar',
        'brazil',
        '2020 — Alagoinhas (Bahia) ; J. A. M. Monteiro',
        'Fabrique propre en bord de BR-110, Alagoinhas, avec la ferme FEANBE (2016) ; une centaine de personnes directes et indirectes (2022) ; 4 500 cigares par jour dont 2 500 en tripe longue (2024)',
        'maisriodejaneiro.com « JAMM Cigar: mistura brasileira para um charuto de excelência » (novembre 2022 : fondée deux ans et demi plus tôt ; ferme FEANBE achetée en 2016 à Alagoinhas ; fabrique en bord de BR-110, trois agrandissements ; une centaine de personnes directes et indirectes ; Mata Fina du Recôncavo et tabac de semence cubaine planté au Brésil ; les initiales des deux amis, José Antônio Martins Monteiro et Joaquim Alfredo Mesquita Moreira, rencontrés au Canada ; lignes tripe longue et tripe courte) ; ronaldojacobina.com.br (9 octobre 2024 : production commerciale depuis 2021 ; 4 500 cigares par jour, 2 500 en tripe longue ; Alagoinhas à 124 km de Salvador ; deux adresses de dégustation à Salvador ; le fondateur venait des agrumes) ; www.fortenoreconcavo.com.br (23 juillet 2026 : José Antônio Martins Monteiro, directeur, dans le projet de dénomination d''origine de l''Apcab) ; revistadeguste.com — sources en portugais',
        'JAMM Cigar est née d''un cigare offert dans un casino près des chutes du Niagara : José Antônio Martins Monteiro, producteur d''oranges, de citrons et de mandarines dans le nord de Bahia, y rencontra Joaquim Alfredo Mesquita Moreira, qui lui tendit son premier cigare de prix. Les initiales des deux amis font le nom de la marque. Il a d''abord roulé pour lui-même et pour offrir, raconte-t-il, jusqu''au jour où son comptable lui a montré ce que cela coûtait ; il en a fait une entreprise. La ferme FEANBE, achetée en 2016 à Alagoinhas, à 124 km de Salvador, porte la fabrique, en bord de la BR-110, fondée en 2020 selon la presse de 2022 et en production commerciale depuis 2021.

La fabrique a été agrandie trois fois en deux ans. Une centaine de personnes en vivent, directement ou non, disait la presse en 2022 ; en 2024 elle sortait 4 500 cigares par jour, dont 2 500 en tripe longue — le reste en tripe moyenne et courte, que l''atlas laisse. Le mélange marie le Mata Fina du Recôncavo et un tabac de semence cubaine planté au Brésil ; les lignes longues s''appellent Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito.

C''est la maison la plus jeune du Brésil dans cet atlas, et déjà l''une des quatre que l''Apcab compte pour l''essentiel du segment artisanal du pays ; son fondateur siège au projet de dénomination d''origine de 2026. Alagoinhas n''est pas le Recôncavo — c''est plus au nord, hors de la vallée du Paraguaçu — et l''atlas ouvre pour elle une zone.',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Les lignes en tripe longue — Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito — sur Mata Fina et semence cubaine plantée au Brésil."}]',
        'JAMM Cigar was born of a cigar offered in a casino near Niagara Falls: José Antônio Martins Monteiro, a grower of oranges, lemons and tangerines in northern Bahia, met there Joaquim Alfredo Mesquita Moreira, who handed him his first fine cigar. The two friends'' initials make the brand''s name. He first rolled for himself and for gifts, he says, until the day his accountant showed him what it cost; he made a business of it. The FEANBE farm, bought in 2016 at Alagoinhas, 124 km from Salvador, carries the factory, on the BR-110, founded in 2020 according to the 2022 press and in commercial production since 2021.

The factory was enlarged three times in two years. About a hundred people live from it, directly or not, the press said in 2022; in 2024 it turned out 4,500 cigars a day, 2,500 of them long filler — the rest medium and short filler, which this atlas leaves. The blend marries the Recôncavo''s Mata Fina with a Cuban-seed tobacco grown in Brazil; the long lines are called Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito.

It is Brazil''s youngest house in this atlas, and already one of the four Apcab counts for the bulk of the country''s artisanal segment; its founder sits on the 2026 designation-of-origin project. Alagoinhas is not the Recôncavo — it is further north, outside the Paraguaçu valley — and this atlas opens a zone for it.',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"The long-filler lines — Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito — on Mata Fina and Cuban seed grown in Brazil."}]',
        'JAMM Cigar nació de un puro ofrecido en un casino cerca de las cataratas del Niágara: José Antônio Martins Monteiro, productor de naranjas, limones y mandarinas en el norte de Bahía, conoció allí a Joaquim Alfredo Mesquita Moreira, que le tendió su primer puro de precio. Las iniciales de los dos amigos hacen el nombre de la marca. Primero lió para él y para regalar, cuenta, hasta el día en que su contador le mostró lo que costaba; hizo de ello una empresa. La hacienda FEANBE, comprada en 2016 en Alagoinhas, a 124 km de Salvador, sostiene la fábrica, junto a la BR-110, fundada en 2020 según la prensa de 2022 y en producción comercial desde 2021.

La fábrica se amplió tres veces en dos años. Un centenar de personas viven de ella, directa o indirectamente, decía la prensa en 2022; en 2024 sacaba 4 500 puros al día, 2 500 de ellos con tripa larga — el resto con tripa media y corta, que el atlas deja. La ligada casa el Mata Fina del Recôncavo con un tabaco de semilla cubana plantado en Brasil; las líneas largas se llaman Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito.

Es la casa más joven de Brasil en este atlas, y ya una de las cuatro que la Apcab cuenta para lo esencial del segmento artesanal del país; su fundador forma parte del proyecto de denominación de origen de 2026. Alagoinhas no es el Recôncavo — está más al norte, fuera del valle del Paraguaçu — y el atlas abre para ella una zona.',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"Mata Fina (Bahía)","vitolas":[],"story":"Las líneas con tripa larga — Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito — sobre Mata Fina y semilla cubana plantada en Brasil."}]',
        'JAMM Cigar entstand aus einer Zigarre, die in einem Casino bei den Niagarafällen angeboten wurde: José Antônio Martins Monteiro, Anbauer von Orangen, Zitronen und Mandarinen im Norden Bahias, traf dort Joaquim Alfredo Mesquita Moreira, der ihm seine erste teure Zigarre reichte. Die Initialen der beiden Freunde bilden den Namen der Marke. Er rollte zuerst für sich und zum Verschenken, erzählt er, bis sein Buchhalter ihm eines Tages zeigte, was es kostete; er machte ein Unternehmen daraus. Die Farm FEANBE, 2016 in Alagoinhas gekauft, 124 km von Salvador, trägt die Fabrik an der BR-110, gegründet 2020 laut der Presse von 2022 und seit 2021 in kommerzieller Produktion.

Die Fabrik wurde in zwei Jahren dreimal erweitert. Etwa hundert Menschen leben davon, direkt oder nicht, sagte die Presse 2022; 2024 brachte sie 4 500 Zigarren am Tag hervor, 2 500 davon Longfiller — der Rest Medium- und Shortfiller, den dieser Atlas lässt. Die Mischung vermählt den Mata Fina des Recôncavo mit einem in Brasilien angebauten Tabak aus kubanischem Saatgut; die langen Linien heißen Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito.

Es ist das jüngste Haus Brasiliens in diesem Atlas, und schon eines der vier, die die Apcab für den Großteil des handwerklichen Segments des Landes zählt; ihr Gründer sitzt im Projekt der Ursprungsbezeichnung von 2026. Alagoinhas ist nicht der Recôncavo — es liegt weiter nördlich, außerhalb des Paraguaçu-Tals —, und dieser Atlas öffnet dafür eine Zone.',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Die Longfiller-Linien — Super Premium, Robusto Premium, Petit Lonsdale, Churchill, Gordito — auf Mata Fina und in Brasilien angebautem kubanischem Saatgut."}]',
        'JAMM Cigar 源于尼亚加拉瀑布附近一家赌场里递来的一支雪茄：巴伊亚北部种橙子、柠檬和橘子的何塞·安东尼奥·马丁斯·蒙泰罗，在那里认识了若阿金·阿尔弗雷多·梅斯基塔·莫雷拉，后者递给他第一支高价雪茄。两位朋友的姓名首字母组成了品牌名。他说，起初只为自己和送人而卷，直到会计给他算了成本，他才把它做成生意。2016年在离萨尔瓦多124公里的阿拉戈伊尼亚斯买下的 FEANBE 农场承载着 BR-110 公路旁的工厂，据2022年媒体报道成立于2020年，2021年起商业化生产。

工厂两年内扩建三次。2022年媒体称约有一百人直接或间接靠它生活；2024年日产4500支，其中2500支为长茄芯——其余为中、短茄芯，本图集不收。配方把雷孔卡沃的 Mata Fina 与在巴西种植的古巴种烟叶结合；长茄芯系列名为 Super Premium、Robusto Premium、Petit Lonsdale、Churchill、Gordito。

它是本图集中巴西年轻的一家，却已是 Apcab 认定的、占全国手工雪茄主要份额的四家之一；创始人参与2026年的原产地命名项目。阿拉戈伊尼亚斯不属于雷孔卡沃——它更靠北，在帕拉瓜苏河谷之外——本图集为它开辟一个产区。',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"Mata Fina（巴伊亚）","vitolas":[],"story":"长茄芯系列——Super Premium、Robusto Premium、Petit Lonsdale、Churchill、Gordito——用 Mata Fina 和在巴西种植的古巴种。"}]',
        'وُلدت JAMM Cigar من سيجار قُدّم في كازينو قرب شلالات نياغارا: خوسيه أنطونيو مارتينس مونتيرو، مزارع البرتقال والليمون واليوسفي في شمال باهيا، التقى هناك جواكيم ألفريدو ميسكيتا موريرا الذي ناوله سيجاره الثمين الأوّل. والأحرف الأولى من اسمي الصديقين تصنع اسم العلامة. لفّ أوّلًا لنفسه وللإهداء، كما يروي، حتّى أراه محاسبه يومًا ما يكلّفه ذلك؛ فجعل منه شركة. وتحمل مزرعة FEANBE، المشتراة سنة 2016 في ألاغوينياس على 124 كم من سلفادور، المصنعَ على طريق BR-110، المؤسَّس سنة 2020 بحسب صحافة 2022 وفي إنتاج تجاري منذ 2021.

وُسّع المصنع ثلاث مرّات في سنتين. يعيش منه نحو مئة شخص، مباشرة أو لا، كما قالت الصحافة سنة 2022؛ وسنة 2024 كان يُخرج 4500 سيجار في اليوم، 2500 منها بحشوة طويلة — والباقي بحشوة متوسّطة وقصيرة يتركه هذا الأطلس. تزاوج الخلطة ماتا فينا ريكونكافو مع تبغ من بذور كوبية يُزرع في البرازيل؛ وتُسمّى الخطوط الطويلة Super Premium وRobusto Premium وPetit Lonsdale وChurchill وGordito.

هي أحدث دار برازيلية في هذا الأطلس، وهي بالفعل إحدى الدور الأربع التي تعدّها Apcab لمعظم القطاع الحرفي في البلاد؛ ويجلس مؤسّسها في مشروع تسمية المنشأ لسنة 2026. وألاغوينياس ليست ريكونكافو — فهي أبعد شمالًا، خارج وادي باراغواسو — ويفتح لها هذا الأطلس منطقة.',
        '[{"name":"JAMM Premium","color":"#5C2E1E","force":"Medium-Full","wrapper":"ماتا فينا (باهيا)","vitolas":[],"story":"خطوط الحشوة الطويلة — Super Premium وRobusto Premium وPetit Lonsdale وChurchill وGordito — على ماتا فينا وبذور كوبية تُزرع في البرازيل."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Chaba ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Chaba',
        'brazil',
        '1998 — Alagoinhas (Bahia) ; Fernando Fraga',
        'Rua Jonas de Melo Pereira 15, Jardim Petrolar, Alagoinhas — 80 personnes, puis 25 à la réouverture de 2011 ; registre d''entreprise actif en 2026, aucune presse depuis 2012',
        'abras.com.br reprenant Valor Econômico « Encolhe a produção de charutos na Bahia » (28 août 2012 : Fernando Fraga, 73 ans, ancien de Suerdieck et héritier de certaines de ses marques ; Alagoinhas ; 80 employés, saisie de la production par l''Anvisa en 2010 pour irrégularités d''enregistrement, fermeture puis réouverture l''année suivante avec 25 personnes) ; econodata.com.br, registre de Chaba Charutos da Bahia Ltda (fondée le 28 octobre 1998 ; Rua Jonas de Melo Pereira 15, Jardim Petrolar ; Fernando Alberto Fraga administrateur ; statut actif) ; correiobraziliense.com.br (10 février 2017 : Chaba parmi les fabriques de Bahia) — l''atlas n''a trouvé aucun article après 2012 : l''état de la maison est écrit dans la fiche',
        'Chaba — Charutos da Bahia — est la maison de Fernando Fraga à Alagoinhas, dans le nord de Bahia, et c''est un morceau de Suerdieck qui a survécu à Suerdieck. Fraga y avait fait sa carrière ; quand la grande fabrique de Maragojipe, qui avait employé plus de deux mille personnes, ferma sa dernière unité en 2000, il hérita de certaines de ses marques et les fit vivre dans sa propre société, enregistrée le 28 octobre 1998.

La presse économique de 2012 raconte la suite : quatre-vingts employés, puis, en 2010, une saisie de la production par l''agence sanitaire pour des irrégularités d''enregistrement, la fermeture, et la réouverture l''année suivante avec vingt-cinq personnes. Fraga avait alors soixante-treize ans. Les listes de fabriques bahianaises de 2017 la comptent encore, à Alagoinhas.

Depuis, rien : l''atlas n''a trouvé aucun article après 2012, et le registre des entreprises la dit active en 2026, à la même adresse, sous le même administrateur. La fiche est écrite au passé là où elle le doit, et ne prétend pas savoir si l''on y roule encore — c''est la règle de l''atlas pour les maisons qu''on ne peut pas vérifier.',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Les marques héritées de Suerdieck, roulées à Alagoinhas — état de la production non vérifié depuis 2012."}]',
        'Chaba — Charutos da Bahia — is Fernando Fraga''s house in Alagoinhas, in northern Bahia, and it is a piece of Suerdieck that outlived Suerdieck. Fraga had made his career there; when the great Maragojipe factory, which had employed more than two thousand people, closed its last unit in 2000, he inherited some of its brands and kept them alive in his own company, registered on 28 October 1998.

The business press of 2012 tells the rest: eighty employees, then, in 2010, a seizure of production by the health agency for registration irregularities, the closure, and the reopening the following year with twenty-five people. Fraga was then seventy-three. The 2017 lists of Bahian factories still count it, at Alagoinhas.

Since then, nothing: this atlas has found no article after 2012, and the company register says it is active in 2026, at the same address, under the same administrator. The entry is written in the past tense where it must be, and does not claim to know whether rolling still goes on there — that is the atlas''s rule for houses that cannot be verified.',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"The brands inherited from Suerdieck, rolled at Alagoinhas — production status unverified since 2012."}]',
        'Chaba — Charutos da Bahia — es la casa de Fernando Fraga en Alagoinhas, en el norte de Bahía, y es un pedazo de Suerdieck que sobrevivió a Suerdieck. Fraga había hecho allí su carrera; cuando la gran fábrica de Maragojipe, que había empleado a más de dos mil personas, cerró su última unidad en 2000, heredó algunas de sus marcas y las hizo vivir en su propia sociedad, registrada el 28 de octubre de 1998.

La prensa económica de 2012 cuenta lo demás: ochenta empleados, luego, en 2010, una incautación de la producción por la agencia sanitaria por irregularidades de registro, el cierre, y la reapertura al año siguiente con veinticinco personas. Fraga tenía entonces setenta y tres años. Las listas de fábricas bahianas de 2017 aún la cuentan, en Alagoinhas.

Desde entonces, nada: el atlas no ha encontrado ningún artículo después de 2012, y el registro de empresas la dice activa en 2026, en la misma dirección, bajo el mismo administrador. La ficha está escrita en pasado donde debe, y no pretende saber si allí se sigue liando — es la regla del atlas para las casas que no se pueden verificar.',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"Mata Fina (Bahía)","vitolas":[],"story":"Las marcas heredadas de Suerdieck, liadas en Alagoinhas — estado de la producción no verificado desde 2012."}]',
        'Chaba — Charutos da Bahia — ist das Haus von Fernando Fraga in Alagoinhas im Norden Bahias, und es ist ein Stück Suerdieck, das Suerdieck überlebt hat. Fraga hatte dort seine Laufbahn gemacht; als die große Fabrik von Maragojipe, die über zweitausend Menschen beschäftigt hatte, 2000 ihre letzte Einheit schloss, erbte er einige ihrer Marken und hielt sie in seiner eigenen, am 28. Oktober 1998 eingetragenen Gesellschaft am Leben.

Die Wirtschaftspresse von 2012 erzählt den Rest: achtzig Beschäftigte, dann 2010 eine Beschlagnahme der Produktion durch die Gesundheitsbehörde wegen Unregelmäßigkeiten bei der Registrierung, die Schließung und die Wiedereröffnung im Jahr darauf mit fünfundzwanzig Leuten. Fraga war damals dreiundsiebzig. Die Listen bahianischer Fabriken von 2017 zählen sie noch, in Alagoinhas.

Seither nichts: Dieser Atlas hat keinen Artikel nach 2012 gefunden, und das Unternehmensregister nennt sie 2026 aktiv, unter derselben Adresse, mit demselben Verwalter. Der Eintrag ist im Präteritum geschrieben, wo er es sein muss, und behauptet nicht zu wissen, ob dort noch gerollt wird — das ist die Regel des Atlas für Häuser, die sich nicht prüfen lassen.',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"Mata Fina (Bahia)","vitolas":[],"story":"Die von Suerdieck geerbten Marken, in Alagoinhas gerollt — Produktionsstand seit 2012 nicht geprüft."}]',
        'Chaba——Charutos da Bahia——是费尔南多·弗拉加在巴伊亚北部阿拉戈伊尼亚斯的公司，是 Suerdieck 留下的、比 Suerdieck 活得更久的一块。弗拉加在那里度过了职业生涯；当曾雇用两千多人的马拉戈吉佩大厂于2000年关闭最后一个单位时，他继承了其中一些品牌，并让它们在自己1998年10月28日注册的公司里延续。

2012年的经济媒体讲了后来的事：八十名员工；2010年卫生监管机构因注册不合规查扣产品，工厂关闭，次年以二十五人重开。弗拉加当时七十三岁。2017年的巴伊亚工厂名单仍把它算在阿拉戈伊尼亚斯。

此后再无消息：本图集没有找到2012年之后的任何报道，企业登记显示它2026年仍在同一地址、同一管理人名下处于活跃状态。词条在该用过去时的地方用过去时，不假装知道那里是否还在卷制——这是图集对无法核实的公司的规则。',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"Mata Fina（巴伊亚）","vitolas":[],"story":"继承自 Suerdieck 的品牌，在阿拉戈伊尼亚斯卷制——生产状况自2012年起未经核实。"}]',
        'Chaba — Charutos da Bahia — دار فرناندو فراغا في ألاغوينياس شمال باهيا، وهي قطعة من Suerdieck عاشت بعد Suerdieck. صنع فراغا مسيرته هناك؛ وحين أغلق مصنع ماراغوجيبي الكبير، الذي كان يشغّل أكثر من ألفي شخص، وحدته الأخيرة سنة 2000، ورث بعض علاماته وأحياها في شركته الخاصّة المسجّلة في 28 أكتوبر 1998.

تروي الصحافة الاقتصادية سنة 2012 البقية: ثمانون موظّفًا، ثمّ سنة 2010 حجزٌ للإنتاج من هيئة الرقابة الصحية بسبب مخالفات في التسجيل، فالإغلاق، ثمّ إعادة الفتح في السنة التالية بخمسة وعشرين شخصًا. وكان فراغا حينها في الثالثة والسبعين. وما زالت قوائم مصانع باهيا لسنة 2017 تعدّها في ألاغوينياس.

ومنذ ذلك الحين لا شيء: لم يجد هذا الأطلس أيّ مقال بعد 2012، ويقول سجلّ الشركات إنّها نشطة سنة 2026 في العنوان نفسه وتحت المدير نفسه. كُتبت البطاقة بصيغة الماضي حيث يجب، ولا تدّعي معرفة ما إذا كان اللفّ ما زال جاريًا هناك — تلك قاعدة الأطلس للدور التي لا يمكن التحقّق منها.',
        '[{"name":"Chaba","color":"#7A4B2A","force":"Medium","wrapper":"ماتا فينا (باهيا)","vitolas":[],"story":"العلامات الموروثة من Suerdieck، تُلفّ في ألاغوينياس — حال الإنتاج غير متحقَّق منه منذ 2012."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Menendez Amerino : paragraphe ajoute, six langues (marqueur Apcab) ──
UPDATE `brands` SET `history` = CONCAT(`history`, '\n\n', 'Deux dates pour une fondation : 1977 dans cet atlas et chez la maison, 1978 dans un reportage de 2017 ; la fiche écrit les deux. La presse économique de 2012 mesurait la chute : quinze mille cigares par jour à la fin des années 1990, mille cinq cents en 2012, plus quatre cent mille cigarillos par mois ; quatre cents employés autrefois, cent cinquante trois ans plus tôt, soixante-dix alors, à plus de 90 % des femmes — et toujours la plus grande fabrique du pays. En 2026, son vice-président José Henrique Barreto siège à l''Apcab, l''association qui porte la dénomination d''origine des cigares du Recôncavo.') WHERE `name` = 'Menendez Amerino' AND `history` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_en` = CONCAT(`history_en`, '\n\n', 'Two dates for one founding: 1977 in this atlas and at the house, 1978 in a 2017 report; the entry writes both. The business press of 2012 measured the fall: fifteen thousand cigars a day in the late 1990s, fifteen hundred in 2012, plus four hundred thousand cigarillos a month; four hundred employees once, a hundred and fifty three years earlier, seventy then, more than 90% women — and still the country''s largest factory. In 2026 its vice-president José Henrique Barreto sits on Apcab, the association carrying the designation of origin for the Recôncavo''s cigars.') WHERE `name` = 'Menendez Amerino' AND `history_en` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_es` = CONCAT(`history_es`, '\n\n', 'Dos fechas para una fundación: 1977 en este atlas y en la casa, 1978 en un reportaje de 2017; la ficha escribe las dos. La prensa económica de 2012 medía la caída: quince mil puros al día a finales de los años noventa, mil quinientos en 2012, más cuatrocientos mil cigarritos al mes; cuatrocientos empleados antaño, ciento cincuenta tres años antes, setenta entonces, más del 90 % mujeres — y aún la mayor fábrica del país. En 2026 su vicepresidente José Henrique Barreto forma parte de la Apcab, la asociación que lleva la denominación de origen de los puros del Recôncavo.') WHERE `name` = 'Menendez Amerino' AND `history_es` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_de` = CONCAT(`history_de`, '\n\n', 'Zwei Daten für eine Gründung: 1977 in diesem Atlas und beim Haus, 1978 in einer Reportage von 2017; der Eintrag schreibt beide. Die Wirtschaftspresse von 2012 maß den Fall: fünfzehntausend Zigarren am Tag Ende der 1990er Jahre, fünfzehnhundert 2012, dazu vierhunderttausend Zigarillos im Monat; einst vierhundert Beschäftigte, hundertfünfzig drei Jahre zuvor, damals siebzig, zu über 90 % Frauen — und noch immer die größte Fabrik des Landes. 2026 sitzt ihr Vizepräsident José Henrique Barreto in der Apcab, dem Verband, der die Ursprungsbezeichnung der Zigarren des Recôncavo trägt.') WHERE `name` = 'Menendez Amerino' AND `history_de` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_zh` = CONCAT(`history_zh`, '\n\n', '一个创立年份，两个说法：本图集和公司写1977年，2017年一篇报道写1978年；词条两者都写。2012年的经济媒体量出了下滑：1990年代末每天一万五千支，2012年一千五百支，另有每月四十万支小雪茄；从前四百名员工，三年前一百五十人，当时七十人，九成以上是女性——仍是全国规模第一位的工厂。2026年，副总裁若泽·恩里克·巴雷托任职于 Apcab，即推动雷孔卡沃雪茄原产地命名的协会。') WHERE `name` = 'Menendez Amerino' AND `history_zh` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_ar` = CONCAT(`history_ar`, '\n\n', 'تاريخان لتأسيس واحد: 1977 في هذا الأطلس وعند الدار، و1978 في تحقيق سنة 2017؛ تكتب البطاقة الاثنين. قاست الصحافة الاقتصادية سنة 2012 الهبوط: خمسة عشر ألف سيجار في اليوم أواخر التسعينيات، وألف وخمسمئة سنة 2012، مع أربعمئة ألف سيجار صغير في الشهر؛ أربعمئة موظّف يومًا ما، ومئة وخمسون قبل ثلاث سنوات، وسبعون حينها، أكثر من 90 % منهم نساء — وما زالت كبرى مصانع البلاد. وسنة 2026 يجلس نائب رئيسها خوسيه إنريكي باريتو في Apcab، الجمعية التي تحمل تسمية منشأ سيجار ريكونكافو.') WHERE `name` = 'Menendez Amerino' AND `history_ar` NOT LIKE '%Apcab%';
UPDATE `brands` SET `source` = CONCAT(`source`, ' ; correiobraziliense.com.br « Muito além de Cuba » (10 février 2017 : fondée en 1978 — divergence avec 1977, écrite ; marques Dona Flor, Aquarius, Alonso Menendez, Gabriela) ; abras.com.br reprenant Valor Econômico (28 août 2012 : 1 500 cigares par jour contre 15 000 à la fin des années 1990 ; 400 000 cigarillos par mois ; 70 employés, plus de 90 % de femmes ; 150 trois ans plus tôt, 400 autrefois) ; www.fortenoreconcavo.com.br (23 juillet 2026 : José Henrique Barreto, vice-président de l''Apcab)') WHERE `name` = 'Menendez Amerino' AND `source` NOT LIKE '%fortenoreconcavo%';

-- ── Dannemann : paragraphe ajoute, six langues (marqueur Apcab) ──
UPDATE `brands` SET `history` = CONCAT(`history`, '\n\n', 'La presse économique de 2012 comptait vingt personnes au Centro Dannemann de São Félix, à la fois fabrique et centre culturel tourné vers les visiteurs, et notait que le premier revenu du groupe suisse à Bahia venait de Danco, son usine de traitement de feuilles, non des cigares. Un reportage de 2017 date le bâtiment du Centro de 1892 — la maison, elle, de 1873. En 2026, l''Apcab, l''association des producteurs artisanaux, compte quatre fabricants pour l''essentiel du segment ; la fiche ne sait pas si Dannemann en est.') WHERE `name` = 'Dannemann' AND `history` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_en` = CONCAT(`history_en`, '\n\n', 'The business press of 2012 counted twenty people at the Centro Dannemann in São Félix, both factory and cultural centre turned toward visitors, and noted that the Swiss group''s first income in Bahia came from Danco, its leaf-processing plant, not from cigars. A 2017 report dates the Centro''s building to 1892 — the house itself to 1873. In 2026 Apcab, the artisanal producers'' association, counts four manufacturers for the bulk of the segment; the entry does not know whether Dannemann is one of them.') WHERE `name` = 'Dannemann' AND `history_en` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_es` = CONCAT(`history_es`, '\n\n', 'La prensa económica de 2012 contaba veinte personas en el Centro Dannemann de São Félix, a la vez fábrica y centro cultural vuelto hacia los visitantes, y anotaba que el primer ingreso del grupo suizo en Bahía venía de Danco, su planta de procesado de hojas, no de los puros. Un reportaje de 2017 fecha el edificio del Centro en 1892 — la casa, en 1873. En 2026 la Apcab, la asociación de productores artesanales, cuenta cuatro fabricantes para lo esencial del segmento; la ficha no sabe si Dannemann es uno de ellos.') WHERE `name` = 'Dannemann' AND `history_es` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_de` = CONCAT(`history_de`, '\n\n', 'Die Wirtschaftspresse von 2012 zählte zwanzig Menschen im Centro Dannemann in São Félix, zugleich Fabrik und den Besuchern zugewandtes Kulturzentrum, und vermerkte, dass die ersten Einnahmen der Schweizer Gruppe in Bahia von Danco kamen, ihrem Blattverarbeitungswerk, nicht von Zigarren. Eine Reportage von 2017 datiert das Gebäude des Centro auf 1892 — das Haus selbst auf 1873. 2026 zählt die Apcab, der Verband der handwerklichen Hersteller, vier Fabrikanten für den Großteil des Segments; der Eintrag weiß nicht, ob Dannemann dazugehört.') WHERE `name` = 'Dannemann' AND `history_de` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_zh` = CONCAT(`history_zh`, '\n\n', '2012年的经济媒体数到圣费利克斯的 Centro Dannemann 有二十人，既是工厂也是面向访客的文化中心，并指出瑞士集团在巴伊亚的第一大收入来自其烟叶加工厂 Danco，而非雪茄。2017年一篇报道把 Centro 的建筑定在1892年——公司本身则是1873年。2026年，手工生产者协会 Apcab 认定四家制造商占该领域主要份额；词条不知道 Dannemann 是否在其中。') WHERE `name` = 'Dannemann' AND `history_zh` NOT LIKE '%Apcab%';
UPDATE `brands` SET `history_ar` = CONCAT(`history_ar`, '\n\n', 'عدّت الصحافة الاقتصادية سنة 2012 عشرين شخصًا في Centro Dannemann في ساو فيليكس، وهو مصنع ومركز ثقافي موجّه للزوّار في آن، ولاحظت أنّ الدخل الأوّل للمجموعة السويسرية في باهيا يأتي من Danco، معملها لمعالجة الأوراق، لا من السيجار. ويؤرّخ تحقيق سنة 2017 مبنى المركز بسنة 1892 — أمّا الدار فبسنة 1873. وسنة 2026 تعدّ Apcab، جمعية المنتجين الحرفيين، أربعة صانعين لمعظم القطاع؛ ولا تعرف البطاقة إن كانت Dannemann منهم.') WHERE `name` = 'Dannemann' AND `history_ar` NOT LIKE '%Apcab%';
UPDATE `brands` SET `source` = CONCAT(`source`, ' ; abras.com.br reprenant Valor Econômico (28 août 2012 : 20 personnes au Centro Dannemann ; le premier revenu du groupe à Bahia vient de Danco, traitement de feuilles) ; correiobraziliense.com.br « Muito além de Cuba » (10 février 2017 : Centro Dannemann, São Félix, bâtiment de 1892, rouleuses) ; www.fortenoreconcavo.com.br (23 juillet 2026 : quatre fabricants pour 85 % du segment artisanal, selon l''Apcab)') WHERE `name` = 'Dannemann' AND `source` NOT LIKE '%fortenoreconcavo%';

-- ── Jose L. Piedra : le founded que le gabarit rendait illisible (226) ──
UPDATE `brands` SET `founded` = 'années 1880 (famille) ; marque à la 2e génération' WHERE `name` = 'José L. Piedra';

-- ── BRESIL : `brands`, `regions`, `tabacaleras` reecrits en litteral complet ; notes completees ──
UPDATE `producer_countries` SET `brands` = '[{"desc":"Marque brésilienne iconique depuis 1873","name":"Dannemann","iconic":true},{"cape":true,"desc":"Utilise le wrapper Mata Fina","name":"Arturo Fuente Maduro","iconic":false},{"desc":"La mémoire cigarière de Bahia","name":"Suerdieck","iconic":true},{"desc":"Roulage cubain, feuille brésilienne","name":"Dona Flor","iconic":true},{"name":"Menendez Amerino","desc":"La fabrique de Dona Flor, à São Gonçalo dos Campos","iconic":true},{"name":"Leite & Alves","desc":"Cachoeira, depuis 1936 — Talvis, Le Cigar ; un musée du tabac dans la fabrique","iconic":false},{"name":"Monte Pascoal","desc":"Cruz das Almas, 2007 — Tabacos Mata Fina, Lorenzo Orsi ; cent pour cent brésilien","iconic":false},{"name":"JAMM Cigar","desc":"Alagoinhas, 2020 — 4 500 cigares par jour en 2024, dont 2 500 en tripe longue","iconic":false},{"name":"Chaba","desc":"Alagoinhas, 1998 — l''héritière de marques Suerdieck ; état non vérifié depuis 2012","iconic":false}]', `regions` = '["São Gonçalo","Arapiraca","Cruz das Almas","Cachoeira et São Félix","Alagoinhas"]', `tabacaleras` = '["Dannemann (São Félix)","Menendez Amerino (São Gonçalo dos Campos)","Leite & Alves (Cachoeira)","Tabacos Mata Fina (Cruz das Almas)","JAMM Cigar (Alagoinhas)","Chaba (Alagoinhas)","Suerdieck (fermée en 2000)"]' WHERE `id` = 'brazil';
UPDATE `producer_countries` SET `notes` = CONCAT(`notes`, '\n\n', 'Le cinquième recensement (septembre 2026) a relu Bahia dans la presse en portugais : le Recôncavo compte une dizaine de fabriques — Cruz das Almas, Cachoeira, São Félix, São Gonçalo dos Campos, Governador Mangabeira, Muritiba — et Alagoinhas deux, plus au nord ; quatre fabricants font environ 85 % du segment artisanal, dit l''Apcab, qui portait en 2026 à l''INPI une dénomination d''origine pour le tabac Mata Fina et les cigares artisanaux du Recôncavo. L''atlas n''a trouvé aucun atelier de roulage main hors de Bahia — ni dans le Sud, ni à São Paulo — et le dit.') WHERE `id` = 'brazil' AND `notes` NOT LIKE '%Apcab%';
UPDATE `producer_countries` SET `notes_en` = CONCAT(`notes_en`, '\n\n', 'The fifth census (September 2026) reread Bahia in the Portuguese-language press: the Recôncavo counts some ten factories — Cruz das Almas, Cachoeira, São Félix, São Gonçalo dos Campos, Governador Mangabeira, Muritiba — and Alagoinhas two, further north; four manufacturers make about 85% of the artisanal segment, says Apcab, which in 2026 was bringing to the INPI a designation of origin for Mata Fina tobacco and the Recôncavo''s artisanal cigars. This atlas found no hand-rolling workshop outside Bahia — neither in the South nor in São Paulo — and says so.') WHERE `id` = 'brazil' AND `notes_en` NOT LIKE '%Apcab%';
UPDATE `producer_countries` SET `notes_es` = CONCAT(`notes_es`, '\n\n', 'El quinto censo (septiembre de 2026) releyó Bahía en la prensa en portugués: el Recôncavo cuenta una decena de fábricas — Cruz das Almas, Cachoeira, São Félix, São Gonçalo dos Campos, Governador Mangabeira, Muritiba — y Alagoinhas dos, más al norte; cuatro fabricantes hacen cerca del 85 % del segmento artesanal, dice la Apcab, que llevaba en 2026 al INPI una denominación de origen para el tabaco Mata Fina y los puros artesanales del Recôncavo. Este atlas no encontró ningún taller de liado a mano fuera de Bahía — ni en el Sur, ni en São Paulo — y lo dice.') WHERE `id` = 'brazil' AND `notes_es` NOT LIKE '%Apcab%';
UPDATE `producer_countries` SET `notes_de` = CONCAT(`notes_de`, '\n\n', 'Der fünfte Zensus (September 2026) las Bahia in der portugiesischsprachigen Presse neu: Der Recôncavo zählt etwa zehn Fabriken — Cruz das Almas, Cachoeira, São Félix, São Gonçalo dos Campos, Governador Mangabeira, Muritiba — und Alagoinhas zwei, weiter nördlich; vier Hersteller machen etwa 85 % des handwerklichen Segments aus, sagt die Apcab, die 2026 beim INPI eine Ursprungsbezeichnung für den Mata-Fina-Tabak und die handwerklichen Zigarren des Recôncavo einreichte. Dieser Atlas fand keine Handroll-Werkstatt außerhalb Bahias — weder im Süden noch in São Paulo — und sagt es.') WHERE `id` = 'brazil' AND `notes_de` NOT LIKE '%Apcab%';
UPDATE `producer_countries` SET `notes_zh` = CONCAT(`notes_zh`, '\n\n', '第五次普查（2026年9月）用葡萄牙语媒体重读了巴伊亚：雷孔卡沃有十来家工厂——克鲁斯-达斯阿尔马斯、卡舒埃拉、圣费利克斯、圣贡萨洛-杜斯坎普斯、戈韦纳多尔曼加贝拉、穆里蒂巴——更北的阿拉戈伊尼亚斯有两家；Apcab 称四家制造商占手工雪茄约85%，该协会2026年正向 INPI 提交 Mata Fina 烟草与雷孔卡沃手工雪茄的原产地命名。本图集在巴伊亚之外没有找到任何手工卷制作坊——南部和圣保罗都没有——并如实说明。') WHERE `id` = 'brazil' AND `notes_zh` NOT LIKE '%Apcab%';
UPDATE `producer_countries` SET `notes_ar` = CONCAT(`notes_ar`, '\n\n', 'أعاد الإحصاء الخامس (سبتمبر 2026) قراءة باهيا في الصحافة البرتغالية: يعدّ ريكونكافو نحو عشرة مصانع — كروز داس ألماس وكاشويرا وساو فيليكس وساو غونسالو دوس كامبوس وغوفيرنادور مانغابيرا وموريتيبا — وألاغوينياس مصنعين أبعد شمالًا؛ ويصنع أربعة صانعين نحو 85 % من القطاع الحرفي، كما تقول Apcab التي كانت تحمل سنة 2026 إلى معهد INPI تسمية منشأ لتبغ ماتا فينا وسيجار ريكونكافو الحرفي. ولم يجد هذا الأطلس أيّ ورشة لفّ يدوي خارج باهيا — لا في الجنوب ولا في ساو باولو — ويقول ذلك.') WHERE `id` = 'brazil' AND `notes_ar` NOT LIKE '%Apcab%';

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'production_zones', z.`id`, 'note', l.lang, SHA1(z.`note`), 'machine', NOW()
  FROM `production_zones` z
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE z.`id` IN (53, 54)
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'brands', b.`name`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'history' THEN b.`history` ELSE b.`gamme` END), 'machine', NOW()
  FROM `brands` b
  JOIN (SELECT 'history' champ UNION ALL SELECT 'gamme') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE b.`name` IN ('Leite & Alves','Monte Pascoal','JAMM Cigar','Chaba','Menendez Amerino','Dannemann')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'producer_countries', p.`id`, 'notes', l.lang, SHA1(p.`notes`), 'machine', NOW()
  FROM `producer_countries` p
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE p.`id` = 'brazil'
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 227';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 227','systeme','quatre_maisons_de_bahia','marque',0,
   'Leite & Alves (Cachoeira, 1936), Monte Pascoal (Tabacos Mata Fina, Cruz das Almas, 2007), JAMM Cigar (Alagoinhas, 2020), Chaba (Alagoinhas, 1998) : le Bresil relu dans la presse en portugais. Deux zones : Cachoeira et Sao Felix, Alagoinhas'),
  (NULL,'migration 227','systeme','etat_dit_pour_chaba','marque',0,
   'Chaba : aucune presse depuis 2012, registre actif en 2026 — la fiche ecrit au passe ce qui doit l etre et ne pretend pas savoir si l on y roule encore (regle Ortega)'),
  (NULL,'migration 227','systeme','rien_hors_de_bahia','pays',0,
   'Le recensement n a trouve aucun atelier de roulage main hors de Bahia — ni dans le Sud ni a Sao Paulo — et les notes du pays le disent. Non ecrites : San Francisco Charutos (une source, 2012), Josefina, Angelina, Julien Bahia, Paraguacu (des noms)');

SELECT
  (SELECT COUNT(*) FROM `brands` WHERE `name` IN ('Leite & Alves', 'Monte Pascoal', 'JAMM Cigar', 'Chaba')) = 4 AS quatre_fiches,
  (SELECT COUNT(*) FROM `production_zones` WHERE `id` IN (53, 54)) = 2 AS deux_zones,
  (SELECT SUM(`history` LIKE '%Apcab%' AND `history_ar` LIKE '%Apcab%') FROM `brands` WHERE `name` IN ('Menendez Amerino', 'Dannemann')) = 2 AS deux_completees,
  (SELECT `notes_zh` LIKE '%Apcab%' FROM `producer_countries` WHERE `id` = 'brazil') AS notes_pays,
  (SELECT JSON_LENGTH(`brands`) FROM `producer_countries` WHERE `id` = 'brazil') = 9 AS bresil_neuf,
  (SELECT `founded` FROM `brands` WHERE `name` = 'José L. Piedra') LIKE 'années 1880%' AS piedra_lisible;
SELECT COUNT(*) AS marques, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `brands`;
