-- ════════════════════════════════════════════════════════
-- 228 — Lot 15 du cinquieme recensement : cinq vitrines relues
-- ────────────────────────────────────────────────────────
-- EQUATEUR, COSTA RICA, PANAMA, PHILIPPINES, MEXIQUE, relus dans la
-- presse en espagnol et dans la presse asiatique du tabac. TROIS
-- MAISONS ENTRENT :
--   IGM Cigars              San Jose (Costa Rica), 1997 selon la maison —
--                           la fabrique boutique qui roule Casdagli
--   Tabacalera R. Paxtian   Sihuapan, San Andres Tuxtla, 1990 — quatre
--                           generations de planteurs depuis 1910
--   Chazaro                 Ezequiel Montes, Queretaro, 2015 ou 2016 —
--                           premiere maison mexicaine hors de Veracruz
-- UNE ZONE : Ezequiel Montes (55) — lieu de roulage, pas de champs.
--
-- CE QUE LE RECENSEMENT N'A PAS ECRIT, ET POURQUOI, dans les notes de
-- chaque pays : les trois ateliers de Guayaquil (une source chacun),
-- Tabacos de la Cordillera (domaine mort), Don Chicho (une mention),
-- et rien aux Philippines au-dela des quatre fiches. Tabaqueria de
-- Filipinas recoit les chiffres de 2016 ; Joyas de Panama sa gamme
-- (Flor de Panama) et le reportage de 2025 ; les fabriques fermees du
-- Panama sont marquees fermees. Les `tabacaleras` de trois pays sont
-- reecrits — le Costa Rica disait « un seul acteur » avec dix fiches.
--
-- Ajouts gardes par des marqueurs : « recensement de 2026 » et ses
-- traductions pour les notes, « tobaccoasia » et « dopanama » pour les
-- sources, JSON_LENGTH pour la gamme.
-- ════════════════════════════════════════════════════════

-- ── ZONE ──
INSERT INTO `production_zones` (`id`, `country_id`, `name`, `lat`, `lon`, `color`, `note`, `note_en`, `note_es`, `note_de`, `note_zh`, `note_ar`)
VALUES (55, 'mexico', 'Ezequiel Montes (Querétaro)', 20.665, -99.893, '#7A4B2A', 'Un lieu de roulage, pas de champs : la Real Fábrica de Tabacos de la famille Cházaro, sur la route du vin et du fromage, roule le tabac noir de San Andrés Tuxtla avec des artisans venus de Veracruz', 'A rolling place, not fields: the Cházaro family''s Real Fábrica de Tabacos, on the wine and cheese road, rolls San Andrés Tuxtla''s black tobacco with artisans come from Veracruz', 'Un lugar de liado, no de campos: la Real Fábrica de Tabacos de la familia Cházaro, en la ruta del vino y el queso, lía el tabaco negro de San Andrés Tuxtla con artesanos venidos de Veracruz', 'Ein Rollort, keine Felder: die Real Fábrica de Tabacos der Familie Cházaro an der Wein- und Käsestraße rollt den schwarzen Tabak von San Andrés Tuxtla mit aus Veracruz gekommenen Handwerkern', '卷制之地而非田地：查萨罗家族的 Real Fábrica de Tabacos，位于葡萄酒与奶酪之路上，由来自韦拉克鲁斯的匠人卷制圣安德烈斯-图斯特拉的黑烟叶', 'مكان لفّ لا حقول: Real Fábrica de Tabacos لعائلة تشاسارو، على طريق النبيذ والجبن، تلفّ تبغ سان أندريس توكستلا الأسود بحرفيين قادمين من فيراكروز')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `name` = VALUES(`name`), `lat` = VALUES(`lat`), `lon` = VALUES(`lon`), `color` = VALUES(`color`), `note` = VALUES(`note`), `note_en` = VALUES(`note_en`), `note_es` = VALUES(`note_es`), `note_de` = VALUES(`note_de`), `note_zh` = VALUES(`note_zh`), `note_ar` = VALUES(`note_ar`);

-- ── IGM Cigars ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('IGM Cigars',
        'costarica',
        '1997 (maison) — San José ; les González Ferrer',
        'Fabrique propre à San José ; ferme à Santa Marta de Puriscal, à plus de 900 m ; roule aussi pour Casdagli depuis 2013 (Daughters of the Wind, Cypher 3311)',
        'igmcigars.com « Historia » (Inversiones González Martínez S.A. ; fondée en 1997 ; la famille Ferrer, héritière du tabac cubain du milieu du XXe siècle ; fabrique à San José, ferme à Puriscal ; tabacs de République dominicaine, du Nicaragua, du Pérou et d''Équateur ; Tobacco Tour) ; casdaglicigars.com « IGM Boutique Factory » (fabrique boutique de San José ; ferme à Santa Marta de Puriscal à plus de 3 000 pieds ; José González Ferrer, ingénieur agronome cubain ; roule pour le marché saoudien de Casdagli depuis 2013, Daughters of the Wind en 2018, Cypher 3311 en 2022 ; tripe dominicaine et péruvienne, sous-cape et cape costariciennes) ; neptunecigar.com et smallbatchcigar.com (détaillants) — aucune presse indépendante : ce sont la maison et sa cliente qui parlent',
        'IGM — Inversiones González Martínez — est une petite fabrique de San José qui se présente comme boutique : des formats et des mélanges qu''on ne trouve pas ailleurs, faits à la main, et souvent sur mesure pour le client qui choisit son assemblage. La maison se dit fondée en 1997 par une famille aux racines cubaines, les González Ferrer, dont l''un, José González Ferrer, est ingénieur agronome formé à Cuba ; elle cultive à Santa Marta de Puriscal, dans les montagnes à plus de neuf cents mètres, et achète aussi des feuilles en République dominicaine, au Nicaragua, au Pérou et en Équateur.

C''est par ses clients qu''on la connaît : Casdagli, la maison britannique déjà dans cet atlas, lui confie depuis 2013 ses cigares pour l''Arabie saoudite, puis ses lignes Daughters of the Wind en 2018 et Cypher 3311 en 2022 — tripe dominicaine et péruvienne, sous-cape et cape costariciennes, un rouleur nommé Luis pour les Cremellos. La fabrique ouvre sa ferme aux visiteurs, de la semence au cigare.

Aucun journal indépendant ne l''a décrite ; la fiche tient de la maison et de sa cliente, et le dit. Elle entre parce que l''atlas nommait déjà IGM comme fabrique de Casdagli sans lui donner de fiche — la même logique qu''entre la Tabacalera Palma et l''Aging Room.',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"Costaricienne (Claro) ou importée","vitolas":[],"story":"La marque propre de la fabrique de San José — formats et mélanges boutique, souvent sur mesure."}]',
        'IGM — Inversiones González Martínez — is a small San José factory that presents itself as a boutique: sizes and blends found nowhere else, made by hand, and often to order for the client who chooses the blend. The house says it was founded in 1997 by a family with Cuban roots, the González Ferrers, one of whom, José González Ferrer, is an agricultural engineer trained in Cuba; it grows at Santa Marta de Puriscal, in the mountains above nine hundred metres, and also buys leaf in the Dominican Republic, Nicaragua, Peru and Ecuador.

It is known through its clients: Casdagli, the British house already in this atlas, has entrusted it since 2013 with its cigars for Saudi Arabia, then its Daughters of the Wind line in 2018 and Cypher 3311 in 2022 — Dominican and Peruvian filler, Costa Rican binder and wrapper, a roller named Luis for the Cremellos. The factory opens its farm to visitors, from seed to cigar.

No independent paper has described it; the entry comes from the house and its client, and says so. It enters because the atlas already named IGM as Casdagli''s factory without giving it an entry — the same logic as between Tabacalera Palma and Aging Room.',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"Costa Rican (Claro) or imported","vitolas":[],"story":"The San José factory''s own brand — boutique sizes and blends, often to order."}]',
        'IGM — Inversiones González Martínez — es una pequeña fábrica de San José que se presenta como boutique: formatos y ligadas que no se encuentran en otra parte, hechos a mano, y a menudo a medida para el cliente que elige su mezcla. La casa se dice fundada en 1997 por una familia de raíces cubanas, los González Ferrer, uno de los cuales, José González Ferrer, es ingeniero agrónomo formado en Cuba; cultiva en Santa Marta de Puriscal, en las montañas a más de novecientos metros, y compra también hojas en República Dominicana, Nicaragua, Perú y Ecuador.

Se la conoce por sus clientes: Casdagli, la casa británica ya en este atlas, le confía desde 2013 sus puros para Arabia Saudita, y luego sus líneas Daughters of the Wind en 2018 y Cypher 3311 en 2022 — tripa dominicana y peruana, capote y capa costarricenses, un torcedor llamado Luis para los Cremellos. La fábrica abre su finca a los visitantes, de la semilla al puro.

Ningún diario independiente la ha descrito; la ficha procede de la casa y de su cliente, y lo dice. Entra porque el atlas ya nombraba a IGM como fábrica de Casdagli sin darle ficha — la misma lógica que entre la Tabacalera Palma y Aging Room.',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"Costarricense (Claro) o importada","vitolas":[],"story":"La marca propia de la fábrica de San José — formatos y ligadas boutique, a menudo a medida."}]',
        'IGM — Inversiones González Martínez — ist eine kleine Fabrik in San José, die sich als Boutique versteht: Formate und Mischungen, die es sonst nirgends gibt, von Hand gemacht und oft nach Maß für den Kunden, der seine Mischung wählt. Das Haus nennt sich 1997 von einer Familie mit kubanischen Wurzeln gegründet, den González Ferrers, von denen einer, José González Ferrer, ein in Kuba ausgebildeter Agraringenieur ist; es baut in Santa Marta de Puriscal an, in den Bergen über neunhundert Metern, und kauft auch Blätter in der Dominikanischen Republik, in Nicaragua, Peru und Ecuador.

Bekannt ist es durch seine Kunden: Casdagli, das britische Haus, das schon in diesem Atlas steht, vertraut ihm seit 2013 seine Zigarren für Saudi-Arabien an, dann seine Linie Daughters of the Wind 2018 und Cypher 3311 2022 — dominikanische und peruanische Einlage, costa-ricanisches Um- und Deckblatt, ein Roller namens Luis für die Cremellos. Die Fabrik öffnet ihre Farm den Besuchern, vom Samen bis zur Zigarre.

Keine unabhängige Zeitung hat sie beschrieben; der Eintrag stammt vom Haus und seiner Kundin, und sagt es. Sie tritt ein, weil der Atlas IGM bereits als Fabrik von Casdagli nannte, ohne ihr einen Eintrag zu geben — dieselbe Logik wie zwischen Tabacalera Palma und Aging Room.',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"Costa-ricanisch (Claro) oder importiert","vitolas":[],"story":"Die eigene Marke der Fabrik von San José — Boutique-Formate und -Mischungen, oft nach Maß."}]',
        'IGM——Inversiones González Martínez——是圣何塞一家自称精品店的小工厂：别处没有的规格和配方，手工制作，常常按客户选定的配方定制。公司自称1997年由有古巴根源的冈萨雷斯·费雷尔家族创立，其中的何塞·冈萨雷斯·费雷尔是古巴培养的农艺工程师；工厂在海拔九百多米的圣玛尔塔-德普里斯卡尔山区种植，也从多米尼加、尼加拉瓜、秘鲁和厄瓜多尔购买烟叶。

人们通过它的客户认识它：本图集已收录的英国品牌 Casdagli 自2013年起把沙特市场的雪茄交给它，随后是2018年的 Daughters of the Wind 系列和2022年的 Cypher 3311——多米尼加和秘鲁茄芯，哥斯达黎加茄套和茄衣，一位名叫路易斯的卷工负责 Cremellos。工厂向访客开放农场，从种子到雪茄。

没有独立报刊描述过它；词条来自公司及其客户，并如实说明。它之所以进入图集，是因为图集早已把 IGM 列为 Casdagli 的工厂却没有给它词条——与 Tabacalera Palma 和 Aging Room 之间的逻辑相同。',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"哥斯达黎加（Claro）或进口","vitolas":[],"story":"圣何塞工厂的自有品牌——精品规格与配方，常按需定制。"}]',
        'IGM — Inversiones González Martínez — مصنع صغير في سان خوسيه يقدّم نفسه بوصفه بوتيك: قياسات وخلطات لا تُوجد في مكان آخر، تُصنع يدويًّا وغالبًا حسب الطلب للزبون الذي يختار خلطته. تقول الدار إنّها تأسّست سنة 1997 على يد عائلة ذات جذور كوبية، آل غونساليس فيرير، ومنهم خوسيه غونساليس فيرير، مهندس زراعي تدرّب في كوبا؛ وتزرع في سانتا مارتا دي بوريسكال، في الجبال فوق تسعمئة متر، وتشتري أيضًا الأوراق من جمهورية الدومينيكان ونيكاراغوا وبيرو والإكوادور.

تُعرف بزبائنها: فـCasdagli، الدار البريطانية الموجودة في هذا الأطلس، تعهد إليها منذ 2013 بسيجارها للسعودية، ثمّ بخطّها Daughters of the Wind سنة 2018 وCypher 3311 سنة 2022 — حشوة دومينيكية وبيروفية، ورابط وغلاف كوستاريكيان، ولفّاف اسمه لويس لصنف Cremellos. ويفتح المصنع مزرعته للزوّار، من البذرة إلى السيجار.

لم تصفها أيّ صحيفة مستقلّة؛ البطاقة من الدار وزبونتها، وتقول ذلك. وتدخل لأنّ الأطلس كان يسمّي IGM مصنعَ Casdagli من دون أن يعطيها بطاقة — المنطق نفسه بين Tabacalera Palma وAging Room.',
        '[{"name":"IGM","color":"#4A6741","force":"Medium","wrapper":"كوستاريكية (كلارو) أو مستوردة","vitolas":[],"story":"العلامة الخاصّة لمصنع سان خوسيه — قياسات وخلطات بوتيك، غالبًا حسب الطلب."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Tabacalera R. Paxtián ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Tabacalera R. Paxtián',
        'mexico',
        '1990 — Sihuapan (San Andrés) ; planteurs dès 1910',
        'Fabrique et champs propres à Sihuapan (San Andrés Tuxtla, Veracruz) ; famille Rodríguez Paxtián, quatre générations ; jusqu''à 300 hectares coordonnés par la deuxième',
        'humolatino.com « Tabacalera R. Paxtián, un siglo de tabaco » (14 novembre 2023 : Don Juan Rodríguez López commence en 1910 sur des terres louées à Sihuapan, jusqu''à 7 hectares, meurt à 102 ans ; son fils Víctor, plus de 83 ans, jusqu''à 300 hectares et deux tonnes par hectare ; Francisco « Paco », ingénieur industriel en 1994, dessine les marques ; société fondée en 1990 avec des terres propres, cigares premium depuis 1994 ; quatrième génération arrivée ; marques Privilegios, Del Paraíso, R. Paxtián, TabaRicos) ; rpaxtian.com et shop.rpaxtian.com « Sobre nosotros » (un siècle de tradition ; Los Puros del Paraíso créés en 1994 ; puros faits à Sihuapan) ; diexmexico.com (Tabacalera R. Paxtián S.P.R. de R.L.) — sources en espagnol',
        'La Tabacalera R. Paxtián est une maison de planteurs avant d''être une maison de cigares. Don Juan Rodríguez López, de Sihuapan, dans la vallée de San Andrés Tuxtla, est entré dans les champs de tabac à quatorze ans, s''est marié à quinze, a cultivé jusqu''à sept hectares sur des terres louées à partir de 1910, roulait pour lui-même des jolochitos, et a travaillé jusqu''à quatre-vingt-seize ans avant de mourir à cent deux ; il n''a pas laissé d''entreprise, dit la presse du cigare mexicaine, mais un savoir. Son fils Víctor, entré aux champs au même âge, a fini par coordonner jusqu''à trois cents hectares, à deux tonnes l''hectare, et se lève encore avant l''aube passé quatre-vingt-trois ans.

La société, elle, date de 1990 : Víctor, son fils Francisco — Paco, ingénieur industriel diplômé en 1994, qui a dessiné toutes les marques — et un frère, sur des terres cette fois à eux. Les cigares premium commencent en 1994, avec Los Puros del Paraíso ; suivent Privilegios, R. Paxtián et les petits formats TabaRicos, tous roulés à la main à Sihuapan, sur le Negro San Andrés que la maison tient pour la meilleure cape mûre qui soit — c''est elle qui le dit. Une quatrième génération, les petits-enfants, est arrivée dans les cinq dernières années.

C''est la fabrique de San Andrés que l''atlas n''avait pas : à côté des Turrent et de Santa Clara, une famille de la vallée qui a mis un siècle à signer ses feuilles de son nom.',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"La première marque, 1994 — Elemental, Especial, Premium, Mexike, et une Fusión México-Nicaragua."},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Especial, Premium, Selecta — le haut de la maison."},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Premium et Secrets, au nom de la famille."}]',
        'Tabacalera R. Paxtián is a house of growers before it is a house of cigars. Don Juan Rodríguez López, of Sihuapan, in the San Andrés Tuxtla valley, entered the tobacco fields at fourteen, married at fifteen, grew up to seven hectares on rented land from 1910, rolled jolochitos for himself, and worked until ninety-six before dying at a hundred and two; he left no company, says the Mexican cigar press, but a knowledge. His son Víctor, in the fields at the same age, came to coordinate up to three hundred hectares, at two tonnes a hectare, and still rises before dawn past eighty-three.

The company itself dates from 1990: Víctor, his son Francisco — Paco, an industrial engineer who graduated in 1994 and drew all the brands — and a brother, on land this time their own. Premium cigars begin in 1994, with Los Puros del Paraíso; Privilegios, R. Paxtián and the small TabaRicos follow, all hand-rolled at Sihuapan, on the Negro San Andrés that the house holds to be the finest mature wrapper there is — that is the house speaking. A fourth generation, the grandchildren, arrived in the last five years.

It is the San Andrés factory this atlas lacked: next to the Turrents and Santa Clara, a family of the valley that took a century to sign its leaves with its name.',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"The first brand, 1994 — Elemental, Especial, Premium, Mexike, and a Mexico-Nicaragua Fusión."},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Especial, Premium, Selecta — the house''s top."},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Premium and Secrets, in the family''s name."}]',
        'La Tabacalera R. Paxtián es una casa de sembradores antes que una casa de puros. Don Juan Rodríguez López, de Sihuapan, en el valle de San Andrés Tuxtla, entró en los campos de tabaco a los catorce años, se casó a los quince, cultivó hasta siete hectáreas en tierras rentadas desde 1910, liaba jolochitos para él mismo, y trabajó hasta los noventa y seis antes de morir a los ciento dos; no dejó empresa, dice la prensa mexicana del puro, sino un saber. Su hijo Víctor, en los campos a la misma edad, llegó a coordinar hasta trescientas hectáreas, a dos toneladas por hectárea, y aún se levanta antes del alba pasados los ochenta y tres.

La sociedad, ella, data de 1990: Víctor, su hijo Francisco — Paco, ingeniero industrial titulado en 1994, que diseñó todas las marcas — y un hermano, en tierras esta vez propias. Los puros premium empiezan en 1994, con Los Puros del Paraíso; siguen Privilegios, R. Paxtián y los formatos pequeños TabaRicos, todos liados a mano en Sihuapan, sobre el Negro San Andrés que la casa tiene por la mejor capa madura que exista — es ella quien lo dice. Una cuarta generación, los nietos, llegó en los últimos cinco años.

Es la fábrica de San Andrés que el atlas no tenía: junto a los Turrent y a Santa Clara, una familia del valle que tardó un siglo en firmar sus hojas con su nombre.',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"La primera marca, 1994 — Elemental, Especial, Premium, Mexike, y una Fusión México-Nicaragua."},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Especial, Premium, Selecta — lo alto de la casa."},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Premium y Secrets, con el nombre de la familia."}]',
        'Die Tabacalera R. Paxtián ist ein Haus von Pflanzern, bevor sie ein Haus von Zigarren ist. Don Juan Rodríguez López aus Sihuapan im Tal von San Andrés Tuxtla ging mit vierzehn auf die Tabakfelder, heiratete mit fünfzehn, baute ab 1910 bis zu sieben Hektar auf gepachtetem Land an, rollte sich selbst Jolochitos und arbeitete bis sechsundneunzig, bevor er mit hundertzwei starb; er hinterließ kein Unternehmen, sagt die mexikanische Zigarrenpresse, sondern ein Wissen. Sein Sohn Víctor, im selben Alter auf den Feldern, kam dazu, bis zu dreihundert Hektar zu koordinieren, zu zwei Tonnen je Hektar, und steht mit über dreiundachtzig noch vor der Dämmerung auf.

Die Gesellschaft selbst stammt von 1990: Víctor, sein Sohn Francisco — Paco, Wirtschaftsingenieur mit Abschluss 1994, der alle Marken entwarf — und ein Bruder, auf diesmal eigenem Land. Die Premiumzigarren beginnen 1994 mit Los Puros del Paraíso; Privilegios, R. Paxtián und die kleinen TabaRicos folgen, alle in Sihuapan von Hand gerollt, auf dem Negro San Andrés, den das Haus für das feinste reife Deckblatt überhaupt hält — das sagt das Haus. Eine vierte Generation, die Enkel, kam in den letzten fünf Jahren dazu.

Es ist die Fabrik von San Andrés, die diesem Atlas fehlte: neben den Turrents und Santa Clara eine Familie des Tals, die ein Jahrhundert brauchte, um ihre Blätter mit ihrem Namen zu zeichnen.',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Die erste Marke, 1994 — Elemental, Especial, Premium, Mexike und eine Fusión México-Nicaragua."},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Especial, Premium, Selecta — die Spitze des Hauses."},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Premium und Secrets, im Namen der Familie."}]',
        'Tabacalera R. Paxtián 首先是种植者之家，然后才是雪茄之家。圣安德烈斯-图斯特拉河谷西瓦潘的堂胡安·罗德里格斯·洛佩斯十四岁下烟田，十五岁成婚，自1910年起在租来的地上种到七公顷，为自己卷 jolochitos，工作到九十六岁，一百零二岁去世；墨西哥雪茄媒体说，他没有留下企业，留下的是手艺。儿子维克多同龄下田，后来统筹多达三百公顷，每公顷两吨，八十三岁过后仍在黎明前起身。

公司本身始于1990年：维克多、他的儿子弗朗西斯科——帕科，1994年毕业的工业工程师，设计了全部品牌——和一位兄弟，这次是在自家的地上。高档雪茄始于1994年的 Los Puros del Paraíso；随后是 Privilegios、R. Paxtián 和小规格的 TabaRicos，全部在西瓦潘手工卷制，用的是公司视为世上上佳成熟茄衣的 Negro San Andrés——这是公司自己的说法。第四代——孙辈——在过去五年里加入。

这是本图集缺少的那家圣安德烈斯工厂：在图伦特家族和 Santa Clara 之外，一个用了一个世纪才把自己的名字签在烟叶上的河谷家族。',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"Negro San Andrés（韦拉克鲁斯）","vitolas":[],"story":"首个品牌，1994年——五个系列，含一款墨西哥-尼加拉瓜混配。"},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"Negro San Andrés（韦拉克鲁斯）","vitolas":[],"story":"三个系列——公司的高端。"},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"Negro San Andrés（韦拉克鲁斯）","vitolas":[],"story":"以家族命名的两个系列。"}]',
        'Tabacalera R. Paxtián دار مزارعين قبل أن تكون دار سيجار. دخل دون خوان رودريغيس لوبيس، من سيواپان في وادي سان أندريس توكستلا، حقول التبغ في الرابعة عشرة، وتزوّج في الخامسة عشرة، وزرع حتّى سبعة هكتارات على أرض مستأجرة منذ 1910، وكان يلفّ لنفسه سجائر خولوتشيتو، وعمل حتّى السادسة والتسعين قبل أن يموت في الثانية بعد المئة؛ لم يترك شركة، تقول صحافة السيجار المكسيكية، بل معرفة. وابنه فيكتور، في الحقول في السنّ نفسها، صار ينسّق حتّى ثلاثمئة هكتار، بطنّين للهكتار، وما زال ينهض قبل الفجر بعد الثالثة والثمانين.

أمّا الشركة فمن سنة 1990: فيكتور وابنه فرانسيسكو — باكو، المهندس الصناعي المتخرّج سنة 1994 الذي رسم كلّ العلامات — وأخ، على أرض هذه المرّة لهم. يبدأ السيجار الفاخر سنة 1994 بـLos Puros del Paraíso؛ ثمّ Privilegios وR. Paxtián والقياسات الصغيرة TabaRicos، كلّها ملفوفة يدويًّا في سيواپان على تبغ نيغرو سان أندريس الذي تعدّه الدار أجود غلاف ناضج — والدار هي القائلة. ووصل جيل رابع، الأحفاد، في السنوات الخمس الأخيرة.

هذا مصنع سان أندريس الذي كان ينقص الأطلس: إلى جانب آل تورينت وSanta Clara، عائلة من الوادي احتاجت قرنًا لتوقّع أوراقها باسمها.',
        '[{"name":"Del Paraíso","color":"#8B1A1A","force":"Medium","wrapper":"نيغرو سان أندريس (فيراكروز)","vitolas":[],"story":"العلامة الأولى، 1994 — Elemental وEspecial وPremium وMexike، وFusión مكسيكية-نيكاراغوية."},{"name":"Privilegios","color":"#5C2E1E","force":"Medium-Full","wrapper":"نيغرو سان أندريس (فيراكروز)","vitolas":[],"story":"Especial وPremium وSelecta — قمّة الدار."},{"name":"R. Paxtián","color":"#6B4226","force":"Medium","wrapper":"نيغرو سان أندريس (فيراكروز)","vitolas":[],"story":"Premium وSecrets، باسم العائلة."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Cházaro ──

INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Cházaro',
        'mexico',
        '2015 ou 2016 — Ezequiel Montes (Querétaro)',
        'Real Fábrica de Tabacos, route 120 km 42, Ezequiel Montes (Querétaro) ; quinze personnes, environ 300 cigares par jour (2022) ; artisans de San Andrés menés par Don Toño',
        'eluniversalqueretaro.mx « Bocanadas artesanales » (20 septembre 2018, mis à jour le 5 juillet 2023 : fondée trois ans plus tôt, ouverte au public en 2017 ; famille Cházaro d''origine veracruzaine ; Ricardo Wolf, ventes ; Don Toño, maître rouleur de San Andrés Tuxtla, quarante ans de métier ; 70 à 90 cigares par rouleur et par jour, 15 000 par mois ; 70 % à l''export vers les États-Unis ; la Real Fábrica de Tabacos de San Fernando de 1779 en référence) ; eluniversal.com.mx « Tour por la Real Fábrica » (11 septembre 2022, mis à jour le 20 mars 2023 : marque en 2016 ; installée à Ezequiel Montes en 2016, route 120 km 42 ; quinze employés, environ 300 cigares par jour ; lignes Black, Habano, Peña Blanca ; Mauricio Cedillo, directeur commercial ; visites du vendredi au dimanche) — divergence entre 15 000 par mois en 2018 et 300 par jour en 2022, écrite ; chazarocigars.com ; asomarte.com ; habanoclub.mx — sources en espagnol',
        'Cházaro est la seule maison de cet atlas qui roule au Mexique hors de Veracruz : à Ezequiel Montes, dans le Querétaro, sur la route du vin et du fromage, une famille d''origine veracruzaine a ouvert vers 2015 une fabrique qu''elle a nommée Real Fábrica de Tabacos, en mémoire de celle de San Fernando, que la Couronne installa à Querétaro en 1779 — la deuxième de Nouvelle-Espagne — et qui ferma dans la première moitié du XIXe siècle. Les deux journaux qui l''ont visitée ne s''accordent pas sur l''année : fondée trois ans avant 2018 pour l''un, marque née en 2016 pour l''autre ; la fiche écrit les deux. Ouverte au public en 2017.

Le tabac vient de San Andrés Tuxtla, et les artisans aussi : Antonio Toto Pucheta, Don Toño, maître rouleur de quarante ans de métier, dirige la production avec des rouleurs venus de la vallée, chacun à soixante-dix ou quatre-vingt-dix cigares par jour. Trois lignes — Black, quatre cinquièmes de tabac clair ; Habano, moitié-moitié ; Peña Blanca, avec eau-de-vie de canne et jus de fruits. Les chiffres divergent selon l''année : quinze mille cigares par mois et sept dixièmes exportés vers les États-Unis en 2018, quinze personnes et environ trois cents cigares par jour en 2022 ; la fiche les écrit tous les deux plutôt que de choisir.

L''atlas ouvre pour elle une zone de roulage, Ezequiel Montes, sans champs : c''est un lieu où l''on roule la feuille d''une autre région, comme Dresde ou Moscou.',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Quatre cinquièmes de tabac clair, un cinquième de sombre — café, rhum, fruits, dit la maison."},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Moitié sombre, moitié clair ; feuilles hydratées au rhum et au miel, dit la maison."}]',
        'Cházaro is the only house in this atlas that rolls in Mexico outside Veracruz: at Ezequiel Montes, in Querétaro, on the wine and cheese road, a family of Veracruz origin opened around 2015 a factory it named Real Fábrica de Tabacos, in memory of the San Fernando one the Crown set up in Querétaro in 1779 — the second in New Spain — which closed in the first half of the nineteenth century. The two papers that visited it do not agree on the year: founded three years before 2018 for one, brand created in 2016 for the other; the entry writes both. Open to the public since 2017.

The tobacco comes from San Andrés Tuxtla, and so do the artisans: Antonio Toto Pucheta, Don Toño, a master roller with forty years in the trade, leads production with rollers from the valley, each at seventy to ninety cigars a day. Three lines — Black, four fifths light tobacco; Habano, half and half; Peña Blanca, with cane brandy and fruit juice. The figures differ by year: fifteen thousand cigars a month and seven tenths exported to the United States in 2018, fifteen people and about three hundred cigars a day in 2022; the entry writes both rather than choosing.

This atlas opens a rolling zone for it, Ezequiel Montes, without fields: a place where another region''s leaf is rolled, like Dresden or Moscow.',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Four fifths light tobacco, one fifth dark — coffee, rum, fruit, says the house."},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Half dark, half light; leaves hydrated with rum and honey, says the house."}]',
        'Cházaro es la única casa de este atlas que lía en México fuera de Veracruz: en Ezequiel Montes, en Querétaro, en la ruta del vino y el queso, una familia de origen veracruzano abrió hacia 2015 una fábrica que llamó Real Fábrica de Tabacos, en memoria de la de San Fernando, que la Corona instaló en Querétaro en 1779 — la segunda de la Nueva España — y que cerró en la primera mitad del siglo XIX. Los dos diarios que la visitaron no concuerdan en el año: fundada tres años antes de 2018 para uno, marca creada en 2016 para el otro; la ficha escribe las dos. Abierta al público en 2017.

El tabaco viene de San Andrés Tuxtla, y los artesanos también: Antonio Toto Pucheta, Don Toño, maestro torcedor con cuarenta años de oficio, dirige la producción con torcedores venidos del valle, cada uno a setenta u noventa puros al día. Tres líneas — Black, cuatro quintos de tabaco claro; Habano, mitad y mitad; Peña Blanca, con aguardiente de caña y jugo de frutas. Las cifras divergen según el año: quince mil puros al mes y siete décimas exportadas a Estados Unidos en 2018, quince personas y unos trescientos puros al día en 2022; la ficha escribe las dos en vez de elegir.

El atlas abre para ella una zona de liado, Ezequiel Montes, sin campos: un lugar donde se lía la hoja de otra región, como Dresde o Moscú.',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Cuatro quintos de tabaco claro, un quinto de oscuro — café, ron, frutas, dice la casa."},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Mitad oscuro, mitad claro; hojas hidratadas con ron y miel, dice la casa."}]',
        'Cházaro ist das einzige Haus dieses Atlas, das in Mexiko außerhalb von Veracruz rollt: In Ezequiel Montes, in Querétaro, an der Wein- und Käsestraße, eröffnete eine Familie veracruzanischer Herkunft um 2015 eine Fabrik, die sie Real Fábrica de Tabacos nannte, in Erinnerung an die von San Fernando, die die Krone 1779 in Querétaro einrichtete — die zweite Neuspaniens — und die in der ersten Hälfte des 19. Jahrhunderts schloss. Die beiden Zeitungen, die sie besuchten, sind sich über das Jahr uneins: gegründet drei Jahre vor 2018 für die eine, Marke geschaffen 2016 für die andere; der Eintrag schreibt beide. Seit 2017 für Besucher geöffnet.

Der Tabak kommt aus San Andrés Tuxtla, und die Handwerker auch: Antonio Toto Pucheta, Don Toño, Meisterroller mit vierzig Jahren im Beruf, leitet die Produktion mit Rollern aus dem Tal, jeder bei siebzig bis neunzig Zigarren am Tag. Drei Linien — Black, vier Fünftel heller Tabak; Habano, halb und halb; Peña Blanca, mit Zuckerrohrbrand und Fruchtsaft. Die Zahlen weichen je nach Jahr ab: fünfzehntausend Zigarren im Monat und sieben Zehntel in die Vereinigten Staaten exportiert 2018, fünfzehn Leute und etwa dreihundert Zigarren am Tag 2022; der Eintrag schreibt beide, statt zu wählen.

Dieser Atlas öffnet für sie eine Rollzone, Ezequiel Montes, ohne Felder: ein Ort, an dem das Blatt einer anderen Region gerollt wird, wie Dresden oder Moskau.',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Vier Fünftel heller Tabak, ein Fünftel dunkler — Kaffee, Rum, Frucht, sagt das Haus."},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"Negro San Andrés (Veracruz)","vitolas":[],"story":"Halb dunkel, halb hell; Blätter mit Rum und Honig befeuchtet, sagt das Haus."}]',
        'Cházaro 是本图集中唯一在韦拉克鲁斯之外的墨西哥地区卷制的公司：在克雷塔罗州的埃塞基耶尔蒙特斯，葡萄酒与奶酪之路上，一个韦拉克鲁斯裔家族在2015年前后开了一家工厂，取名 Real Fábrica de Tabacos，纪念王室1779年设在克雷塔罗的圣费尔南多皇家烟草厂——新西班牙第二大厂，十九世纪上半叶关闭。到访过的两家报纸对年份说法不一：一家说成立于2018年前三年，另一家说品牌创于2016年；词条两者都写。2017年向公众开放。

烟叶来自圣安德烈斯-图斯特拉，匠人也是：安东尼奥·托托·普切塔，人称堂托尼奥，四十年手艺的卷制大师，带领来自河谷的卷工主持生产，每人每天七十到九十支。三条线——Black，五分之四浅色烟叶；Habano，各半；Peña Blanca，加甘蔗烧酒和果汁。数字因年份而异：2018年每月一万五千支、七成出口美国，2022年十五人、每天约三百支；词条两者都写，不作取舍。

本图集为它开辟一个没有田地的卷制产区——埃塞基耶尔蒙特斯：一个卷制别处烟叶的地方，如同德累斯顿或莫斯科。',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"Negro San Andrés（韦拉克鲁斯）","vitolas":[],"story":"五分之四浅色烟叶，五分之一深色——公司说有咖啡、朗姆和水果气息。"},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"Negro San Andrés（韦拉克鲁斯）","vitolas":[],"story":"深浅各半；公司说烟叶以朗姆和蜂蜜润湿。"}]',
        'Cházaro هي الدار الوحيدة في هذا الأطلس التي تلفّ في المكسيك خارج فيراكروز: في إسيكييل مونتيس بولاية كيريتارو، على طريق النبيذ والجبن، فتحت عائلة من أصل فيراكروزي نحو 2015 مصنعًا سمّته Real Fábrica de Tabacos تخليدًا لمصنع سان فرناندو الذي أقامه التاج في كيريتارو سنة 1779 — الثاني في إسبانيا الجديدة — والذي أُغلق في النصف الأوّل من القرن التاسع عشر. ولا تتّفق الصحيفتان اللتان زارتاه على السنة: أُسّس قبل 2018 بثلاث سنوات عند إحداهما، وأُنشئت العلامة سنة 2016 عند الأخرى؛ تكتب البطاقة الاثنتين. مفتوح للجمهور منذ 2017.

يأتي التبغ من سان أندريس توكستلا، والحرفيون أيضًا: أنطونيو توتو بوتشيتا، دون تونيو، معلّم اللفّ ذو الأربعين عامًا في المهنة، يقود الإنتاج مع لفّافين قادمين من الوادي، كلّ منهم بسبعين إلى تسعين سيجارًا في اليوم. ثلاثة خطوط — Black، أربعة أخماسه تبغ فاتح؛ Habano، نصفًا بنصف؛ Peña Blanca، بعرق قصب السكّر وعصير الفاكهة. وتختلف الأرقام بحسب السنة: خمسة عشر ألف سيجار في الشهر وسبعة أعشارها تُصدَّر إلى الولايات المتحدة سنة 2018، وخمسة عشر شخصًا ونحو ثلاثمئة سيجار في اليوم سنة 2022؛ تكتب البطاقة الاثنين بدل أن تختار.

يفتح لها هذا الأطلس منطقة لفّ، إسيكييل مونتيس، بلا حقول: مكان تُلفّ فيه ورقة منطقة أخرى، مثل درسدن أو موسكو.',
        '[{"name":"Black Cházaro","color":"#1C1C1C","force":"Mild-Medium","wrapper":"نيغرو سان أندريس (فيراكروز)","vitolas":[],"story":"أربعة أخماس تبغ فاتح وخُمس داكن — قهوة ورم وفاكهة، كما تقول الدار."},{"name":"Habano","color":"#8B4513","force":"Medium","wrapper":"نيغرو سان أندريس (فيراكروز)","vitolas":[],"story":"نصف داكن ونصف فاتح؛ أوراق مرطّبة بالرم والعسل، كما تقول الدار."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Tabaqueria de Filipinas : paragraphe ajoute, six langues ──
UPDATE `brands` SET `history` = CONCAT(`history`, '\n\n', 'Le recensement de 2026 n''a rien trouvé de plus récent que la presse asiatique du tabac de 2016, qui la donnait comme la plus grande fabrique de cigares du pays malgré sa jeunesse : plus de deux cents personnes, quinze mille cigares roulés à la main par jour, sous les marques Antonio Gimenez, Independencia 1898 et Flor de Filipinas.') WHERE `name` = 'Tabaqueria de Filipinas' AND `history` NOT LIKE '%recensement de 2026%';
UPDATE `brands` SET `history_en` = CONCAT(`history_en`, '\n\n', 'The 2026 census found nothing more recent than the Asian tobacco press of 2016, which gave it as the country''s largest cigar factory despite its youth: more than two hundred people, fifteen thousand hand-rolled cigars a day, under the Antonio Gimenez, Independencia 1898 and Flor de Filipinas brands.') WHERE `name` = 'Tabaqueria de Filipinas' AND `history_en` NOT LIKE '%2026 census%';
UPDATE `brands` SET `history_es` = CONCAT(`history_es`, '\n\n', 'El censo de 2026 no encontró nada más reciente que la prensa asiática del tabaco de 2016, que la daba como la mayor fábrica de puros del país pese a su juventud: más de doscientas personas, quince mil puros liados a mano al día, bajo las marcas Antonio Gimenez, Independencia 1898 y Flor de Filipinas.') WHERE `name` = 'Tabaqueria de Filipinas' AND `history_es` NOT LIKE '%censo de 2026%';
UPDATE `brands` SET `history_de` = CONCAT(`history_de`, '\n\n', 'Der Zensus von 2026 fand nichts Neueres als die asiatische Tabakpresse von 2016, die sie trotz ihrer Jugend als größte Zigarrenfabrik des Landes nannte: über zweihundert Menschen, fünfzehntausend handgerollte Zigarren am Tag, unter den Marken Antonio Gimenez, Independencia 1898 und Flor de Filipinas.') WHERE `name` = 'Tabaqueria de Filipinas' AND `history_de` NOT LIKE '%Zensus von 2026%';
UPDATE `brands` SET `history_zh` = CONCAT(`history_zh`, '\n\n', '2026年的普查没有找到比2016年亚洲烟草媒体更新的资料，那篇报道称它虽年轻却是该国规模第一位的雪茄厂：两百多人，每天手工卷制一万五千支，品牌为 Antonio Gimenez、Independencia 1898 和 Flor de Filipinas。') WHERE `name` = 'Tabaqueria de Filipinas' AND `history_zh` NOT LIKE '%2026年的普查%';
UPDATE `brands` SET `history_ar` = CONCAT(`history_ar`, '\n\n', 'لم يجد إحصاء 2026 شيئًا أحدث من صحافة التبغ الآسيوية سنة 2016، التي جعلتها كبرى مصانع السيجار في البلاد رغم حداثتها: أكثر من مئتي شخص، وخمسة عشر ألف سيجار ملفوف يدويًّا في اليوم، تحت علامات Antonio Gimenez وIndependencia 1898 وFlor de Filipinas.') WHERE `name` = 'Tabaqueria de Filipinas' AND `history_ar` NOT LIKE '%إحصاء 2026%';
UPDATE `brands` SET `source` = CONCAT(`source`, ' ; tobaccoasia.com « Cigars: Made in Asia » (4 mai 2016 : San Pedro, Laguna ; fondée en 1993 ; plus de 200 employés ; 15 000 cigares par jour ; marques Antonio Gimenez, Independencia 1898, Flor de Filipinas) — le recensement de 2026 n''a rien trouvé de plus récent') WHERE `name` = 'Tabaqueria de Filipinas' AND `source` NOT LIKE '%tobaccoasia%';

-- ── Joyas de Panama : gamme ecrite (elle etait vide), source completee ──
UPDATE `brands` SET `gamme` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"Panaméenne (Coclé)","vitolas":[],"story":"La marque de 1986, roulée à La Pintada sur semence cubaine acclimatée à Coclé."},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"Panaméenne (Coclé)","vitolas":[],"story":"La seconde marque de la fabrique, aux profils variés, dit le reportage de 2025 — sous Braulio Zurita, le fils de la fondatrice."}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme`) = 0;
UPDATE `brands` SET `gamme_en` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"Panamanian (Coclé)","vitolas":[],"story":"The 1986 brand, rolled at La Pintada on Cuban seed acclimatised in Coclé."},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"Panamanian (Coclé)","vitolas":[],"story":"The factory''s second brand, with varied profiles, says the 2025 report — under Braulio Zurita, the founder''s son."}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme_en`) = 0;
UPDATE `brands` SET `gamme_es` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"Panameña (Coclé)","vitolas":[],"story":"La marca de 1986, liada en La Pintada sobre semilla cubana aclimatada en Coclé."},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"Panameña (Coclé)","vitolas":[],"story":"La segunda marca de la fábrica, de perfiles variados, dice el reportaje de 2025 — bajo Braulio Zurita, el hijo de la fundadora."}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme_es`) = 0;
UPDATE `brands` SET `gamme_de` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"Panamaisch (Coclé)","vitolas":[],"story":"Die Marke von 1986, in La Pintada gerollt auf in Coclé akklimatisiertem kubanischem Saatgut."},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"Panamaisch (Coclé)","vitolas":[],"story":"Die zweite Marke der Fabrik, mit verschiedenen Profilen, sagt die Reportage von 2025 — unter Braulio Zurita, dem Sohn der Gründerin."}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme_de`) = 0;
UPDATE `brands` SET `gamme_zh` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"巴拿马（科克莱）","vitolas":[],"story":"1986年的品牌，在拉平塔达用驯化于科克莱的古巴种烟叶卷制。"},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"巴拿马（科克莱）","vitolas":[],"story":"据2025年报道，这是工厂的第二个品牌，风格多样——由创始人之子布劳略·苏里塔主持。"}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme_zh`) = 0;
UPDATE `brands` SET `gamme_ar` = '[{"name":"Joyas de Panamá","color":"#8B1A1A","force":"Medium","wrapper":"بنمية (كوكلي)","vitolas":[],"story":"علامة 1986، تُلفّ في لا بينتادا على بذور كوبية أُقلمت في كوكلي."},{"name":"Flor de Panamá","color":"#C9A227","force":"Mild-Medium","wrapper":"بنمية (كوكلي)","vitolas":[],"story":"العلامة الثانية للمصنع، بأنماط متنوّعة، كما يقول تحقيق 2025 — تحت إدارة براوليو سوريتا، ابن المؤسِّسة."}]' WHERE `name` = 'Joyas de Panamá' AND JSON_LENGTH(`gamme_ar`) = 0;
UPDATE `brands` SET `source` = CONCAT(`source`, ' ; dopanama.com « Joyas de Panama: Cuba''s Cigar Legacy in Volcanic Coclé » (15 septembre 2025 : Coclé Tobacco Factory de Peñonomé, mars 1981, Gilberto Oliva, fermée ; Tabacos Panamá S.A., La Pintada, 1984, Nestor Plasencia, fermée ; Joyas de Panamá rouverte sous Braulio Zurita ; seconde marque Flor de Panamá ; tout à la main, trois à six mois de fermentation)') WHERE `name` = 'Joyas de Panamá' AND `source` NOT LIKE '%Volcanic Cocl%';

-- ── ECUADOR ──
UPDATE `producer_countries` SET `notes` = CONCAT(`notes`, '\n\n', 'Le recensement de 2026 a cherché qui roule en Équateur, pays de cape par excellence : trois ateliers de Guayaquil, que seul le quotidien Expreso a décrits — la Real Fábrica de Cigarros La Clemencia, au Fortín, d''Atiliano Castellano et Eduardo Jurado, environ trois mille cigares par mois en 2020 sous la marque Guayacos ; l''atelier de Franklin Coello, au sud de la ville, marques Equinoccial, Libertador et Rumiñahui, vendues à l''aéroport ; Hacienda Real, de Geovanny León, plus de vingt ans en 2022, cinq personnes, qui exporta autrefois vers la France, l''Allemagne et l''Espagne. Le groupe Aray a fermé vers 2015. Une seule source par atelier : l''atlas les nomme ici et attend la seconde avant de leur donner une fiche.') WHERE `id` = 'ecuador' AND `notes` NOT LIKE '%recensement de 2026%';
UPDATE `producer_countries` SET `notes_en` = CONCAT(`notes_en`, '\n\n', 'The 2026 census looked for who rolls in Ecuador, the wrapper country par excellence: three Guayaquil workshops, described only by the daily Expreso — the Real Fábrica de Cigarros La Clemencia, in El Fortín, of Atiliano Castellano and Eduardo Jurado, about three thousand cigars a month in 2020 under the Guayacos brand; Franklin Coello''s workshop, in the south of the city, brands Equinoccial, Libertador and Rumiñahui, sold at the airport; Hacienda Real, of Geovanny León, more than twenty years old in 2022, five people, which once exported to France, Germany and Spain. The Aray group closed around 2015. One source per workshop: the atlas names them here and waits for the second before giving them an entry.') WHERE `id` = 'ecuador' AND `notes_en` NOT LIKE '%2026 census%';
UPDATE `producer_countries` SET `notes_es` = CONCAT(`notes_es`, '\n\n', 'El censo de 2026 buscó quién lía en Ecuador, el país de la capa por excelencia: tres talleres de Guayaquil, que solo el diario Expreso ha descrito — la Real Fábrica de Cigarros La Clemencia, en El Fortín, de Atiliano Castellano y Eduardo Jurado, unos tres mil puros al mes en 2020 bajo la marca Guayacos; el taller de Franklin Coello, al sur de la ciudad, marcas Equinoccial, Libertador y Rumiñahui, vendidas en el aeropuerto; Hacienda Real, de Geovanny León, más de veinte años en 2022, cinco personas, que exportó antaño a Francia, Alemania y España. El grupo Aray cerró hacia 2015. Una sola fuente por taller: el atlas los nombra aquí y espera la segunda antes de darles ficha.') WHERE `id` = 'ecuador' AND `notes_es` NOT LIKE '%censo de 2026%';
UPDATE `producer_countries` SET `notes_de` = CONCAT(`notes_de`, '\n\n', 'Der Zensus von 2026 suchte, wer in Ecuador rollt, dem Deckblattland schlechthin: drei Werkstätten in Guayaquil, die allein die Tageszeitung Expreso beschrieben hat — die Real Fábrica de Cigarros La Clemencia in El Fortín von Atiliano Castellano und Eduardo Jurado, etwa dreitausend Zigarren im Monat 2020 unter der Marke Guayacos; die Werkstatt von Franklin Coello im Süden der Stadt, Marken Equinoccial, Libertador und Rumiñahui, am Flughafen verkauft; Hacienda Real von Geovanny León, 2022 über zwanzig Jahre alt, fünf Leute, die einst nach Frankreich, Deutschland und Spanien exportierte. Die Gruppe Aray schloss um 2015. Eine Quelle je Werkstatt: Der Atlas nennt sie hier und wartet auf die zweite, bevor er ihnen einen Eintrag gibt.') WHERE `id` = 'ecuador' AND `notes_de` NOT LIKE '%Zensus von 2026%';
UPDATE `producer_countries` SET `notes_zh` = CONCAT(`notes_zh`, '\n\n', '2026年的普查寻找谁在厄瓜多尔——首屈一指的茄衣之国——卷制雪茄：瓜亚基尔的三家作坊，只有《Expreso》日报描述过——El Fortín 区的 Real Fábrica de Cigarros La Clemencia，由阿蒂利亚诺·卡斯特利亚诺和爱德华多·胡拉多创办，2020年每月约三千支，品牌 Guayacos；城南弗兰克林·科埃略的作坊，品牌 Equinoccial、Libertador、Rumiñahui，在机场销售；赫奥瓦尼·莱昂的 Hacienda Real，2022年时已逾二十年，五人，曾出口法国、德国和西班牙。Aray 集团约2015年关闭。每家作坊只有一个来源：图集在此点名，等有第二个来源再给词条。') WHERE `id` = 'ecuador' AND `notes_zh` NOT LIKE '%2026年的普查%';
UPDATE `producer_countries` SET `notes_ar` = CONCAT(`notes_ar`, '\n\n', 'بحث إحصاء 2026 عمّن يلفّ في الإكوادور، بلد الغلاف بامتياز: ثلاث ورش في غواياكيل لم تصفها سوى صحيفة Expreso اليومية — Real Fábrica de Cigarros La Clemencia في إل فورتين، لأتيليانو كاستيّانو وإدواردو خورادو، نحو ثلاثة آلاف سيجار في الشهر سنة 2020 تحت علامة Guayacos؛ وورشة فرانكلين كويّو في جنوب المدينة، علامات Equinoccial وLibertador وRumiñahui تُباع في المطار؛ وHacienda Real لخيوفاني ليون، أكثر من عشرين عامًا سنة 2022، خمسة أشخاص، صدّرت يومًا إلى فرنسا وألمانيا وإسبانيا. وأُغلقت مجموعة Aray نحو 2015. مصدر واحد لكلّ ورشة: يسمّيها الأطلس هنا وينتظر الثاني قبل أن يعطيها بطاقة.') WHERE `id` = 'ecuador' AND `notes_ar` NOT LIKE '%إحصاء 2026%';

-- ── COSTARICA ──
UPDATE `producer_countries` SET `brands` = '[{"desc":"Du dessinateur du Behike à sa propre maison","name":"Atabey","iconic":true},{"desc":"Le versant classique de Selected Tobacco","name":"Byron","iconic":false},{"desc":"Des tabacs mûris cinq ans avant roulage","name":"Bandolero","iconic":false},{"desc":"Maison britannique sans champs, roulée au Costa Rica","name":"Casdagli","iconic":false},{"name":"Selected Tobacco","desc":"Nelson Alfonso — la maison derrière Atabey, Byron et Bandolero","iconic":false},{"name":"Vegas de Santiago","desc":"La seule du pays qui cultive ce qu''elle roule","iconic":true},{"name":"Bombay Tobak","desc":"2014 — MBombay, troisième marque sortie de Puriscal","iconic":false},{"name":"Brun del Ré","desc":"Carlo Corazza, 2006 — usine propre à Escazú ; 1787 Libertad en tabac costaricien","iconic":true},{"name":"El Septimo","desc":"Genève 2005, Younan depuis 2019 — le luxe roulé au Costa Rica","iconic":false},{"name":"IGM Cigars","desc":"San José, 1997 selon la maison — la fabrique boutique qui roule Casdagli","iconic":false}]', `tabacaleras` = '["Tabacos de Costa Rica (Santiago de Puriscal)","IGM Cigars (San José)","Brun del Ré (Escazú)","Selected Tobacco (Puriscal)","El Septimo Cigar Factory (revendiquée)"]' WHERE `id` = 'costarica';
UPDATE `producer_countries` SET `notes` = CONCAT(`notes`, '\n\n', 'Ce n''est plus un seul acteur : le recensement de 2026 compte dix fiches et trois fabriques nommées — Tabacos de Costa Rica à Puriscal, Brun del Ré à Escazú, IGM à San José —, plus l''usine que revendique El Septimo. Puriscal, à plus de mille mètres, est le seul lieu du pays où l''on cultive ce qu''on roule. Tabacos de la Cordillera, de Puriscal, n''a plus de domaine et aucune presse : non écrite.') WHERE `id` = 'costarica' AND `notes` NOT LIKE '%recensement de 2026%';
UPDATE `producer_countries` SET `notes_en` = CONCAT(`notes_en`, '\n\n', 'No longer a single player: the 2026 census counts ten entries and three named factories — Tabacos de Costa Rica in Puriscal, Brun del Ré in Escazú, IGM in San José —, plus the plant El Septimo claims. Puriscal, above a thousand metres, is the only place in the country where what is rolled is also grown. Tabacos de la Cordillera, of Puriscal, no longer has a domain and no press: not written.') WHERE `id` = 'costarica' AND `notes_en` NOT LIKE '%2026 census%';
UPDATE `producer_countries` SET `notes_es` = CONCAT(`notes_es`, '\n\n', 'Ya no es un solo actor: el censo de 2026 cuenta diez fichas y tres fábricas nombradas — Tabacos de Costa Rica en Puriscal, Brun del Ré en Escazú, IGM en San José —, más la planta que reivindica El Septimo. Puriscal, a más de mil metros, es el único lugar del país donde se cultiva lo que se lía. Tabacos de la Cordillera, de Puriscal, ya no tiene dominio y ninguna prensa: no escrita.') WHERE `id` = 'costarica' AND `notes_es` NOT LIKE '%censo de 2026%';
UPDATE `producer_countries` SET `notes_de` = CONCAT(`notes_de`, '\n\n', 'Nicht mehr ein einziger Akteur: Der Zensus von 2026 zählt zehn Einträge und drei benannte Fabriken — Tabacos de Costa Rica in Puriscal, Brun del Ré in Escazú, IGM in San José —, dazu das Werk, das El Septimo beansprucht. Puriscal, über tausend Meter hoch, ist der einzige Ort des Landes, an dem angebaut wird, was gerollt wird. Tabacos de la Cordillera aus Puriscal hat keine Domain mehr und keine Presse: nicht geschrieben.') WHERE `id` = 'costarica' AND `notes_de` NOT LIKE '%Zensus von 2026%';
UPDATE `producer_countries` SET `notes_zh` = CONCAT(`notes_zh`, '\n\n', '不再是单一参与者：2026年的普查计有十个词条和三家点名的工厂——普里斯卡尔的 Tabacos de Costa Rica、埃斯卡苏的 Brun del Ré、圣何塞的 IGM——加上 El Septimo 自称的厂。海拔一千多米的普里斯卡尔是全国唯一种自己所卷之叶的地方。普里斯卡尔的 Tabacos de la Cordillera 域名已失效，也没有媒体报道：未写。') WHERE `id` = 'costarica' AND `notes_zh` NOT LIKE '%2026年的普查%';
UPDATE `producer_countries` SET `notes_ar` = CONCAT(`notes_ar`, '\n\n', 'لم يعد لاعبًا واحدًا: يعدّ إحصاء 2026 عشر بطاقات وثلاثة مصانع مسمّاة — Tabacos de Costa Rica في بوريسكال، وBrun del Ré في إسكاسو، وIGM في سان خوسيه — إضافة إلى المعمل الذي تدّعيه El Septimo. وبوريسكال، فوق ألف متر، هي المكان الوحيد في البلاد الذي يُزرع فيه ما يُلفّ. أمّا Tabacos de la Cordillera من بوريسكال فلم يعد لها نطاق ولا صحافة: لم تُكتب.') WHERE `id` = 'costarica' AND `notes_ar` NOT LIKE '%إحصاء 2026%';

-- ── MEXICO ──
UPDATE `producer_countries` SET `brands` = '[{"desc":"Marque mexicaine iconique depuis 1963","name":"Te Amo","iconic":true},{"cape":true,"desc":"Wrapper San Andrés par excellence","name":"CAO Black","iconic":false},{"desc":"La cape San Andrés à sa source","name":"Santa Clara 1830","iconic":true},{"desc":"Les planteurs de la vallée signent enfin leur travail","name":"Casa Turrent","iconic":true},{"desc":"Le terroir de San Andrés seul, sans rien pour l''accompagner","name":"Matacan","iconic":false},{"name":"Casa 1910","desc":"2021 — les puros de la Révolution ; fabrique de San Andrés non divulguée","iconic":false},{"name":"Tabacalera R. Paxtián","desc":"Sihuapan, 1990 — quatre générations de planteurs de San Andrés","iconic":false},{"name":"Cházaro","desc":"Ezequiel Montes (Querétaro), 2015 — le tabac de San Andrés roulé hors de Veracruz","iconic":false}]', `tabacaleras` = '["Casa Turrent / Nueva Matacapan Tabacos (San Andrés Tuxtla)","Santa Clara (San Andrés Tuxtla)","Tabacalera R. Paxtián (Sihuapan)","Cházaro — Real Fábrica de Tabacos (Ezequiel Montes)"]', `regions` = '["San Andrés Tuxtla","Los Tuxtlas","Ezequiel Montes (Querétaro)"]' WHERE `id` = 'mexico';
UPDATE `producer_countries` SET `notes` = CONCAT(`notes`, '\n\n', 'Le recensement de 2026 a relu la vallée dans la presse en espagnol : à côté des Turrent et de Santa Clara — soixante personnes, surtout des femmes, et au moins deux mille cinq cents cigares par jour, dit le Diario de Xalapa en 2023 —, la Tabacalera R. Paxtián de Sihuapan, quatre générations de planteurs ; et hors de Veracruz, pour la première fois, Cházaro à Ezequiel Montes, dans le Querétaro, qui roule le tabac de San Andrés avec des artisans de la vallée. Don Chicho, de San Andrés, n''a qu''une mention : non écrite.') WHERE `id` = 'mexico' AND `notes` NOT LIKE '%recensement de 2026%';
UPDATE `producer_countries` SET `notes_en` = CONCAT(`notes_en`, '\n\n', 'The 2026 census reread the valley in the Spanish-language press: alongside the Turrents and Santa Clara — sixty people, mostly women, and at least two thousand five hundred cigars a day, says the Diario de Xalapa in 2023 —, the Tabacalera R. Paxtián of Sihuapan, four generations of growers; and outside Veracruz, for the first time, Cházaro at Ezequiel Montes, in Querétaro, which rolls San Andrés tobacco with artisans from the valley. Don Chicho, of San Andrés, has only one mention: not written.') WHERE `id` = 'mexico' AND `notes_en` NOT LIKE '%2026 census%';
UPDATE `producer_countries` SET `notes_es` = CONCAT(`notes_es`, '\n\n', 'El censo de 2026 releyó el valle en la prensa en español: junto a los Turrent y a Santa Clara — sesenta personas, sobre todo mujeres, y al menos dos mil quinientos puros al día, dice el Diario de Xalapa en 2023 —, la Tabacalera R. Paxtián de Sihuapan, cuatro generaciones de sembradores; y fuera de Veracruz, por primera vez, Cházaro en Ezequiel Montes, en Querétaro, que lía el tabaco de San Andrés con artesanos del valle. Don Chicho, de San Andrés, solo tiene una mención: no escrita.') WHERE `id` = 'mexico' AND `notes_es` NOT LIKE '%censo de 2026%';
UPDATE `producer_countries` SET `notes_de` = CONCAT(`notes_de`, '\n\n', 'Der Zensus von 2026 las das Tal in der spanischsprachigen Presse neu: neben den Turrents und Santa Clara — sechzig Menschen, meist Frauen, und mindestens zweitausendfünfhundert Zigarren am Tag, sagt der Diario de Xalapa 2023 — die Tabacalera R. Paxtián in Sihuapan, vier Generationen von Pflanzern; und außerhalb von Veracruz zum ersten Mal Cházaro in Ezequiel Montes, in Querétaro, das den Tabak von San Andrés mit Handwerkern aus dem Tal rollt. Don Chicho aus San Andrés hat nur eine Erwähnung: nicht geschrieben.') WHERE `id` = 'mexico' AND `notes_de` NOT LIKE '%Zensus von 2026%';
UPDATE `producer_countries` SET `notes_zh` = CONCAT(`notes_zh`, '\n\n', '2026年的普查用西班牙语媒体重读了这条河谷：在图伦特家族和 Santa Clara——据《Diario de Xalapa》2023年报道，六十人、多为女性、每天至少两千五百支——之外，还有西瓦潘的 Tabacalera R. Paxtián，四代种植者；并且首次在韦拉克鲁斯之外收录克雷塔罗州埃塞基耶尔蒙特斯的 Cházaro，它用河谷匠人卷制圣安德烈斯烟叶。圣安德烈斯的 Don Chicho 只有一处提及：未写。') WHERE `id` = 'mexico' AND `notes_zh` NOT LIKE '%2026年的普查%';
UPDATE `producer_countries` SET `notes_ar` = CONCAT(`notes_ar`, '\n\n', 'أعاد إحصاء 2026 قراءة الوادي في الصحافة الإسبانية: إلى جانب آل تورينت وSanta Clara — ستّون شخصًا معظمهم نساء، وألفان وخمسمئة سيجار في اليوم على الأقلّ، كما تقول Diario de Xalapa سنة 2023 — Tabacalera R. Paxtián في سيواپان، أربعة أجيال من المزارعين؛ وخارج فيراكروز، للمرّة الأولى، Cházaro في إسيكييل مونتيس بكيريتارو التي تلفّ تبغ سان أندريس بحرفيين من الوادي. أمّا Don Chicho من سان أندريس فلها ذكر واحد: لم تُكتب.') WHERE `id` = 'mexico' AND `notes_ar` NOT LIKE '%إحصاء 2026%';

-- ── PHILIPPINES ──
UPDATE `producer_countries` SET `notes` = CONCAT(`notes`, '\n\n', 'Le recensement de 2026 n''a trouvé aucune fabrique de roulage main au-delà des quatre fiches de l''atlas — Tabacalera, La Flor de la Isabela, Alhambra, Tabaqueria de Filipinas — et le dit ; Mighty, à Bulacan, est une fabrique de machine.') WHERE `id` = 'philippines' AND `notes` NOT LIKE '%recensement de 2026%';
UPDATE `producer_countries` SET `notes_en` = CONCAT(`notes_en`, '\n\n', 'The 2026 census found no hand-rolling factory beyond the atlas''s four entries — Tabacalera, La Flor de la Isabela, Alhambra, Tabaqueria de Filipinas — and says so; Mighty, in Bulacan, is a machine factory.') WHERE `id` = 'philippines' AND `notes_en` NOT LIKE '%2026 census%';
UPDATE `producer_countries` SET `notes_es` = CONCAT(`notes_es`, '\n\n', 'El censo de 2026 no encontró ninguna fábrica de liado a mano más allá de las cuatro fichas del atlas — Tabacalera, La Flor de la Isabela, Alhambra, Tabaqueria de Filipinas — y lo dice; Mighty, en Bulacan, es una fábrica de máquina.') WHERE `id` = 'philippines' AND `notes_es` NOT LIKE '%censo de 2026%';
UPDATE `producer_countries` SET `notes_de` = CONCAT(`notes_de`, '\n\n', 'Der Zensus von 2026 fand keine Handroll-Fabrik über die vier Einträge des Atlas hinaus — Tabacalera, La Flor de la Isabela, Alhambra, Tabaqueria de Filipinas — und sagt es; Mighty in Bulacan ist eine Maschinenfabrik.') WHERE `id` = 'philippines' AND `notes_de` NOT LIKE '%Zensus von 2026%';
UPDATE `producer_countries` SET `notes_zh` = CONCAT(`notes_zh`, '\n\n', '2026年的普查在图集的四个词条——Tabacalera、La Flor de la Isabela、Alhambra、Tabaqueria de Filipinas——之外没有找到任何手工卷制工厂，并如实说明；布拉干的 Mighty 是机制工厂。') WHERE `id` = 'philippines' AND `notes_zh` NOT LIKE '%2026年的普查%';
UPDATE `producer_countries` SET `notes_ar` = CONCAT(`notes_ar`, '\n\n', 'لم يجد إحصاء 2026 أيّ مصنع لفّ يدوي خارج بطاقات الأطلس الأربع — Tabacalera وLa Flor de la Isabela وAlhambra وTabaqueria de Filipinas — ويقول ذلك؛ وMighty في بولاكان مصنع آلي.') WHERE `id` = 'philippines' AND `notes_ar` NOT LIKE '%إحصاء 2026%';

-- ── PANAMA ──
UPDATE `producer_countries` SET `tabacaleras` = '["Joyas de Panamá — La Pintada, Coclé, 1986, Miriam Padilla ; rouverte sous Braulio Zurita","Tabacos Panamá S.A. — La Pintada, 1984 (fermée)","Coclé Tobacco Factory — Peñonomé, 1981 (fermée)"]' WHERE `id` = 'panama';


INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'production_zones', z.`id`, 'note', l.lang, SHA1(z.`note`), 'machine', NOW()
  FROM `production_zones` z
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE z.`id` = 55
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'brands', b.`name`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'history' THEN b.`history` ELSE b.`gamme` END), 'machine', NOW()
  FROM `brands` b
  JOIN (SELECT 'history' champ UNION ALL SELECT 'gamme') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE b.`name` IN ('IGM Cigars','Tabacalera R. Paxtián','Cházaro','Tabaqueria de Filipinas','Joyas de Panamá')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'producer_countries', p.`id`, 'notes', l.lang, SHA1(p.`notes`), 'machine', NOW()
  FROM `producer_countries` p
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE p.`id` IN ('ecuador','costarica','mexico','philippines')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 228';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 228','systeme','trois_maisons_deux_pays','marque',0,
   'IGM Cigars (San Jose, Costa Rica — la fabrique boutique qui roule Casdagli), Tabacalera R. Paxtian (Sihuapan, San Andres Tuxtla — quatre generations depuis 1910), Chazaro (Ezequiel Montes, Queretaro — premiere maison mexicaine hors de Veracruz, zone 55)'),
  (NULL,'migration 228','systeme','ce_qui_n_est_pas_ecrit_est_dit','pays',0,
   'Les notes de l Equateur nomment les trois ateliers de Guayaquil (une source chacun) ; celles du Costa Rica disent Tabacos de la Cordillera sans domaine ; celles du Mexique disent Don Chicho a une mention ; celles des Philippines disent que rien n a ete trouve au-dela des quatre fiches'),
  (NULL,'migration 228','systeme','vitrines_completees','marque',0,
   'Tabaqueria de Filipinas : 200 personnes et 15 000 cigares par jour (2016). Joyas de Panama : gamme ecrite avec Flor de Panama, reportage de 2025. Costa Rica : tabacaleras reecrits — dix fiches, trois fabriques, plus un seul acteur. Panama : deux fabriques marquees fermees');

SELECT
  (SELECT COUNT(*) FROM `brands` WHERE `name` IN ('IGM Cigars', 'Tabacalera R. Paxtián', 'Cházaro')) = 3 AS trois_fiches,
  (SELECT COUNT(*) FROM `production_zones` WHERE `id` = 55) = 1 AS zone_queretaro,
  (SELECT SUM(`notes_ar` LIKE '%إحصاء 2026%') FROM `producer_countries` WHERE `id` IN ('ecuador','costarica','mexico','philippines')) = 4 AS quatre_notes,
  (SELECT JSON_LENGTH(`gamme_zh`) FROM `brands` WHERE `name` = 'Joyas de Panamá') = 2 AS panama_gamme,
  (SELECT `history_de` LIKE '%Zensus von 2026%' FROM `brands` WHERE `name` = 'Tabaqueria de Filipinas') AS filipinas_completee,
  (SELECT JSON_LENGTH(`tabacaleras`) FROM `producer_countries` WHERE `id` = 'costarica') = 5 AS costarica_cinq;
SELECT COUNT(*) AS marques, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `brands`;
