-- ════════════════════════════════════════════════════════
-- 229 — Lot 16 du sixieme recensement : les feuilles ont une source
-- ────────────────────────────────────────────────────────
-- TRENTE-DEUX FEUILLES ECRITES AU PREMIER JOUR, SANS COLONNE SOURCE.
-- La doctrine « aucune fiche sans source » ne pouvait donc pas etre
-- verifiee sur la table la plus exigeante de l'atlas — genese, culture,
-- caracteres, six langues. La colonne entre ici, comme `brands.source`
-- a la 195 : TEXT d'emblee (lecon 219). tools/sources.php la lit,
-- page.php la rend, schema.sql la porte.
--
-- ET LA FAMILLE CUBAINE RELUE — quatorze feuilles nees de la meme
-- semence, a Cuba, au Nicaragua, en Republique dominicaine, au Honduras
-- et au Panama — contre l'encyclopedie cubaine (ecured.cu), les
-- publications de la station de San Juan y Martinez (Cultivos
-- Tropicales, agris.fao.org) et la presse du metier (1995, 1996, 2015).
-- CE QUE LA RELECTURE A TROUVE :
--   Corojo        une selection des annees 1930-1940, pas une creation
--                 de 1947 ; loue aux Allones, nationalisee en 1960
--   Criollo       la variete est une selection de 1941 ; la plante des
--                 Tainos est l'usage — les deux, separes
--   Habano 2000   Bell 61-10 (presse) ou Habana 2.1.1 (EcuRed) : les
--                 deux ecrits ; diffusee en 1993
--   Corojo 99     SOEUR du Criollo 98, meme croisement (Habana 92 x
--                 Habana P.R.) — l'atlas ecrivait Criollo 98 x Corojo,
--                 sans source ; corrige, et dit
--   Havana 92     Corojo x lignee polonaise R x T ; mere des deux autres
--   Piloto Cubano Torano pere (usage) ou Satornini (presse 2015) : les
--                 deux ecrits
--   San Vicente   nee a la ferme San Vicente de la Vuelta Abajo, pas
--                 « dans le sud » dominicain ; culture reecrite
-- Les autres recoivent leur source sans changer de texte.
-- ════════════════════════════════════════════════════════

ALTER TABLE `feuilles` ADD COLUMN `source` TEXT NULL COMMENT 'D''où vient la fiche (229). Texte libre, comme brands.source.' AFTER `pairings_ar`;

-- ── cuba-corojo ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Cuba''s Best Wrapper » (été 1995 : Diego Rodríguez loue la vega aux Allones dans les années 1920, sélectionne la variété dans les années 1930-1940, meurt en 1956 ; son fils Daniel quitte Cuba au début de 1960 ; propriété nationalisée ; environ 160 hectares et 600 personnes en 1995) et « Tobacco Typology » (mai-juin 2015 : hybride des années 1940 nommé d''après la plantation El Corojo ; feuilles petites, très sensibles aux maladies ; retirée à la fin des années 1990 ; Corojo 99, Corojo 2012) ; ecured.cu « Variedades de tabacos » (le Corojo comme parent de Habana 92 et Habana 2000) — 1947, l''année de l''usage, ne vient d''aucune de ces sources',
    `genese` = 'Une sélection, pas une invention : dans les années 1930 et 1940, Diego Rodríguez, qui louait depuis les années 1920 la vega El Corojo, près de San Luis, dans la Vuelta Abajo, a trié des semences de Criollo jusqu''à obtenir une plante à part — feuille sombre, veines fines, faite pour la cape — et l''a nommée d''après sa ferme. L''année 1947 circule pour sa mise en culture ; la presse du métier ne la date pas si précisément, et la fiche le dit. Il est mort en 1956 ; son fils Daniel a quitté Cuba en 1960, et la vega a été nationalisée. Elle a régné sur les capes des havanes jusqu''à la fin des années 1990, avant que sa fragilité aux maladies ne la fasse remplacer par ses descendantes.',
    `genese_en` = 'A selection, not an invention: in the 1930s and 1940s Diego Rodríguez, who had rented the El Corojo vega near San Luis, in the Vuelta Abajo, since the 1920s, sorted Criollo seed until he obtained a plant apart — dark leaf, fine veins, made for wrapper — and named it after his farm. The year 1947 circulates for its coming into cultivation; the trade press does not date it so precisely, and the entry says so. He died in 1956; his son Daniel left Cuba in 1960, and the vega was nationalised. It reigned over Havana wrappers until the late 1990s, before its frailty to disease had it replaced by its descendants.',
    `genese_es` = 'Una selección, no una invención: en los años treinta y cuarenta Diego Rodríguez, que alquilaba desde los años veinte la vega El Corojo, cerca de San Luis, en la Vuelta Abajo, cribó semillas de Criollo hasta obtener una planta aparte — hoja oscura, venas finas, hecha para capa — y la nombró por su finca. El año 1947 circula para su puesta en cultivo; la prensa del oficio no la fecha con tanta precisión, y la ficha lo dice. Murió en 1956; su hijo Daniel dejó Cuba en 1960, y la vega fue nacionalizada. Reinó sobre las capas de los habanos hasta finales de los años noventa, antes de que su fragilidad ante las enfermedades la hiciera reemplazar por sus descendientes.',
    `genese_de` = 'Eine Auslese, keine Erfindung: In den 1930er und 1940er Jahren sortierte Diego Rodríguez, der seit den 1920er Jahren die Vega El Corojo bei San Luis in der Vuelta Abajo gepachtet hatte, Criollo-Saatgut, bis er eine eigene Pflanze erhielt — dunkles Blatt, feine Adern, fürs Deckblatt gemacht — und benannte sie nach seinem Hof. Das Jahr 1947 kursiert für ihren Anbaubeginn; die Fachpresse datiert es nicht so genau, und der Eintrag sagt es. Er starb 1956; sein Sohn Daniel verließ Kuba 1960, und die Vega wurde verstaatlicht. Sie beherrschte die Deckblätter der Havannas bis Ende der 1990er Jahre, bevor ihre Anfälligkeit für Krankheiten sie durch ihre Nachkommen ersetzen ließ.',
    `genese_zh` = '是选育，不是发明：1930和1940年代，自1920年代起租种下维尔塔圣路易斯附近 El Corojo 烟田的迭戈·罗德里格斯，从 Criollo 种子中反复筛选，得到一种与众不同的植株——叶色深、叶脉细、专为茄衣而生——并以自家农场命名。1947年这个年份在坊间流传为其投入种植之年；行业媒体并没有给出这么精确的日期，词条如实说明。他1956年去世；儿子丹尼尔1960年离开古巴，烟田被收归国有。它统治哈瓦那雪茄的茄衣直到1990年代末，随后因不耐病害而被其后代取代。',
    `genese_ar` = 'انتقاءٌ لا اختراع: في الثلاثينيات والأربعينيات، فرز دييغو رودريغيس، الذي كان يستأجر منذ العشرينيات مزرعة El Corojo قرب سان لويس في فويلتا أباخو، بذور الكريولو حتّى حصل على نبتة متميّزة — ورقة داكنة، عروق رفيعة، مصنوعة للغلاف — وسمّاها باسم مزرعته. وتتداول سنة 1947 لبدء زراعتها؛ ولا تؤرّخها صحافة المهنة بهذه الدقّة، وتقول البطاقة ذلك. مات سنة 1956؛ وغادر ابنه دانييل كوبا سنة 1960، وأُمّمت المزرعة. سادت على أغلفة الهافانا حتّى أواخر التسعينيات قبل أن تجعلها هشاشتها أمام الأمراض تُستبدل بسلالاتها.' WHERE `id` = 'cuba-corojo';

-- ── cuba-criollo ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : la variété Criollo mise au point vers 1941 à la station expérimentale de San Juan y Martínez ; selon Habanos S.A., le modèle génétique de toutes les semences cubaines d''aujourd''hui ; d''abord pour sous-cape et tripe ; Criollo 98, feuille courte, largeur à 65 % de la longueur) ; ecured.cu « Variedades de tabacos » (les variétés cubaines actuelles et leurs parents) — la présence de la plante à l''arrivée de Colomb est l''usage, pas une source',
    `genese` = 'Le mot veut dire « semence du pays », et il désigne deux choses que la fiche sépare : le tabac que les Taïnos fumaient déjà quand Colomb aborde l''île en 1492 — c''est l''usage, et aucune source ne le date mieux —, et la variété Criollo proprement dite, une sélection mise au point vers 1941 à la station expérimentale de San Juan y Martínez, dans la Vuelta Abajo, selon la presse du métier. C''est de cette seconde que descendent, de près ou de loin, toutes les semences cubaines d''aujourd''hui, et Habanos la tient pour leur modèle génétique.',
    `genese_en` = 'The word means "native seed", and it names two things the entry keeps apart: the tobacco the Taínos already smoked when Columbus reached the island in 1492 — that is usage, and no source dates it better —, and the Criollo variety proper, a selection developed around 1941 at the San Juan y Martínez experimental station, in the Vuelta Abajo, according to the trade press. It is from that second one that all of today''s Cuban seeds descend, near or far, and Habanos holds it to be their genetic model.',
    `genese_es` = 'La palabra quiere decir « semilla del país », y designa dos cosas que la ficha separa: el tabaco que los taínos ya fumaban cuando Colón llegó a la isla en 1492 — eso es el uso, y ninguna fuente lo fecha mejor —, y la variedad Criollo propiamente dicha, una selección desarrollada hacia 1941 en la estación experimental de San Juan y Martínez, en la Vuelta Abajo, según la prensa del oficio. De esa segunda descienden, de cerca o de lejos, todas las semillas cubanas de hoy, y Habanos la tiene por su modelo genético.',
    `genese_de` = 'Das Wort bedeutet „einheimisches Saatgut“ und benennt zwei Dinge, die der Eintrag auseinanderhält: den Tabak, den die Taíno schon rauchten, als Kolumbus 1492 die Insel erreichte — das ist Gebrauch, und keine Quelle datiert es besser —, und die eigentliche Sorte Criollo, eine um 1941 an der Versuchsstation von San Juan y Martínez in der Vuelta Abajo entwickelte Auslese, laut Fachpresse. Von dieser zweiten stammen, nah oder fern, alle heutigen kubanischen Samen ab, und Habanos hält sie für ihr genetisches Modell.',
    `genese_zh` = '这个词意为“本地种子”，指两件事，词条把它们分开：一是1492年哥伦布抵达该岛时泰诺人已在抽的烟草——这是惯例的说法，没有来源能给出更准确的日期；二是严格意义上的 Criollo 品种，据行业媒体，约1941年在下维尔塔圣胡安-马丁内斯试验站育成的选育系。今天所有古巴种子或近或远都源自后者，Habanos 视之为它们的遗传原型。',
    `genese_ar` = 'تعني الكلمة «بذرة البلد»، وتسمّي شيئين تفرّق بينهما البطاقة: التبغ الذي كان التاينو يدخّنونه حين بلغ كولومبوس الجزيرة سنة 1492 — وذلك عرفٌ لا يؤرّخه مصدر بأحسن من ذلك — وصنف الكريولو بمعناه الدقيق، وهو انتقاء طُوّر نحو 1941 في المحطّة التجريبية في سان خوان إي مارتينيس بفويلتا أباخو، بحسب صحافة المهنة. ومن هذا الثاني تنحدر، قريبًا أو بعيدًا، كلّ البذور الكوبية اليوم، وتعدّه Habanos نموذجها الوراثي.' WHERE `id` = 'cuba-criollo';

-- ── cuba-habano-2000 ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : croisement du Corojo et de Bell 61-10, un tabac de cigarette cubain ; la version des années 1980 s''appelait Habana 2.1.1 ; recroisée ensuite avec le Corojo ; Hirochi Robaina la dit avoir sauvé l''industrie cubaine ; essais d''Oliva Tobacco depuis 2001) ; ecured.cu « Variedades de tabacos » (Habana 2000 : croisement du Corojo et de la variété non commerciale Habana 2.1.1 ; 14 à 16 feuilles, 48-52 cm sur 24-28 ; très résistante à la pata prieta, résistante au moho azul ; sous toile et au soleil) ; une note du Centro de Información y Gestión Tecnológica de Pinar del Río (revue n° 2000-2, domaine cubain qui ne résout pas depuis l''étranger, non cité : variété diffusée en 1993 ; environ la moitié des surfaces sous toile de Pinar del Río à la récolte 1995-1996) ; habanos.com « Habano 2000 »',
    `genese` = 'Elle naît d''une catastrophe. À la fin des années 1970, le mildiou bleu — le moho azul des Cubains, un champignon qui ravage les plants — détruit la production, et la station de Pinar del Río cherche une cape qui lui résiste. Les sources décrivent la même filiation par deux bouts : la presse du métier dit un croisement du Corojo avec Bell 61-10, un tabac de cigarette, dont la version des années 1980 s''appelait Habana 2.1.1, recroisée ensuite avec le Corojo ; l''encyclopédie cubaine dit un croisement du Corojo avec Habana 2.1.1. Diffusée en 1993, elle couvrait près de la moitié des surfaces sous toile de Pinar del Río dès la récolte 1995-1996. On l''écrit aussi Habana 2000 : les deux graphies circulent.',
    `genese_en` = 'It was born of a catastrophe. In the late 1970s blue mould — the Cubans'' moho azul, a fungus that ravages the plants — destroyed production, and the Pinar del Río station looked for a wrapper that would resist it. The sources describe the same lineage from two ends: the trade press says a cross of Corojo with Bell 61-10, a cigarette tobacco, whose 1980s version was called Habana 2.1.1, then crossed again with Corojo; the Cuban encyclopaedia says a cross of Corojo with Habana 2.1.1. Released in 1993, it covered nearly half of Pinar del Río''s shade-grown area by the 1995-1996 harvest. It is also written Habana 2000: both spellings circulate.',
    `genese_es` = 'Nace de una catástrofe. A finales de los años setenta el moho azul — un hongo que arrasa las plantas — destruye la producción, y la estación de Pinar del Río busca una capa que le resista. Las fuentes describen la misma filiación por dos extremos: la prensa del oficio dice un cruce del Corojo con Bell 61-10, un tabaco de cigarrillo, cuya versión de los años ochenta se llamaba Habana 2.1.1, recruzada luego con el Corojo; la enciclopedia cubana dice un cruce del Corojo con Habana 2.1.1. Difundida en 1993, cubría cerca de la mitad de las superficies bajo tela de Pinar del Río desde la cosecha 1995-1996. También se escribe Habana 2000: las dos grafías circulan.',
    `genese_de` = 'Sie entstand aus einer Katastrophe. Ende der 1970er Jahre zerstörte der Blauschimmel — der moho azul der Kubaner, ein Pilz, der die Pflanzen verwüstet — die Produktion, und die Station von Pinar del Río suchte ein Deckblatt, das ihm widersteht. Die Quellen beschreiben dieselbe Abstammung von zwei Enden: Die Fachpresse nennt eine Kreuzung von Corojo mit Bell 61-10, einem Zigarettentabak, deren Version der 1980er Jahre Habana 2.1.1 hieß, dann erneut mit Corojo gekreuzt; die kubanische Enzyklopädie nennt eine Kreuzung von Corojo mit Habana 2.1.1. 1993 freigegeben, bedeckte sie schon zur Ernte 1995-1996 fast die Hälfte der Schattenflächen von Pinar del Río. Man schreibt sie auch Habana 2000: Beide Schreibweisen kursieren.',
    `genese_zh` = '它诞生于一场灾难。1970年代末，蓝霉——古巴人所说的 moho azul，一种毁坏植株的真菌——摧毁了生产，比那尔德里奥试验站寻找能抗它的茄衣。各来源从两端描述同一条谱系：行业媒体说是 Corojo 与卷烟烟草 Bell 61-10 的杂交，其1980年代的版本叫 Habana 2.1.1，随后再与 Corojo 回交；古巴百科全书说是 Corojo 与 Habana 2.1.1 的杂交。1993年推广，到1995-1996年收获季已覆盖比那尔德里奥近一半的遮阴种植面积。也写作 Habana 2000：两种写法并行。',
    `genese_ar` = 'وُلدت من كارثة. في أواخر السبعينيات دمّر العفن الأزرق — الـmoho azul عند الكوبيين، فطر يخرّب النبتات — الإنتاجَ، وبحثت محطّة بينار ديل ريو عن غلاف يقاومه. تصف المصادر النسب نفسه من طرفين: تقول صحافة المهنة إنّه تهجين للكوروخو مع Bell 61-10، وهو تبغ سجائر، كانت نسخته في الثمانينيات تُسمّى Habana 2.1.1، ثمّ هُجّن ثانيةً مع الكوروخو؛ وتقول الموسوعة الكوبية إنّه تهجين للكوروخو مع Habana 2.1.1. نُشرت سنة 1993، وغطّت نحو نصف مساحات الزراعة تحت القماش في بينار ديل ريو منذ موسم 1995-1996. وتُكتب أيضًا Habana 2000: الكتابتان متداولتان.' WHERE `id` = 'cuba-habano-2000';

-- ── nicaragua-corojo-99 ──
UPDATE `feuilles` SET `source` = 'ecured.cu « Variedades de tabacos » (Corojo 99 : variété sœur du Criollo 98, issue du même croisement, Habana 92 × Habana P.R. ; 160-170 cm ; 14 à 16 feuilles de 48-52 cm ; résistante au moho azul, à la pata prieta, au virus de la mosaïque et à la nécrose ambiantale ; sous toile et au soleil) ; agris.fao.org « Corojo-99, nueva variedad de tabaco negro productora de capas resistentes a las principales enfermedades » (notice de la publication cubaine) ; cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : feuille plus longue, largeur à 55 % de la longueur ; Hirochi Robaina la cultive depuis 2005 ; Corojo 2012 issue de Corojo 99, Criollo 98 et Habana 2000) ; redalyc.org, Cultivos Tropicales vol. 42 (2021 : le croisement Criollo 98/Habana 2000//Corojo 99/L 17 de 2001-2002) — la filiation « Criollo 98 × Corojo » écrite auparavant dans cette fiche ne vient d''aucune de ces sources',
    `genese` = 'Son nom promet le Corojo, et c''est là que la fiche doit être prudente : l''encyclopédie cubaine la dit sœur du Criollo 98, issue du même croisement — Habana 92 et Habana P.R. —, sélectionnée pour la cape et pour résister au mildiou bleu, à la pata prieta et au virus de la mosaïque ; l''atlas l''écrivait auparavant comme un croisement du Criollo 98 avec le Corojo de Diego Rodríguez, et aucune source consultée ne le soutient. Le nom dit donc ce qu''on lui a demandé — retrouver le goût et l''allure du Corojo — plus que ses parents. Diffusée en 1999, elle a depuis donné, croisée avec le Criollo 98, le Habana 2000 et une lignée L 17, les Corojo 2006 et 2012.',
    `genese_en` = 'Its name promises Corojo, and that is where the entry must be careful: the Cuban encyclopaedia calls it a sister of Criollo 98, from the same cross — Habana 92 and Habana P.R. —, selected for wrapper and to resist blue mould, black shank and mosaic virus; this atlas previously wrote it as a cross of Criollo 98 with Diego Rodríguez''s Corojo, and no source consulted supports that. The name therefore says what was asked of it — to recover the taste and look of Corojo — more than its parents. Released in 1999, it has since given, crossed with Criollo 98, Habana 2000 and an L 17 line, the Corojo 2006 and 2012.',
    `genese_es` = 'Su nombre promete el Corojo, y ahí la ficha debe ser prudente: la enciclopedia cubana la dice hermana del Criollo 98, salida del mismo cruce — Habana 92 y Habana P.R. —, seleccionada para capa y para resistir al moho azul, a la pata prieta y al virus del mosaico; el atlas la escribía antes como un cruce del Criollo 98 con el Corojo de Diego Rodríguez, y ninguna fuente consultada lo sostiene. El nombre dice pues lo que se le pidió — recuperar el gusto y el porte del Corojo — más que sus padres. Difundida en 1999, ha dado desde entonces, cruzada con el Criollo 98, el Habana 2000 y una línea L 17, los Corojo 2006 y 2012.',
    `genese_de` = 'Ihr Name verspricht Corojo, und da muss der Eintrag vorsichtig sein: Die kubanische Enzyklopädie nennt sie eine Schwester des Criollo 98, aus derselben Kreuzung — Habana 92 und Habana P.R. —, ausgelesen fürs Deckblatt und gegen Blauschimmel, Schwarzbeinigkeit und Mosaikvirus; dieser Atlas schrieb sie zuvor als Kreuzung des Criollo 98 mit dem Corojo von Diego Rodríguez, und keine befragte Quelle stützt das. Der Name sagt also, was man von ihr verlangte — Geschmack und Aussehen des Corojo wiederzufinden — mehr als ihre Eltern. 1999 freigegeben, hat sie seither, gekreuzt mit Criollo 98, Habana 2000 und einer Linie L 17, die Corojo 2006 und 2012 ergeben.',
    `genese_zh` = '它的名字许诺了 Corojo，词条恰恰要在这里谨慎：古巴百科全书说它是 Criollo 98 的姊妹系，出自同一杂交——Habana 92 与 Habana P.R.——为茄衣而选育，抗蓝霉、黑胫病和花叶病毒；本图集此前写它是 Criollo 98 与迭戈·罗德里格斯的 Corojo 的杂交，查阅的来源无一支持。所以名字说的是人们对它的要求——找回 Corojo 的味道和外观——而非它的亲本。1999年推广，此后与 Criollo 98、Habana 2000 和一个 L 17 品系杂交，产生了 Corojo 2006 和 2012。',
    `genese_ar` = 'يعد اسمها بالكوروخو، وهنا يجب أن تحذر البطاقة: تقول الموسوعة الكوبية إنّها شقيقة الكريولو 98، من التهجين نفسه — Habana 92 وHabana P.R. — انتُقيت للغلاف ولمقاومة العفن الأزرق وسواد الساق وفيروس الفسيفساء؛ وكان هذا الأطلس يكتبها من قبل تهجينًا للكريولو 98 مع كوروخو دييغو رودريغيس، ولا يدعم ذلك أيّ مصدر راجعناه. فالاسم يقول إذًا ما طُلب منها — استعادة طعم الكوروخو وهيئته — لا أبويها. نُشرت سنة 1999، وأعطت منذئذ، مهجّنةً مع الكريولو 98 وHabana 2000 وسلالة L 17، الكوروخو 2006 و2012.' WHERE `id` = 'nicaragua-corojo-99';

-- ── nicaragua-criollo-98 ──
UPDATE `feuilles` SET `source` = 'ecured.cu « Variedades de tabacos » (Criollo 98 : croisement de Habana 92 et de Habana P.R. ; 150-160 cm, entre-nœuds de 5 cm ; 14 à 16 feuilles de 48-52 cm sur 24-28 ; résistante au moho azul, à la pata prieta et au virus de la mosaïque ; sous toile, au soleil) ; cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : feuille courte, largeur à 65 % de la longueur ; Aganorsa en cultive sur 1 250 acres à Estelí, Jalapa et Condega ; 60 % de la ferme de Rocky Patel à Estelí) ; redalyc.org, Cultivos Tropicales vol. 42 (2021 : la Criollo 98 comme témoin commercial des nouvelles variétés cubaines)' WHERE `id` = 'nicaragua-criollo-98';

-- ── nicaragua-havana-92 ──
UPDATE `feuilles` SET `source` = 'ecured.cu « Variedades de tabacos » (Habana 92 : croisement du Corojo cubain et d''une lignée polonaise R × T ; 160-170 cm ; 14 à 18 feuilles de 40-45 cm ; résistante au moho azul, à la pata prieta et à la nécrose ambiantale ; culture au soleil) ; cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : donnée comme la variété principale alors cultivée à Cuba ; quelques acres chez Aganorsa au Nicaragua) — le profil aromatique n''est décrit par aucune source, la fiche s''en abstient',
    `genese` = 'La génération d''avant, et la mère des deux suivantes : l''encyclopédie cubaine la dit issue du croisement du Corojo avec une lignée polonaise, R × T, qui lui apporte la résistance au mildiou bleu et à la pata prieta ; croisée ensuite avec Habana P.R., elle a donné le Criollo 98 et le Corojo 99, que le Nicaragua a adoptés. Les trois feuilles nicaraguayennes sont donc trois étapes d''une même lignée née de la lutte contre le moho azul. En 2015, la presse du métier la donnait encore comme la variété principale de Cuba, et ne lui trouvait au Nicaragua que quelques acres.',
    `genese_en` = 'The generation before, and the mother of the two that followed: the Cuban encyclopaedia says it came from crossing Corojo with a Polish line, R × T, which gave it resistance to blue mould and black shank; crossed then with Habana P.R., it gave Criollo 98 and Corojo 99, which Nicaragua adopted. The three Nicaraguan leaves are thus three stages of one lineage born of the fight against moho azul. In 2015 the trade press still gave it as Cuba''s main variety, and found it only a few acres in Nicaragua.',
    `genese_es` = 'La generación anterior, y la madre de las dos siguientes: la enciclopedia cubana la dice salida del cruce del Corojo con una línea polaca, R × T, que le aporta la resistencia al moho azul y a la pata prieta; cruzada luego con Habana P.R., dio el Criollo 98 y el Corojo 99, que Nicaragua adoptó. Las tres hojas nicaragüenses son pues tres etapas de un mismo linaje nacido de la lucha contra el moho azul. En 2015 la prensa del oficio aún la daba como la variedad principal de Cuba, y solo le encontraba en Nicaragua unos pocos acres.',
    `genese_de` = 'Die Generation davor, und die Mutter der beiden folgenden: Die kubanische Enzyklopädie nennt sie aus der Kreuzung von Corojo mit einer polnischen Linie, R × T, hervorgegangen, die ihr die Resistenz gegen Blauschimmel und Schwarzbeinigkeit gab; dann mit Habana P.R. gekreuzt, ergab sie Criollo 98 und Corojo 99, die Nicaragua übernahm. Die drei nicaraguanischen Blätter sind also drei Stufen einer Linie, die aus dem Kampf gegen den moho azul entstand. 2015 nannte die Fachpresse sie noch Kubas Hauptsorte und fand ihr in Nicaragua nur wenige Acres.',
    `genese_zh` = '上一代，也是后两代的母本：古巴百科全书说它出自 Corojo 与波兰品系 R × T 的杂交，后者带来对蓝霉和黑胫病的抗性；随后与 Habana P.R. 杂交，生出 Criollo 98 和 Corojo 99，尼加拉瓜采用了它们。尼加拉瓜的三种烟叶因此是同一谱系——诞生于对抗 moho azul——的三个阶段。2015年，行业媒体仍把它列为古巴的主栽品种，而在尼加拉瓜只找到几英亩。',
    `genese_ar` = 'الجيل السابق، وأمّ الجيلين التاليين: تقول الموسوعة الكوبية إنّها من تهجين الكوروخو مع سلالة بولندية، R × T، منحتها مقاومة العفن الأزرق وسواد الساق؛ ثمّ هُجّنت مع Habana P.R. فأعطت الكريولو 98 والكوروخو 99 اللذين تبنّتهما نيكاراغوا. فالأوراق النيكاراغوية الثلاث ثلاث مراحل من سلالة واحدة وُلدت من مكافحة العفن الأزرق. وسنة 2015 كانت صحافة المهنة ما زالت تعدّها الصنف الرئيسي في كوبا، ولا تجد لها في نيكاراغوا إلّا بضعة أفدنة.' WHERE `id` = 'nicaragua-havana-92';

-- ── nicaragua-habano ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : les semences de souche cubaine cultivées hors de Cuba — Criollo 98, Corojo 99, Habana 2000, Habana 92 — chez Aganorsa, Rocky Patel, Oliva) ; ecured.cu « Variedades de tabacos » (les parents de chacune)' WHERE `id` = 'nicaragua-habano';

-- ── dominicaine-piloto-cubano ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Land: The Dominican Republic » (automne 1996 : semence de la Vuelta Abajo, la plus riche des trois dominicaines, tripe de force ; vallée du Cibao et du Yaque, Jacagua, Navarrete, Villa González, La Canela ; Hendrik Kelner, Emilio Reyes, Carlos Fuente Jr.) et « Tobacco Typology » (mai-juin 2015 : arrivée en 1962 de la zone cubaine dite Piloto, apportée par un émigré que l''article nomme Satornini ; plantation d''octobre ; Kelner : dans presque toute ligne Davidoff) — l''attribution à Carlos Toraño père, écrite auparavant dans cette fiche, est l''usage du métier, non une source consultée',
    `genese` = 'Une semence de la Vuelta Abajo, sortie de Cuba en 1962 — l''année où la rupture qui dispersa les familles cubaines déplaça aussi leurs graines. Qui l''a portée diverge selon qu''on lit : l''usage du métier dit Carlos Toraño père ; la presse du cigare, en 2015, nomme un émigré, Satornini, et une zone cubaine dite Piloto d''où viendrait le nom. La fiche écrit les deux. Semence cubaine à l''origine, elle est tenue aujourd''hui pour un tabac dominicain à part entière — et, dit Hendrik Kelner, présente à des doses variables dans presque toutes les lignes Davidoff.',
    `genese_en` = 'A seed from the Vuelta Abajo, out of Cuba in 1962 — the year when the rupture that scattered the Cuban families also moved their seeds. Who carried it differs by what one reads: trade usage says Carlos Toraño senior; the cigar press, in 2015, names an émigré, Satornini, and a Cuban zone called Piloto from which the name would come. The entry writes both. Cuban seed at the origin, it is held today to be a Dominican tobacco in its own right — and, says Hendrik Kelner, present in varying doses in almost every Davidoff line.',
    `genese_es` = 'Una semilla de la Vuelta Abajo, salida de Cuba en 1962 — el año en que la ruptura que dispersó a las familias cubanas desplazó también sus semillas. Quién la llevó diverge según lo que se lea: el uso del oficio dice Carlos Toraño padre; la prensa del puro, en 2015, nombra a un emigrado, Satornini, y una zona cubana llamada Piloto de donde vendría el nombre. La ficha escribe las dos. Semilla cubana en su origen, se la tiene hoy por un tabaco dominicano de pleno derecho — y, dice Hendrik Kelner, presente en dosis variables en casi todas las líneas Davidoff.',
    `genese_de` = 'Ein Samen aus der Vuelta Abajo, 1962 aus Kuba heraus — das Jahr, in dem der Bruch, der die kubanischen Familien zerstreute, auch ihre Samen versetzte. Wer ihn trug, weicht ab, je nachdem, was man liest: Der Brauch des Gewerbes nennt Carlos Toraño senior; die Zigarrenpresse nennt 2015 einen Emigranten, Satornini, und eine kubanische Zone namens Piloto, aus der der Name käme. Der Eintrag schreibt beides. Kubanischer Samen im Ursprung, gilt er heute als dominikanischer Tabak aus eigenem Recht — und ist, sagt Hendrik Kelner, in wechselnden Dosen in fast jeder Davidoff-Linie enthalten.',
    `genese_zh` = '一粒来自下维尔塔的种子，1962年离开古巴——那一年，驱散古巴家族的巨变也带走了他们的种子。是谁带来的，因读到的来源而异：行业惯例说是老卡洛斯·托拉尼奥；2015年的雪茄媒体点名一位移民萨托尼尼，以及一个名为 Piloto 的古巴产区，名字或由此而来。词条两者都写。起初是古巴种子，如今被视为地道的多米尼加烟草——亨德里克·凯尔纳说，几乎每条 Davidoff 产品线都以不同比例用到它。',
    `genese_ar` = 'بذرة من فويلتا أباخو، خرجت من كوبا سنة 1962 — السنة التي شتّت فيها القطيعةُ العائلاتِ الكوبية ونقلت بذورها أيضًا. ويختلف من حملها بحسب ما يُقرأ: يقول عرف المهنة كارلوس تورانيو الأب؛ وتسمّي صحافة السيجار سنة 2015 مهاجرًا اسمه ساتوريني، ومنطقة كوبية تُدعى بيلوتو يأتي منها الاسم. تكتب البطاقة الاثنين. بذرة كوبية في الأصل، تُعدّ اليوم تبغًا دومينيكيًّا بحقّ — وهي، كما يقول هندريك كلنر، حاضرة بجرعات متفاوتة في كلّ خطوط Davidoff تقريبًا.' WHERE `id` = 'dominicaine-piloto-cubano';

-- ── dominicaine-olor ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Land: The Dominican Republic » (automne 1996 : Olor, salé et plutôt neutre, mêlé à 10 ou 20 % comme assaisonnement ; les trois variétés du pays) et « Tobacco Typology » (mai-juin 2015 : cultivée par José Mendez & Co.) ; cigarworld.de et cigarpassion.ch (la seule semence proprement dominicaine)' WHERE `id` = 'dominicaine-olor';

-- ── dominicaine-san-vicente ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Land: The Dominican Republic » (automne 1996 : hybride du Piloto mis au point à la ferme San Vicente, dans la Vuelta Abajo cubaine ; moins puissant, plus acide ; cultivé comme les autres dans le Cibao et la vallée du Yaque) ; cigarpassion.ch (un croisement du Corojo apporté par les Cubains avec l''Olor, résistant à la sécheresse — version que la première ne donne pas, écrite) — la fixation « dans le sud du pays », écrite auparavant dans cette fiche, ne vient d''aucune source consultée',
    `genese` = 'Une variation du Piloto Cubano, et donc une petite-fille de la Vuelta Abajo — mais née là-bas, non ici : la presse du métier la dit mise au point à la ferme San Vicente, dans la Vuelta Abajo cubaine, avant de suivre le Piloto en République dominicaine. Un site suisse en donne une autre origine, un croisement de l''Olor local avec le Corojo apporté par les Cubains, choisi pour sa résistance à la sécheresse ; la fiche écrit les deux. L''atlas la situait dans le sud du pays ; aucune source ne le dit, et elle pousse comme ses aînées dans le Cibao.',
    `genese_en` = 'A variation of Piloto Cubano, and thus a granddaughter of the Vuelta Abajo — but born there, not here: the trade press says it was developed at the San Vicente farm, in Cuba''s Vuelta Abajo, before following Piloto to the Dominican Republic. A Swiss site gives it another origin, a cross of the local Olor with the Corojo the Cubans brought, chosen for its drought resistance; the entry writes both. This atlas placed it in the south of the country; no source says so, and it grows like its elders in the Cibao.',
    `genese_es` = 'Una variación del Piloto Cubano, y por tanto una nieta de la Vuelta Abajo — pero nacida allá, no aquí: la prensa del oficio la dice desarrollada en la finca San Vicente, en la Vuelta Abajo cubana, antes de seguir al Piloto a República Dominicana. Un sitio suizo le da otro origen, un cruce del Olor local con el Corojo traído por los cubanos, elegido por su resistencia a la sequía; la ficha escribe los dos. El atlas la situaba en el sur del país; ninguna fuente lo dice, y crece como sus mayores en el Cibao.',
    `genese_de` = 'Eine Abwandlung des Piloto Cubano, und damit eine Enkelin der Vuelta Abajo — aber dort geboren, nicht hier: Die Fachpresse nennt sie auf der Farm San Vicente in der kubanischen Vuelta Abajo entwickelt, bevor sie dem Piloto in die Dominikanische Republik folgte. Eine Schweizer Seite gibt ihr einen anderen Ursprung, eine Kreuzung des örtlichen Olor mit dem von den Kubanern mitgebrachten Corojo, gewählt wegen ihrer Trockenheitsresistenz; der Eintrag schreibt beides. Dieser Atlas verortete sie im Süden des Landes; keine Quelle sagt das, und sie wächst wie ihre Älteren im Cibao.',
    `genese_zh` = 'Piloto Cubano 的一个变种，因此是下维尔塔的孙辈——但生在那里而不是这里：行业媒体说它在古巴下维尔塔的圣维森特农场育成，随后跟着 Piloto 来到多米尼加。一家瑞士网站给出另一种起源：本地 Olor 与古巴人带来的 Corojo 的杂交，因抗旱而被选中；词条两者都写。本图集原先把它放在该国南部；没有来源这么说，它像前辈一样生长在锡瓦奥。',
    `genese_ar` = 'تنويعٌ على البيلوتو كوبانو، وهي بذلك حفيدة فويلتا أباخو — لكنّها وُلدت هناك لا هنا: تقول صحافة المهنة إنّها طُوّرت في مزرعة سان فيسينتي في فويلتا أباخو الكوبية قبل أن تتبع البيلوتو إلى جمهورية الدومينيكان. ويعطيها موقع سويسري أصلًا آخر، تهجينًا للأولور المحلي مع الكوروخو الذي جلبه الكوبيون، اختير لمقاومته الجفاف؛ تكتب البطاقة الاثنين. وكان هذا الأطلس يضعها في جنوب البلاد؛ ولا يقول ذلك مصدر، وهي تنمو كأسلافها في سيباو.',
    `culture` = 'Cultivée dans le Cibao, comme le Piloto et l''Olor — Jacagua, Navarrete, Villa González, La Canela —, avec un semis d''octobre pour éviter la sécheresse de janvier et février. C''est le même sang que le Piloto sur la même terre, et pourtant une feuille plus douce.',
    `culture_en` = 'Grown in the Cibao, like Piloto and Olor — Jacagua, Navarrete, Villa González, La Canela —, with an October planting to avoid the January-February dry spell. It is the same blood as Piloto on the same land, and yet a milder leaf.',
    `culture_es` = 'Cultivada en el Cibao, como el Piloto y el Olor — Jacagua, Navarrete, Villa González, La Canela —, con siembra de octubre para evitar la sequía de enero y febrero. Es la misma sangre que el Piloto en la misma tierra, y sin embargo una hoja más suave.',
    `culture_de` = 'Im Cibao angebaut, wie Piloto und Olor — Jacagua, Navarrete, Villa González, La Canela —, mit Aussaat im Oktober, um die Trockenheit von Januar und Februar zu meiden. Es ist dasselbe Blut wie Piloto auf demselben Boden, und doch ein milderes Blatt.',
    `culture_zh` = '像 Piloto 和 Olor 一样种在锡瓦奥——哈卡瓜、纳瓦雷特、比亚贡萨莱斯、拉卡内拉——十月播种以避开一二月的干旱。与 Piloto 同血同土，却是更温和的一片叶。',
    `culture_ar` = 'تُزرع في سيباو، مثل البيلوتو والأولور — خاكاغوا ونافاريتي وفيّا غونساليس ولا كانيلا — بزراعة في أكتوبر لتجنّب جفاف يناير وفبراير. الدم نفسه دم البيلوتو على الأرض نفسها، ومع ذلك ورقة ألطف.' WHERE `id` = 'dominicaine-san-vicente';

-- ── honduras-corojo ──
UPDATE `feuilles` SET `source` = 'camachocigars.com (la maison revendique la première feuille de Corojo cultivée hors de Cuba, dans la vallée de Jamastrán, dans les années 1960 — affirmation de la maison) ; cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : le Corojo original retiré de Cuba à la fin des années 1990 pour sa sensibilité aux maladies) et « Cuba''s Best Wrapper » (été 1995 : la sélection de Diego Rodríguez à El Corojo)' WHERE `id` = 'honduras-corojo';

-- ── honduras-connecticut-shade ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : la semence de Connecticut, issue de graines indonésiennes il y a plus d''un siècle, cultivée sous toile hors de sa vallée) ; la culture hondurienne sous toile est l''usage des fabriques de Danlí et de Jamastrán décrites dans les fiches de maisons de l''atlas' WHERE `id` = 'honduras-connecticut-shade';

-- ── panama-corojo ──
UPDATE `feuilles` SET `source` = 'dopanama.com « Joyas de Panama: Cuba''s Cigar Legacy in Volcanic Coclé » (15 septembre 2025 : Gilberto Oliva et Nestor Plasencia arrivent en mars 1981 avec des semences cubaines ; sols volcaniques enrichis par les cendres du Volcán Barú ; pluies de 1 500 à 2 000 mm, 24 à 28 °C toute l''année) ; newsroompanama.com (14 septembre 2025 : semence cubaine et techniques cubaines chez Joyas de Panamá) ; cigaraficionado.com « Cuba''s Best Wrapper » (été 1995 : l''origine de la lignée)' WHERE `id` = 'panama-corojo';

-- ── panama-habano ──
UPDATE `feuilles` SET `source` = 'dopanama.com « Joyas de Panama: Cuba''s Cigar Legacy in Volcanic Coclé » (15 septembre 2025 : semences cubaines apportées en 1981 par Gilberto Oliva et Nestor Plasencia ; villages de Sortová, Sonadora et La Pintada ; quarante ans de culture continue ; fabriques de Peñonomé et de La Pintada fermées) ; newsroompanama.com (14 septembre 2025 : tabac de Sortová, Sonadora et La Pintada chez Joyas de Panamá) — l''interdiction de Philippe II est l''usage panaméen, qu''aucune source consultée ne date ni ne cite' WHERE `id` = 'panama-habano';


INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'feuilles', f.`id`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'genese' THEN f.`genese` ELSE f.`culture` END), 'machine', NOW()
  FROM `feuilles` f
  JOIN (SELECT 'genese' champ UNION ALL SELECT 'culture') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE f.`id` IN ('cuba-corojo','cuba-criollo','cuba-habano-2000','nicaragua-corojo-99','nicaragua-criollo-98','nicaragua-havana-92','nicaragua-habano','dominicaine-piloto-cubano','dominicaine-olor','dominicaine-san-vicente','honduras-corojo','honduras-connecticut-shade','panama-corojo','panama-habano')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 229';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 229','systeme','feuilles_source_ajoutee','systeme',0,
   'feuilles.source (TEXT) : la table des feuilles n avait pas de colonne source, et la doctrine « aucune fiche sans source » y etait invisible. tools/sources.php la compte, page.php la rend, schema.sql la porte'),
  (NULL,'migration 229','systeme','famille_cubaine_relue','systeme',0,
   'Quatorze feuilles de semence cubaine relues contre EcuRed, la station de San Juan y Martinez et la presse du metier. Corojo 99 est la soeur du Criollo 98 (meme croisement Habana 92 x Habana P.R.), pas un croisement Criollo 98 x Corojo : corrige et dit. San Vicente est nee dans la Vuelta Abajo, pas dans le sud dominicain. Corojo : selection des annees 1930-1940, 1947 est l usage'),
  (NULL,'migration 229','systeme','divergences_ecrites','systeme',0,
   'Habano 2000 : Bell 61-10 (presse) ou Habana 2.1.1 (EcuRed). Piloto Cubano : Torano pere (usage) ou Satornini (presse 2015). Criollo : la plante des Tainos (usage) et la variete de 1941 (station), separees. Chaque fiche ecrit les versions au lieu d en choisir une');

SELECT
  (SELECT DATA_TYPE FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'feuilles' AND COLUMN_NAME = 'source') = 'text' AS colonne_text,
  (SELECT COUNT(*) FROM `feuilles` WHERE `source` IS NOT NULL AND `source` <> '') = 14 AS quatorze_sourcees,
  (SELECT `genese` LIKE '%sœur%' FROM `feuilles` WHERE `id` = 'nicaragua-corojo-99') AS corojo99_soeur,
  (SELECT `culture` LIKE '%Cibao%' FROM `feuilles` WHERE `id` = 'dominicaine-san-vicente') AS san_vicente_cibao,
  (SELECT `genese_ar` LIKE '%1941%' FROM `feuilles` WHERE `id` = 'cuba-criollo') AS criollo_ar;
SELECT COUNT(*) AS feuilles, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `feuilles`;
