-- ════════════════════════════════════════════════════════
-- 230 — Lot 17 du sixieme recensement : les Ameriques hors semence cubaine
-- ────────────────────────────────────────────────────────
-- DIX FEUILLES SOURCEES — Connecticut Shade et Broadleaf, les trois
-- equatoriennes, les trois bresiliennes, Negro San Andres, Cow Tongue —
-- contre la presse du metier (1999, 2005, 2009, 2015), la Connecticut
-- Historical Society, la presse de Bahia (2026) et d'Equateur (2022).
-- CE QUE LA RELECTURE A TROUVE :
--   Connecticut Shade   le demi-acre de Poquonock en 1900 ; 30 800 acres
--                       en 1921 ; le tabac reconstitue des annees 1950 ;
--                       2 000 acres en 1999 — genese reecrite
--   Mata Fina           « 1 200 mm de pluie » ne venait de nulle part :
--                       retire ; les communes de la DO de 2026 — culture
--                       reecrite
--   Arapiraca           « centre du tabac bresilien depuis le debut du
--                       XXe » est l'usage, dit comme tel ; Primo del Rey
--                       1960-1970 — genese reecrite
--   Cow Tongue          « rien n'a redemarre depuis 1988 » etait faux :
--                       Gore cultivait encore a May Pen en 1999 ; sol
--                       volcanique (presse) ou calcaire (atlas), les
--                       deux ecrits — culture et caracteres reecrits
-- Les six autres recoivent leur source sans changer de texte.
-- ════════════════════════════════════════════════════════

-- ── usa-connecticut-shade ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Made in the Shade: Connecticut Shade » (nov.-déc. 1999 : premières toiles en 1900 sur River Road, à Poquonock, dans la commune de Windsor, après l''importation de semence de Sumatra ; les Cullman plantent en 1906 ; pic de 30 800 acres en 1921, de Portland (Connecticut) à Brattleboro (Vermont) ; le tabac reconstitué des années 1950 amorce le déclin ; 700 à 800 acres dans les années 1980, 1 600 en 1992, environ 2 000 en 1999 ; mildiou bleu en 1997-1998 ; Windsor Shade, General Cigar, Consolidated ; cape de tête à 45-50 dollars la livre) et « Tobacco Typology » (mai-juin 2015 : semences 8212 et 211) ; connecticuthistory.org « Windsor Tobacco: Made in the Shade » (Tobacco Valley ; semences importées de Virginie dès 1640 ; le demi-acre d''essai de Poquonock ; 30 000 acres dans les années 1930 ; moins de 2 000 en 2006 ; Broadleaf, Havana Seed et tabac d''ombre, les trois variétés de la vallée)',
    `genese` = 'Vers 1900, la cape de Sumatra prend le marché américain, et des planteurs de la vallée du Connecticut vont en chercher la semence ; sous le soleil de Nouvelle-Angleterre, les feuilles brûlent. Quelqu''un remarque que la saison de Sumatra est couverte : en 1900, sur un demi-acre de River Road, à Poquonock, dans la commune de Windsor, on tend des toiles de gaze au-dessus du champ, et la cape d''ombre est née. Cinquante acres l''année suivante ; 30 800 acres en 1921, de Portland dans le Connecticut à Brattleboro dans le Vermont — le sommet. Le tabac reconstitué des années 1950 a commencé le déclin : 700 à 800 acres dans les années 1980, environ 2 000 en 1999, moins de 2 000 en 2006.',
    `genese_en` = 'Around 1900 Sumatra wrapper took the American market, and growers of the Connecticut valley went to fetch its seed; under the New England sun, the leaves burned. Someone noticed that Sumatra''s season is overcast: in 1900, on half an acre of River Road, in Poquonock, in the town of Windsor, cheesecloth was stretched over the field, and shade wrapper was born. Fifty acres the following year; 30,800 acres in 1921, from Portland, Connecticut, to Brattleboro, Vermont — the peak. The homogenised tobacco of the 1950s began the decline: 700 to 800 acres in the 1980s, about 2,000 in 1999, fewer than 2,000 in 2006.',
    `genese_es` = 'Hacia 1900 la capa de Sumatra toma el mercado estadounidense, y plantadores del valle del Connecticut van a buscar su semilla; bajo el sol de Nueva Inglaterra, las hojas se queman. Alguien nota que la temporada de Sumatra es nublada: en 1900, en medio acre de River Road, en Poquonock, en el municipio de Windsor, se tienden telas de gasa sobre el campo, y nace la capa de sombra. Cincuenta acres al año siguiente; 30 800 acres en 1921, de Portland, en Connecticut, a Brattleboro, en Vermont — la cima. El tabaco reconstituido de los años cincuenta empezó el declive: de 700 a 800 acres en los años ochenta, unos 2 000 en 1999, menos de 2 000 en 2006.',
    `genese_de` = 'Um 1900 nahm das Sumatra-Deckblatt den amerikanischen Markt, und Pflanzer des Connecticut-Tals holten sich sein Saatgut; unter der Sonne Neuenglands verbrannten die Blätter. Jemand bemerkte, dass die Saison Sumatras bedeckt ist: 1900 wurde auf einem halben Acre an der River Road in Poquonock, in der Gemeinde Windsor, Gaze über das Feld gespannt, und das Schatten-Deckblatt war geboren. Fünfzig Acres im Jahr darauf; 30 800 Acres 1921, von Portland in Connecticut bis Brattleboro in Vermont — der Gipfel. Der rekonstituierte Tabak der 1950er Jahre leitete den Niedergang ein: 700 bis 800 Acres in den 1980er Jahren, etwa 2 000 im Jahr 1999, unter 2 000 im Jahr 2006.',
    `genese_zh` = '1900年前后，苏门答腊茄衣占领了美国市场，康涅狄格河谷的种植者去弄来它的种子；在新英格兰的阳光下，叶子被灼伤。有人注意到苏门答腊的生长季多云：1900年，在温莎镇波夸诺克河路的半英亩地上，人们在田上拉起纱布，遮阴茄衣由此诞生。次年五十英亩；1921年30800英亩，从康涅狄格州波特兰到佛蒙特州布拉特尔伯勒——顶峰。1950年代的再造烟草开启了衰退：1980年代700到800英亩，1999年约两千英亩，2006年不足两千英亩。',
    `genese_ar` = 'نحو 1900 استولى غلاف سومطرة على السوق الأمريكية، فذهب مزارعو وادي كونيكتيكت يجلبون بذوره؛ وتحت شمس نيو إنغلاند احترقت الأوراق. لاحظ أحدهم أنّ موسم سومطرة غائم: سنة 1900، على نصف فدّان من ريفر رود في بوكونوك ببلدة وندسور، مُدّت أقمشة الشاش فوق الحقل، فوُلد غلاف الظلّ. خمسون فدّانًا في السنة التالية؛ و30800 فدّان سنة 1921، من بورتلاند في كونيكتيكت إلى براتلبورو في فيرمونت — القمّة. وبدأ التبغ المعاد تكوينه في الخمسينيات الانحدارَ: 700 إلى 800 فدّان في الثمانينيات، ونحو ألفين سنة 1999، وأقلّ من ألفين سنة 2006.' WHERE `id` = 'usa-connecticut-shade';

-- ── usa-broadleaf ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Made in the Shade: Connecticut Shade » (nov.-déc. 1999 : le Broadleaf, feuilles épaisses et sombres aux veines marquées, cultivé en plein soleil, pour les maduros et les cigares de machine ; les trois tabacs de la vallée) et « Tobacco Typology » (mai-juin 2015) ; connecticuthistory.org « Windsor Tobacco: Made in the Shade » (semences importées de Virginie dès 1640 ; Broadleaf, Havana Seed et tabac d''ombre ; 30 000 acres dans les années 1930)' WHERE `id` = 'usa-broadleaf';

-- ── equateur-connecticut ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : la semence de Connecticut, elle-même issue de graines indonésiennes il y a plus d''un siècle ; en Équateur, moins chère, plus abondante, feuille génétiquement plus épaisse et plus élastique ; ASP Enterprises y cultive depuis 1987) ; expreso.ec « Los puros de Ecuador se resisten a morir » (3 décembre 2022 : 80 % de couverture nuageuse dans les secteurs de Guayas, Milagro, Los Ríos et Quevedo ; 73,6 millions de dollars et 3 716 tonnes de tabac exportées en 2020) — sources en anglais et en espagnol' WHERE `id` = 'equateur-connecticut';

-- ── equateur-habano ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : les semences de souche cubaine — Habano 2000 en essai chez Oliva Tobacco depuis 2001 — cultivées en Équateur pour les fabriques du Nicaragua, du Honduras et de République dominicaine ; Oliva Tobacco Co. et Plasencia y ont leurs exploitations) ; expreso.ec (3 décembre 2022 : la couverture nuageuse de Guayas, Milagro, Los Ríos et Quevedo, 80 % de la saison, remplace les toiles ; exportations de feuilles 2020) ; ecured.cu « Variedades de tabacos » (les parents des semences cubaines)' WHERE `id` = 'equateur-habano';

-- ── equateur-sumatra ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : feuilles grandes et épaisses, à la texture tachetée, élastiques ; Oliva Tobacco Co. en cultive abondamment en Équateur ; capes de Punch, Hoyo de Monterrey, Ashton Virgin Sun Grown, La Gloria Cubana) ; expreso.ec (3 décembre 2022 : la couverture nuageuse et le pays comme premier fournisseur de capes) — la semence de Sumatra elle-même : voir la feuille Deli Sumatra' WHERE `id` = 'equateur-sumatra';

-- ── bresil-mata-fina ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « The Cigar from Brazil » (sept.-oct. 2005 : la plus connue des variétés brésiliennes, du Recôncavo ; medium à corsée, douce et aromatique selon José Seijas ; Menendez Amerino, 1977, près de cent rouleurs) et glossaire « Mata Fina » (Recôncavo, sols sableux clairs, district humide) ; bahianoticias.com.br (8 juillet 2026 : dénominations d''origine Tabaco Mata Fina et Charuto Artesanal du Recôncavo, portées par l''Apcab et Inovates à l''INPI) ; www.fortenoreconcavo.com.br (23 juillet 2026 : Cruz das Almas, Cachoeira, São Félix, Muritiba, Governador Mangabeira, Conceição da Feira) ; degustandocharutos.wordpress.com (19 avril 2012 : tout le tabac sombre de Bahia est du Mata Fina d''origine ; Mata Norte, Mata Sul, Mata São Gonçalo, des microclimats plus que des variétés) — sources en anglais et en portugais',
    `culture` = 'Culture de plein soleil dans le Recôncavo, la baie qui entoure Salvador — Cruz das Almas, Cachoeira, São Félix, Muritiba, Governador Mangabeira, Conceição da Feira sont les communes que la dénomination d''origine en préparation en 2026 énumère. Le Recôncavo est plus arrosé que le nord de la zone, et c''est cette eau qui la distingue de sa voisine ; les sols sableux clairs du district lui sont attribués par la presse du métier.',
    `culture_en` = 'Sun-grown in the Recôncavo, the bay around Salvador — Cruz das Almas, Cachoeira, São Félix, Muritiba, Governador Mangabeira, Conceição da Feira are the municipalities the designation of origin in preparation in 2026 lists. The Recôncavo is wetter than the north of the zone, and it is that water that sets it apart from its neighbour; the district''s light sandy soils are attributed to it by the trade press.',
    `culture_es` = 'Cultivo a pleno sol en el Recôncavo, la bahía que rodea Salvador — Cruz das Almas, Cachoeira, São Félix, Muritiba, Governador Mangabeira, Conceição da Feira son los municipios que enumera la denominación de origen en preparación en 2026. El Recôncavo es más lluvioso que el norte de la zona, y es esa agua la que la distingue de su vecina; los suelos arenosos claros del distrito se los atribuye la prensa del oficio.',
    `culture_de` = 'Sonnenanbau im Recôncavo, der Bucht um Salvador — Cruz das Almas, Cachoeira, São Félix, Muritiba, Governador Mangabeira, Conceição da Feira sind die Gemeinden, die die 2026 in Vorbereitung befindliche Ursprungsbezeichnung aufzählt. Der Recôncavo ist regenreicher als der Norden der Zone, und dieses Wasser unterscheidet sie von ihrer Nachbarin; die hellen Sandböden des Distrikts schreibt ihr die Fachpresse zu.',
    `culture_zh` = '在环绕萨尔瓦多的海湾雷孔卡沃全日照种植——克鲁斯-达斯阿尔马斯、卡舒埃拉、圣费利克斯、穆里蒂巴、戈韦纳多尔曼加贝拉、孔塞桑-达费拉，是2026年筹备中的原产地命名所列的市镇。雷孔卡沃比该区北部多雨，正是这份水把它与邻居区分开；行业媒体把该地区浅色沙质土归于它。',
    `culture_ar` = 'زراعة في الشمس الكاملة في ريكونكافو، الخليج المحيط بسلفادور — كروز داس ألماس وكاشويرا وساو فيليكس وموريتيبا وغوفيرنادور مانغابيرا وكونسيساو دا فيرا هي البلديات التي تعدّدها تسمية المنشأ قيد الإعداد سنة 2026. وريكونكافو أغزر مطرًا من شمال المنطقة، وهذا الماء هو ما يميّزها عن جارتها؛ وتنسب إليها صحافة المهنة تربة المقاطعة الرملية الفاتحة.' WHERE `id` = 'bresil-mata-fina';

-- ── bresil-mata-norte ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « The Cigar from Brazil » (sept.-oct. 2005 : le nord du Recôncavo, tabac sombre et fort, dominant dans l''assemblage Dona Flor) ; degustandocharutos.wordpress.com (19 avril 2012 : la même plante que le Mata Fina, un microclimat plus sec ; séchage à l''air libre) ; www.fortenoreconcavo.com.br (23 juillet 2026 : les communes du Recôncavo) — sources en anglais et en portugais' WHERE `id` = 'bresil-mata-norte';

-- ── bresil-arapiraca ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « The Cigar from Brazil » (sept.-oct. 2005 : tabac d''Alagoas, cultivé au soleil ; cape lourde, corps épais, goût doux et neutre, combustion remarquable et cendre très blanche selon José Seijas ; dans les Primo del Rey des années 1960-1970 ; pour les maduros aujourd''hui) et « General Cigar''s CAO BX3 » (sous-cape d''Arapiraca sous une cape Mata Fina) ; luxurycigarclub.com et smallbatchcigar.com (Arapiraca, État d''Alagoas ; plus épaisse et plus grasse que la Mata Fina) — la ville d''Arapiraca comme centre du tabac brésilien depuis le début du XXe siècle est l''usage, qu''aucune source consultée ne date',
    `genese` = 'Celle-ci n''est pas de Bahia mais de l''État voisin d''Alagoas, dont la ville d''Arapiraca tient le nom et le tabac ; que la ville soit le centre du tabac brésilien depuis le début du XXe siècle est l''usage, et aucune source consultée ne le date. La presse du métier la connaît depuis longtemps : elle habillait les Primo del Rey des années 1960 et 1970, et sert aujourd''hui aux maduros.',
    `genese_en` = 'This one is not from Bahia but from the neighbouring state of Alagoas, whose town of Arapiraca holds the name and the tobacco; that the town has been the centre of Brazilian tobacco since the early twentieth century is usage, and no source consulted dates it. The trade press has long known it: it dressed the Primo del Reys of the 1960s and 1970s, and serves maduros today.',
    `genese_es` = 'Esta no es de Bahía sino del vecino estado de Alagoas, cuya ciudad de Arapiraca tiene el nombre y el tabaco; que la ciudad sea el centro del tabaco brasileño desde principios del siglo XX es el uso, y ninguna fuente consultada lo fecha. La prensa del oficio la conoce desde hace tiempo: vestía los Primo del Rey de los años sesenta y setenta, y sirve hoy para los maduros.',
    `genese_de` = 'Diese stammt nicht aus Bahia, sondern aus dem Nachbarstaat Alagoas, dessen Stadt Arapiraca den Namen und den Tabak trägt; dass die Stadt seit dem frühen 20. Jahrhundert das Zentrum des brasilianischen Tabaks sei, ist Gebrauch, und keine befragte Quelle datiert es. Die Fachpresse kennt sie seit Langem: Sie kleidete die Primo del Rey der 1960er und 1970er Jahre und dient heute den Maduros.',
    `genese_zh` = '这一种不产自巴伊亚，而是邻州阿拉戈斯，其城镇阿拉皮拉卡既给了名字也给了烟叶；说该镇自二十世纪初就是巴西烟草中心，那是惯例说法，查阅的来源无一给出日期。行业媒体早就认识它：它曾包裹1960和1970年代的 Primo del Rey，如今用于马杜罗。',
    `genese_ar` = 'هذه ليست من باهيا بل من ولاية ألاغواس المجاورة، التي تحمل مدينتها أرابيراكا الاسم والتبغ؛ وأمّا أنّ المدينة مركز التبغ البرازيلي منذ مطلع القرن العشرين فعُرف، ولا يؤرّخه مصدر راجعناه. وتعرفها صحافة المهنة منذ زمن: كانت تكسو سيجار Primo del Rey في الستينيات والسبعينيات، وتخدم المادورو اليوم.' WHERE `id` = 'bresil-arapiraca';

-- ── mexique-negro-san-andres ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Te-Amo''s Alberto and Alejandro Turrent » (janvier-février 2009 : l''arrière-grand-père Turrent cultive dans la vallée de San Andrés dès 1880 ; la vallée, ses sols volcaniques et ses brises du golfe) et « Casa Turrent 1880 to Ship in Four Varieties » ; humolatino.com « Tabacalera R. Paxtián, un siglo de tabaco » (14 novembre 2023 : le Negro San Andrés, tabac sombre de la vallée, tenu par la famille Paxtián pour la meilleure cape mûre — affirmation de la maison) ; eluniversalqueretaro.mx (20 septembre 2018 : le tabac noir de San Andrés Tuxtla roulé à Ezequiel Montes) — les immigrants cubains et allemands des années 1830 sont l''usage de la vallée, qu''aucune source consultée ne date' WHERE `id` = 'mexique-negro-san-andres';

-- ── jamaique-cow-tongue ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « Jamaica''s Cigar Comeback » (juillet-août 1999 : la cow tongue, dite aussi silver tongue, pousse à l''état sauvage dans le sol volcanique de l''île ; tabac indigène ; les Cubains ouvrent des fabriques pendant la Seconde Guerre mondiale pour le marché britannique ; Temple Hall, rachetée par General Cigar en 1969 ; l''ouragan Gilbert détruit en septembre 1988 la fabrique de Kingston de Robert Gore, debout depuis 1935, mille acres de tabac à May Pen et 35 séchoirs pleins ; en 1999 Gore cultive encore à May Pen) et « Hurricane Season » ; cigardojo.com (décembre 2020 : Royal Jamaica revient, roulée en République dominicaine) — la plaine calcaire de May Pen, écrite auparavant dans cette fiche, contredit le sol volcanique de la presse : les deux sont écrits',
    `culture` = 'Elle poussait dans la plaine de May Pen, à cinquante kilomètres à l''ouest de Kingston, et autour de la capitale — sur un sol que la presse du métier dit volcanique, là où l''atlas écrivait une plaine calcaire ; la fiche garde les deux. L''ouragan Gilbert, en septembre 1988, a détruit la fabrique de Kingston, debout depuis 1935, mille acres de tabac à May Pen et trente-cinq séchoirs pleins ; la production est partie en République dominicaine. En 1999, Robert Gore cultivait encore à May Pen ; l''atlas n''a rien trouvé de plus récent sur ces champs, et le dit.',
    `culture_en` = 'It grew on the May Pen plain, fifty kilometres west of Kingston, and around the capital — on a soil the trade press calls volcanic, where this atlas wrote a limestone plain; the entry keeps both. Hurricane Gilbert, in September 1988, destroyed the Kingston factory, standing since 1935, a thousand acres of tobacco at May Pen and thirty-five full curing barns; production left for the Dominican Republic. In 1999 Robert Gore still grew at May Pen; the atlas has found nothing more recent on those fields, and says so.',
    `culture_es` = 'Crecía en la llanura de May Pen, a cincuenta kilómetros al oeste de Kingston, y alrededor de la capital — en un suelo que la prensa del oficio dice volcánico, donde el atlas escribía una llanura calcárea; la ficha conserva los dos. El huracán Gilbert, en septiembre de 1988, destruyó la fábrica de Kingston, en pie desde 1935, mil acres de tabaco en May Pen y treinta y cinco secaderos llenos; la producción se fue a República Dominicana. En 1999 Robert Gore aún cultivaba en May Pen; el atlas no ha encontrado nada más reciente sobre esos campos, y lo dice.',
    `culture_de` = 'Sie wuchs in der Ebene von May Pen, fünfzig Kilometer westlich von Kingston, und um die Hauptstadt — auf einem Boden, den die Fachpresse vulkanisch nennt, wo dieser Atlas eine Kalkebene schrieb; der Eintrag behält beides. Der Hurrikan Gilbert zerstörte im September 1988 die Fabrik von Kingston, die seit 1935 stand, tausend Acres Tabak in May Pen und fünfunddreißig volle Trockenscheunen; die Produktion ging in die Dominikanische Republik. 1999 baute Robert Gore noch in May Pen an; der Atlas hat nichts Neueres über diese Felder gefunden, und sagt es.',
    `culture_zh` = '它生长在金斯敦以西五十公里的梅彭平原和首都周边——行业媒体说那是火山土，本图集原先写的是石灰岩平原；词条两者都保留。1988年9月的飓风吉尔伯特摧毁了自1935年屹立的金斯敦工厂、梅彭的一千英亩烟田和三十五座装满烟叶的烤房；生产迁往多米尼加。1999年罗伯特·戈尔仍在梅彭种植；图集没有找到关于这些田地更新的资料，并如实说明。',
    `culture_ar` = 'كانت تنمو في سهل ماي بن، على خمسين كيلومترًا غرب كينغستون، وحول العاصمة — على تربة تقول صحافة المهنة إنّها بركانية، حيث كان هذا الأطلس يكتب سهلًا كلسيًّا؛ تحتفظ البطاقة بالاثنين. ودمّر إعصار غيلبرت في سبتمبر 1988 مصنع كينغستون القائم منذ 1935 وألف فدّان من التبغ في ماي بن وخمسة وثلاثين مجفّفًا ممتلئًا؛ ورحل الإنتاج إلى جمهورية الدومينيكان. سنة 1999 كان روبرت غور ما زال يزرع في ماي بن؛ ولم يجد الأطلس شيئًا أحدث عن تلك الحقول، ويقول ذلك.',
    `caracteres` = 'Une feuille dont l''atlas parle surtout au passé, et c''est assumé. La Jamaïque fut, dans les années 1960 et 1970, le premier pays du cigare des Caraïbes hors de Cuba, et expédiait encore vingt-trois millions de cigares faits main aux États-Unis en 1998 ; ses marques — Royal Jamaica, Macanudo — se roulent aujourd''hui ailleurs, et Royal Jamaica est revenue en 2020 depuis la République dominicaine.',
    `caracteres_en` = 'A leaf this atlas speaks of mostly in the past tense, and that is deliberate. Jamaica was, in the 1960s and 1970s, the leading cigar country of the Caribbean outside Cuba, and still shipped twenty-three million handmade cigars to the United States in 1998; its brands — Royal Jamaica, Macanudo — are rolled elsewhere today, and Royal Jamaica came back in 2020 from the Dominican Republic.',
    `caracteres_es` = 'Una hoja de la que el atlas habla sobre todo en pasado, y es deliberado. Jamaica fue, en los años sesenta y setenta, el primer país del puro del Caribe fuera de Cuba, y aún enviaba veintitrés millones de puros hechos a mano a Estados Unidos en 1998; sus marcas — Royal Jamaica, Macanudo — se lían hoy en otra parte, y Royal Jamaica volvió en 2020 desde República Dominicana.',
    `caracteres_de` = 'Ein Blatt, von dem dieser Atlas vor allem im Präteritum spricht, und das ist gewollt. Jamaika war in den 1960er und 1970er Jahren das führende Zigarrenland der Karibik außerhalb Kubas und lieferte 1998 noch dreiundzwanzig Millionen handgemachte Zigarren in die Vereinigten Staaten; seine Marken — Royal Jamaica, Macanudo — werden heute anderswo gerollt, und Royal Jamaica kehrte 2020 aus der Dominikanischen Republik zurück.',
    `caracteres_zh` = '本图集谈到这片叶子时多用过去时，这是有意的。1960和1970年代，牙买加是古巴之外加勒比地区的雪茄大国，1998年仍向美国运送两千三百万支手工雪茄；它的品牌——Royal Jamaica、Macanudo——如今在别处卷制，Royal Jamaica 于2020年从多米尼加回归。',
    `caracteres_ar` = 'ورقة يتحدّث عنها هذا الأطلس بصيغة الماضي في الغالب، وذلك مقصود. كانت جامايكا في الستينيات والسبعينيات بلد السيجار الأوّل في الكاريبي خارج كوبا، وكانت ما زالت تشحن ثلاثة وعشرين مليون سيجار يدوي إلى الولايات المتحدة سنة 1998؛ وعلاماتها — Royal Jamaica وMacanudo — تُلفّ اليوم في مكان آخر، وعادت Royal Jamaica سنة 2020 من جمهورية الدومينيكان.' WHERE `id` = 'jamaique-cow-tongue';


INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'feuilles', f.`id`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'genese' THEN f.`genese` WHEN 'culture' THEN f.`culture` ELSE f.`caracteres` END), 'machine', NOW()
  FROM `feuilles` f
  JOIN (SELECT 'genese' champ UNION ALL SELECT 'culture' UNION ALL SELECT 'caracteres') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE f.`id` IN ('usa-connecticut-shade','usa-broadleaf','equateur-connecticut','equateur-habano','equateur-sumatra','bresil-mata-fina','bresil-mata-norte','bresil-arapiraca','mexique-negro-san-andres','jamaique-cow-tongue')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 230';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 230','systeme','dix_feuilles_des_ameriques_sourcees','systeme',0,
   'Connecticut Shade et Broadleaf, Ecuador Connecticut, Habano et Sumatra, Mata Fina, Mata Norte, Arapiraca, Negro San Andres, Cow Tongue : sourcees contre la presse du metier, la Connecticut Historical Society, la presse de Bahia (2026) et d Equateur (2022). 24 feuilles sur 32 ont une source'),
  (NULL,'migration 230','systeme','quatre_feuilles_corrigees','systeme',0,
   'Connecticut Shade : le demi-acre de Poquonock (1900) et les chiffres d acreage. Mata Fina : « 1 200 mm » retire, faute de source. Arapiraca : le centre du tabac « depuis le debut du XXe » dit comme usage. Cow Tongue : Gore cultivait encore a May Pen en 1999 — « rien n a redemarre » etait faux ; sol volcanique (presse) ou calcaire (atlas), les deux ecrits');

SELECT
  (SELECT COUNT(*) FROM `feuilles` WHERE `source` IS NOT NULL AND `source` <> '') = 24 AS vingt_quatre_sourcees,
  (SELECT `genese` LIKE '%Poquonock%' FROM `feuilles` WHERE `id` = 'usa-connecticut-shade') AS shade_poquonock,
  (SELECT `culture` NOT LIKE '%1 200%' FROM `feuilles` WHERE `id` = 'bresil-mata-fina') AS mata_fina_sans_chiffre_orphelin,
  (SELECT `culture_ar` LIKE '%1999%' FROM `feuilles` WHERE `id` = 'jamaique-cow-tongue') AS cow_tongue_ar;
SELECT COUNT(*) AS feuilles, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `feuilles`;
