-- ════════════════════════════════════════════════════════
-- 231 — Lot 18 du sixieme recensement : l'Ancien Monde et l'Asie
-- ────────────────────────────────────────────────────────
-- HUIT FEUILLES SOURCEES — Cameroun, La Palma, Kentucky, Deli, Besuki,
-- Cagayan, Tiebissou, Didievi — et les 32 le sont toutes.
-- CE QUE LA RELECTURE A TROUVE :
--   Cameroun    « des colons neerlandais au debut du XXe » vient de
--               detaillants ; la presse du metier (1998) fait commencer
--               l'histoire avec la SEITA et Jean Masseron, fin des
--               annees 1950 — les deux ecrits, genese reecrite
--   Deli        « semence native jamais importee » etait faux : Nienhuys
--               apporta la culture depuis Java oriental en 1863 ; Deli
--               Maatschappij le 1er novembre 1869 — genese et culture
--               reecrites
--   Besuki      un nom et une date : George Birnie, 1859, Jenggawah —
--               genese reecrite
--   Cagayan     « Cimaba, Viscaya » ne viennent de nulle part : retires ;
--               le galion San Clemente de 1592, le monopole 1782-1881 —
--               genese et caracteres reecrits
--   Kentucky    le sechage au feu precise (10-15 jours, bois non
--               resineux, sans cheminee) ; les cinq regions — culture
--               reecrite
--   La Palma, Tiebissou, Didievi : leur source, sans changer de texte —
--               les deux ivoiriennes restent sans caracteres, et le disent.
-- ════════════════════════════════════════════════════════

-- ── cameroun-cape ──
UPDATE `feuilles` SET `source` = 'cigaraficionado.com « C''est l''Afrique: Cameroon Wrapper Leaf » (janvier-février 1998 : à la fin des années 1950, la SEITA envoie Jean Masseron établir des plantations, mettre au point des variétés et former les planteurs ; la cape centrafricaine se vend aux États-Unis et en Europe dans les années 1960 ; la SEITA se retire en 1993 en invoquant l''absence de demande ; Rick Meerapfel, M. Meerapfel Söhne, plus de cent vingt ans, avec la CETAC détenue à 40 % par des Centrafricains ; Batouri, Tapourou près de Berbérati, Gamboula ; culture au soleil sous couverture nuageuse, sans toile ; près de 5 000 personnes et 3 000 planteurs sous contrat ; balles de 78 kilos expédiées aux Pays-Bas ; Fuente Don Carlos, Partagas, H. Upmann) — l''introduction par des colons néerlandais au début du XXe siècle, écrite auparavant dans cette fiche, vient de sites de détaillants ; la presse du métier fait commencer l''histoire avec la SEITA : les deux sont écrits',
    `genese` = 'Deux récits pour une origine, et la fiche les écrit tous les deux. Les sites de détaillants font apporter la semence de Sumatra en Afrique centrale par des colons néerlandais au début du XXe siècle ; la presse du métier, elle, fait commencer l''histoire à la fin des années 1950, quand le monopole français, la SEITA, envoie un agronome, Jean Masseron, établir des plantations, mettre au point les variétés et apprendre aux planteurs à cultiver et à fermenter. La SEITA achète et exporte seule la récolte jusqu''à son retrait de la région, en 1993, faute de demande, dit-elle. La maison M. Meerapfel Söhne, qui négociait cette feuille depuis plus de cent vingt ans en 1998, a repris la filière avec une société centrafricaine, la CETAC, et on lui attribue de l''avoir sauvée de la disparition.',
    `genese_en` = 'Two accounts of one origin, and the entry writes both. Retailers'' sites have Dutch settlers bring Sumatra seed to Central Africa in the early twentieth century; the trade press, for its part, begins the story in the late 1950s, when the French monopoly, SEITA, sent an agronomist, Jean Masseron, to set up plantations, develop the varieties and teach growers to grow and ferment. SEITA alone bought and exported the crop until its withdrawal from the region in 1993, for lack of demand, it said. The house of M. Meerapfel Söhne, which had traded this leaf for more than a hundred and twenty years by 1998, took the chain over with a Central African company, CETAC, and is credited with saving it from disappearing.',
    `genese_es` = 'Dos relatos para un origen, y la ficha escribe los dos. Los sitios de minoristas hacen llevar la semilla de Sumatra a África central por colonos neerlandeses a principios del siglo XX; la prensa del oficio, en cambio, empieza la historia a finales de los años cincuenta, cuando el monopolio francés, la SEITA, envía a un agrónomo, Jean Masseron, a establecer plantaciones, desarrollar las variedades y enseñar a los plantadores a cultivar y fermentar. La SEITA compra y exporta sola la cosecha hasta su retirada de la región, en 1993, por falta de demanda, según dijo. La casa M. Meerapfel Söhne, que negociaba esta hoja desde hacía más de ciento veinte años en 1998, retomó la cadena con una sociedad centroafricana, la CETAC, y se le atribuye haberla salvado de la desaparición.',
    `genese_de` = 'Zwei Erzählungen für einen Ursprung, und der Eintrag schreibt beide. Händlerseiten lassen niederländische Siedler das Sumatra-Saatgut Anfang des 20. Jahrhunderts nach Zentralafrika bringen; die Fachpresse dagegen beginnt die Geschichte Ende der 1950er Jahre, als das französische Monopol, die SEITA, einen Agronomen, Jean Masseron, entsandte, um Pflanzungen anzulegen, die Sorten zu entwickeln und die Pflanzer im Anbau und in der Fermentation zu unterweisen. Die SEITA kaufte und exportierte die Ernte allein bis zu ihrem Rückzug aus der Region 1993, mangels Nachfrage, wie sie sagte. Das Haus M. Meerapfel Söhne, das dieses Blatt 1998 seit über hundertzwanzig Jahren handelte, übernahm die Kette mit einer zentralafrikanischen Gesellschaft, der CETAC, und ihm wird zugeschrieben, es vor dem Verschwinden bewahrt zu haben.',
    `genese_zh` = '同一个起源，两种叙述，词条两者都写。零售商网站说二十世纪初荷兰殖民者把苏门答腊种子带到中非；行业媒体则把故事的开端放在1950年代末，当时法国专营公司 SEITA 派农学家让·马塞龙去建立种植园、培育品种，并教种植者栽培和发酵。SEITA 独家收购并出口这批烟叶，直到1993年以需求不足为由撤出该地区。M. Meerapfel Söhne 公司到1998年已经营这种烟叶一百二十多年，它与中非公司 CETAC 接手了整条产业链，人们认为是它让这种烟叶免于消失。',
    `genese_ar` = 'روايتان لأصل واحد، وتكتب البطاقة الاثنتين. تجعل مواقع تجّار التجزئة مستوطنين هولنديين يجلبون بذور سومطرة إلى وسط أفريقيا في مطلع القرن العشرين؛ أمّا صحافة المهنة فتبدأ الحكاية في أواخر الخمسينيات حين أرسل الاحتكار الفرنسي، SEITA، مهندسًا زراعيًّا هو جان ماسرون لإقامة المزارع وتطوير الأصناف وتعليم المزارعين الزراعة والتخمير. واشترت SEITA وحدها المحصول وصدّرته حتّى انسحابها من المنطقة سنة 1993 لغياب الطلب، كما قالت. أمّا دار M. Meerapfel Söhne، التي كانت تتاجر بهذه الورقة منذ أكثر من مئة وعشرين سنة في 1998، فاستلمت السلسلة مع شركة من أفريقيا الوسطى هي CETAC، ويُنسب إليها إنقاذها من الاندثار.' WHERE `id` = 'cameroun-cape';

-- ── canaries-la-palma ──
UPDATE `feuilles` SET `source` = 'eldiario.es « El puro palmero es un producto estrella único y espectacular » (la Compañía Insular de Tabaco de La Palma, 1917, et le tabac de l''île) ; diariodeavisos.com « Finca El Sitio, reserva tabaquera de Europa » (la finca de Breña Alta, cultivo bajo telón) ; humolatino.com (Vargas, 1925 ; le mildiou bleu de 1967) ; lapalmabiosfera.es et purosartesanosjulio.com (plantations et roulage d''un seul tenant) — les sources sont celles des six fiches de maisons palmeras de l''atlas ; l''effondrement de la cochenille et les émigrants revenus de Cuba avec les semences sont l''usage de l''île, qu''aucune source consultée ne date' WHERE `id` = 'canaries-la-palma';

-- ── italie-kentucky ──
UPDATE `feuilles` SET `source` = 'it.wikipedia.org « Sigaro toscano » (le Kentucky, tabac sombre de la classe des fire-cured, séché au feu direct dix à quinze jours sur des bois non résineux — chêne, rouvre, cerro — sans cheminée ; cultivé en Toscane, Campanie, Latium, Ombrie et Vénétie, dans cet ordre ; les feuilles du Sud, de Bénévent, pour les Toscano plus doux ; monopole d''État, puis BAT, puis Manifatture Sigaro Toscano en 2006) ; manifatturesigarotoscano.it « History » (la légende d''août 1815, la manufacture de Florence fondée en 1818 par Ferdinand III — les sources officielles nomment elles-mêmes ce récit une légende) ; gustotabacco.it et bottegadelfumatore.com (Compagnia Toscana Sigari, le Kentucky cultivé en Valtiberina) — la date d''arrivée de la semence en Italie n''est donnée précisément par aucune source consultée ; l''usage dit le début du XIXe siècle',
    `culture` = 'Récoltée en fin d''été, puis séchée AU FEU : la feuille passe dix à quinze jours dans une grange close, au-dessus d''un feu lent de bois non résineux — chêne, rouvre, cerro — et sans cheminée, pour que la fumée pénètre la feuille. Ce n''est pas de la fumaison au sens culinaire : le feu sèche autant qu''il parfume, et c''est ce que presque aucune autre origine ne pratique pour le cigare. On la cultive en Toscane, en Campanie, dans le Latium, en Ombrie et en Vénétie, dans cet ordre de volume ; la Valtiberina, entre Toscane et Ombrie, et Bénévent sont les deux noms qui reviennent — le Sud pour les Toscano plus doux.',
    `culture_en` = 'Harvested in late summer, then FIRE-cured: the leaf spends ten to fifteen days in a closed barn, above a slow fire of non-resinous wood — oak, sessile oak, Turkey oak — and without a chimney, so that the smoke enters the leaf. It is not smoking in the culinary sense: the fire dries as much as it scents, and that is what almost no other origin practises for cigars. It is grown in Tuscany, Campania, Lazio, Umbria and Veneto, in that order of volume; the Valtiberina, between Tuscany and Umbria, and Benevento are the two names that recur — the South for the milder Toscanos.',
    `culture_es` = 'Cosechada a finales del verano, y luego secada AL FUEGO: la hoja pasa de diez a quince días en un granero cerrado, sobre un fuego lento de madera no resinosa — roble, roble albar, cerro — y sin chimenea, para que el humo penetre la hoja. No es ahumado en el sentido culinario: el fuego seca tanto como perfuma, y es lo que casi ningún otro origen practica para el puro. Se cultiva en Toscana, Campania, Lacio, Umbría y Véneto, en ese orden de volumen; la Valtiberina, entre Toscana y Umbría, y Benevento son los dos nombres que vuelven — el Sur para los Toscano más suaves.',
    `culture_de` = 'Im Spätsommer geerntet, dann am FEUER getrocknet: Das Blatt verbringt zehn bis fünfzehn Tage in einer geschlossenen Scheune über einem langsamen Feuer aus harzfreiem Holz — Eiche, Traubeneiche, Zerreiche — und ohne Kamin, damit der Rauch in das Blatt eindringt. Es ist kein Räuchern im kulinarischen Sinn: Das Feuer trocknet ebenso, wie es Duft gibt, und das praktiziert für Zigarren kaum eine andere Herkunft. Angebaut wird sie in der Toskana, in Kampanien, Latium, Umbrien und Venetien, in dieser Reihenfolge der Menge; die Valtiberina zwischen Toskana und Umbrien und Benevent sind die zwei Namen, die wiederkehren — der Süden für die milderen Toscano.',
    `culture_zh` = '夏末收获，然后用火烤干：烟叶在封闭的烤房里待十到十五天，架在无树脂木材——橡木、无梗花栎、土耳其栎——的慢火之上，不设烟囱，让烟渗入叶片。这不是烹饪意义上的熏制：火既烘干也赋香，几乎没有别的产地这样处理雪茄烟叶。种植区按产量依次为托斯卡纳、坎帕尼亚、拉齐奥、翁布里亚和威尼托；托斯卡纳与翁布里亚之间的瓦尔蒂贝里纳，以及贝内文托，是常被提起的两个名字——南方的烟叶用于较温和的 Toscano。',
    `culture_ar` = 'تُحصد في أواخر الصيف ثمّ تُجفَّف على النار: تقضي الورقة عشرة إلى خمسة عشر يومًا في حظيرة مغلقة فوق نار بطيئة من خشب غير راتنجي — البلّوط والسنديان والبلّوط التركي — ومن دون مدخنة كي يتخلّل الدخان الورقة. ليس تدخينًا بالمعنى المطبخي: النار تجفّف بقدر ما تعطّر، وذلك ما لا يكاد يمارسه أيّ منشأ آخر للسيجار. تُزرع في توسكانا وكامبانيا ولاتسيو وأومبريا وفينيتو، بهذا الترتيب في الكمّية؛ وفالتيبيرينا بين توسكانا وأومبريا، وبينيفينتو، هما الاسمان اللذان يتكرّران — الجنوب لسيجار Toscano الألطف.' WHERE `id` = 'italie-kentucky';

-- ── indonesie-deli ──
UPDATE `feuilles` SET `source` = 'britannica.com « Jacobus Nienhuys » (le pionnier néerlandais qui installe la culture du tabac à Deli en 1863) ; storiesfromdeli.com « Deli Data 1863-1938 » (concession en 1863, première récolte expérimentale de cinquante balles ; main-d''œuvre chinoise venue de Singapour ; Deli Maatschappij fondée le 1er novembre 1869 avec la Nederlandsche Handel-Maatschappij, Janssen et Clemen) ; researchgate.net « Deli Maatschappij''s Contribution to the Transformation of East Sumatera, 1869-1940s » ; cigaraficionado.com « Tobacco Typology » (mai-juin 2015 : la semence de Sumatra à l''origine des Connecticut) — la fiche écrivait une semence native jamais importée : une publication dit que Nienhuys apporta la culture depuis Java oriental, et la fiche le dit désormais',
    `genese` = 'Jacobus Nienhuys, un Néerlandais, obtient en 1863 une concession sur la côte est de Sumatra, à Deli, autour de l''actuelle Medan, et y plante un premier essai : cinquante balles d''un tabac dont la qualité surprend. Une publication indonésienne dit qu''il apporta la culture depuis Java oriental — la fiche écrivait auparavant une semence native jamais importée, et se corrige. Le 1er novembre 1869, avec la Nederlandsche Handel-Maatschappij et deux associés, il fonde la Deli Maatschappij, qui attire les capitaux néerlandais et fait venir de Singapour une main-d''œuvre chinoise. Avec Besuki à Java Est et Klaten à Java Centre, Deli devient l''un des trois centres du tabac à cigare indonésien — et sa feuille, la semence de Sumatra dont descendent jusqu''aux Connecticut.',
    `genese_en` = 'Jacobus Nienhuys, a Dutchman, obtained in 1863 a concession on Sumatra''s east coast, at Deli, around present-day Medan, and planted a first trial there: fifty bales of a tobacco whose quality surprised. An Indonesian publication says he brought the crop from East Java — the entry previously wrote a native seed never imported, and corrects itself. On 1 November 1869, with the Nederlandsche Handel-Maatschappij and two partners, he founded the Deli Maatschappij, which drew Dutch capital and brought Chinese labour from Singapore. With Besuki in East Java and Klaten in Central Java, Deli became one of the three centres of Indonesian cigar tobacco — and its leaf, the Sumatra seed from which even the Connecticuts descend.',
    `genese_es` = 'Jacobus Nienhuys, un neerlandés, obtiene en 1863 una concesión en la costa este de Sumatra, en Deli, en torno a la actual Medan, y planta allí un primer ensayo: cincuenta fardos de un tabaco cuya calidad sorprende. Una publicación indonesia dice que llevó el cultivo desde Java oriental — la ficha escribía antes una semilla nativa nunca importada, y se corrige. El 1 de noviembre de 1869, con la Nederlandsche Handel-Maatschappij y dos socios, funda la Deli Maatschappij, que atrae capitales neerlandeses y trae de Singapur mano de obra china. Con Besuki en Java Oriental y Klaten en Java Central, Deli se convierte en uno de los tres centros del tabaco de puro indonesio — y su hoja, en la semilla de Sumatra de la que descienden hasta los Connecticut.',
    `genese_de` = 'Jacobus Nienhuys, ein Niederländer, erhielt 1863 eine Konzession an der Ostküste Sumatras, in Deli, um das heutige Medan, und pflanzte dort einen ersten Versuch: fünfzig Ballen eines Tabaks, dessen Qualität überraschte. Eine indonesische Veröffentlichung sagt, er habe den Anbau aus Ostjava mitgebracht — der Eintrag schrieb zuvor einen nie importierten einheimischen Samen und korrigiert sich. Am 1. November 1869 gründete er mit der Nederlandsche Handel-Maatschappij und zwei Partnern die Deli Maatschappij, die niederländisches Kapital anzog und chinesische Arbeitskräfte aus Singapur holte. Mit Besuki in Ostjava und Klaten in Zentraljava wurde Deli eines der drei Zentren des indonesischen Zigarrentabaks — und sein Blatt zum Sumatra-Saatgut, von dem bis hin zu den Connecticuts alles abstammt.',
    `genese_zh` = '荷兰人雅各布斯·尼恩胡伊斯1863年在苏门答腊东海岸的德里——今棉兰一带——获得一块特许地，种下一批试验作物：五十包烟叶，品质令人惊讶。一份印尼出版物说他把这种作物从东爪哇带来——词条此前写的是从未引进的本地种子，予以更正。1869年11月1日，他与荷兰贸易公司及两位合伙人创立德里公司，吸引了荷兰资本，并从新加坡引入华工。与东爪哇的贝苏基和中爪哇的克拉登一起，德里成为印尼雪茄烟草的三大中心之一——它的叶子就是苏门答腊种，连康涅狄格烟叶都源自于此。',
    `genese_ar` = 'حصل الهولندي ياكوبوس نينهاوس سنة 1863 على امتياز على الساحل الشرقي لسومطرة، في ديلي حول ميدان الحالية، وزرع فيه تجربة أولى: خمسون بالة من تبغ أدهشت جودته. ويقول منشور إندونيسي إنّه جلب الزراعة من جاوة الشرقية — وكانت البطاقة تكتب من قبل بذرة محلية لم تُستورد قطّ، وتصحّح نفسها. وفي 1 نوفمبر 1869، مع شركة التجارة الهولندية وشريكين، أسّس شركة ديلي التي جذبت رؤوس الأموال الهولندية وجلبت من سنغافورة يدًا عاملة صينية. ومع بيسوكي في جاوة الشرقية وكلاتن في جاوة الوسطى، صارت ديلي أحد المراكز الثلاثة لتبغ السيجار الإندونيسي — وورقتها بذرة سومطرة التي تنحدر منها حتّى أوراق كونيكتيكت.',
    `culture` = 'Cultivée en plein soleil et destinée dès le départ à la cape, sur des terres que la Deli Maatschappij a mises en valeur avec une main-d''œuvre chinoise puis javanaise ; la publication qui a relu son histoire parle d''un patrimoine culturel autant que d''une culture.',
    `culture_en` = 'Sun-grown and meant for wrapper from the start, on land the Deli Maatschappij developed with Chinese and then Javanese labour; the publication that reread its history speaks of a cultural heritage as much as of a crop.',
    `culture_es` = 'Cultivada a pleno sol y destinada desde el principio a la capa, en tierras que la Deli Maatschappij puso en valor con mano de obra china y luego javanesa; la publicación que releyó su historia habla de un patrimonio cultural tanto como de un cultivo.',
    `culture_de` = 'Sonnenangebaut und von Anfang an fürs Deckblatt bestimmt, auf Land, das die Deli Maatschappij mit chinesischen und dann javanischen Arbeitskräften erschloss; die Veröffentlichung, die ihre Geschichte neu las, spricht von einem kulturellen Erbe ebenso wie von einer Kultur.',
    `culture_zh` = '全日照种植，从一开始就定为茄衣，土地由德里公司先用华工、后用爪哇工人开发；重读其历史的出版物既把它当作一种作物，也当作一项文化遗产。',
    `culture_ar` = 'تُزرع في الشمس الكاملة ومخصّصة منذ البداية للغلاف، على أراضٍ استصلحتها شركة ديلي بيد عاملة صينية ثمّ جاوية؛ ويتحدّث المنشور الذي أعاد قراءة تاريخها عن تراث ثقافي بقدر ما يتحدّث عن زراعة.' WHERE `id` = 'indonesie-deli';

-- ── indonesie-besuki ──
UPDATE `feuilles` SET `source` = 'ptmdr.co.id « Tobacco of Jember History » (George Birnie obtient en 1859 un droit d''emphytéose à Jenggawah, près de Jember, pour le Besuki Na Oogst ; la Landbouw Maatschappij Oud Djember ; les feuilles Na Oogst exportées vers Brême pour la cape) ; journal.unnes.ac.id, Wardhono, « The Quality Development of Besuki Na-Oogst Tobacco in Jember Regency » ; indonesia.travel (le musée du tabac de Jember) ; cigarinspector.com « Besuki » (Vroege Oogst et Na Oogst) ; tribunnews.com et umkm.kompas.com (le tabac de Jember chez Rizona et BIN Cigar, fiches du lot 11) — sources en anglais et en indonésien',
    `genese` = 'La région de Jember, à Java Est, est la plus réputée d''Indonésie pour le tabac, et son histoire a un nom et une date : George Birnie, qui obtient en 1859 un droit d''emphytéose à Jenggawah, près de Jember, pour y planter le Besuki Na Oogst, et fonde la Landbouw Maatschappij Oud Djember. La feuille porte le nom de la résidence de Besuki, héritée de l''administration coloniale ; ses meilleures récoltes partent pour Brême, où elles servent de cape.',
    `genese_en` = 'The Jember region, in East Java, is Indonesia''s most renowned for tobacco, and its history has a name and a date: George Birnie, who obtained in 1859 a long lease at Jenggawah, near Jember, to plant Besuki Na Oogst there, and founded the Landbouw Maatschappij Oud Djember. The leaf bears the name of the Besuki residency, inherited from the colonial administration; its best harvests leave for Bremen, where they serve as wrapper.',
    `genese_es` = 'La región de Jember, en Java Oriental, es la más reputada de Indonesia por el tabaco, y su historia tiene un nombre y una fecha: George Birnie, que obtiene en 1859 un derecho de enfiteusis en Jenggawah, cerca de Jember, para plantar el Besuki Na Oogst, y funda la Landbouw Maatschappij Oud Djember. La hoja lleva el nombre de la residencia de Besuki, heredada de la administración colonial; sus mejores cosechas parten hacia Bremen, donde sirven de capa.',
    `genese_de` = 'Die Region Jember in Ostjava ist die für Tabak bekannteste Indonesiens, und ihre Geschichte hat einen Namen und ein Datum: George Birnie, der 1859 ein Erbpachtrecht in Jenggawah bei Jember erhielt, um dort Besuki Na Oogst zu pflanzen, und die Landbouw Maatschappij Oud Djember gründete. Das Blatt trägt den Namen der Residentschaft Besuki, ererbt von der Kolonialverwaltung; seine besten Ernten gehen nach Bremen, wo sie als Deckblatt dienen.',
    `genese_zh` = '东爪哇的任抹地区是印尼烟草声望最高的产区，它的历史有名有姓、有年可考：乔治·伯尼1859年在任抹附近的曾加瓦获得长期租地权，种植贝苏基 Na Oogst，并创立了老任抹农业公司。烟叶的名字来自殖民政府留下的贝苏基驻扎区；它品质上乘的收成运往不来梅，用作茄衣。',
    `genese_ar` = 'منطقة جمبر في جاوة الشرقية هي الأرفع سمعة في إندونيسيا للتبغ، ولتاريخها اسم وتاريخ: جورج بيرني، الذي حصل سنة 1859 على حقّ استئجار طويل في جنغاواه قرب جمبر ليزرع فيها بيسوكي نا أوغست، وأسّس شركة Landbouw Maatschappij Oud Djember. وتحمل الورقة اسم إقامة بيسوكي الموروث من الإدارة الاستعمارية؛ وتذهب أجود محاصيلها إلى بريمن حيث تُستعمل غلافًا.' WHERE `id` = 'indonesie-besuki';

-- ── philippines-cagayan ──
UPDATE `feuilles` SET `source` = 'philstar.com « A hidden historical landmark echoes Philippine cigar » (2 juin 2014 : en 1592 le galion San Clemente apporte cinquante kilos de semences cubaines ; les frères les répandent avec la foi, et la vallée de Cagayan, province d''Isabela, leur convient ; la variété Isabela pousse encore dans le nord de la vallée ; La Flor de la Isabela établie en 1885 au 851 calle Isaac Peral, nommée d''après la variété) ; tabacalera.com.ph « Our History » (le monopole dissous en 1881, la Compañía General fondée la même année) ; en.wikipedia.org « Tobacco production in the Philippines » (le monopole de 1782 à 1881) ; tobaccoasia.com (4 mai 2016 : Isabela Leaf Tobacco, tabac sombre séché à l''air) — les souches « Cimaba » et « Viscaya », écrites auparavant dans cette fiche, ne viennent d''aucune source consultée : retirées',
    `genese` = 'La semence a suivi la foi : en 1592, dit la presse philippine, le galion San Clemente apporte cinquante kilos de semences cubaines, et ce sont les frères missionnaires qui les répandent dans l''archipel et trouvent qu''elles prospèrent dans la vallée de Cagayan, province d''Isabela. L''Espagne y tint un monopole du tabac de 1782 à son abolition en 1881 — l''année même où le marquis de Comillas fonde à Barcelone la compagnie qui lui succède, et dont la manufacture de Manille sera la première fabrique de cigares d''Asie.',
    `genese_en` = 'The seed followed the faith: in 1592, says the Philippine press, the galleon San Clemente brought fifty kilos of Cuban seed, and it was the missionary friars who spread it through the archipelago and found that it thrived in the Cagayan Valley, in the province of Isabela. Spain held a tobacco monopoly there from 1782 until its abolition in 1881 — the very year the Marquis of Comillas founded in Barcelona the company that succeeded it, whose Manila factory would be Asia''s first cigar factory.',
    `genese_es` = 'La semilla siguió a la fe: en 1592, dice la prensa filipina, el galeón San Clemente trae cincuenta kilos de semillas cubanas, y son los frailes misioneros quienes las esparcen por el archipiélago y encuentran que prosperan en el valle de Cagayán, provincia de Isabela. España mantuvo allí un monopolio del tabaco de 1782 a su abolición en 1881 — el mismo año en que el marqués de Comillas funda en Barcelona la compañía que lo sucede, cuya manufactura de Manila será la primera fábrica de puros de Asia.',
    `genese_de` = 'Der Samen folgte dem Glauben: 1592, sagt die philippinische Presse, brachte die Galeone San Clemente fünfzig Kilo kubanischen Samens, und es waren die Missionsbrüder, die ihn im Archipel verbreiteten und feststellten, dass er im Cagayan-Tal in der Provinz Isabela gedieh. Spanien hielt dort ein Tabakmonopol von 1782 bis zu seiner Abschaffung 1881 — im selben Jahr gründete der Marquis von Comillas in Barcelona die Gesellschaft, die ihm nachfolgte und deren Manufaktur in Manila Asiens erste Zigarrenfabrik werden sollte.',
    `genese_zh` = '种子跟随信仰而来：菲律宾媒体说，1592年圣克莱门特号大帆船带来五十公斤古巴种子，传教修士把它们传遍群岛，并发现它们在伊莎贝拉省的卡加延河谷长势最好。西班牙在那里从1782年起实行烟草专卖，直到1881年废除——同年，科米利亚斯侯爵在巴塞罗那创立接手的公司，其马尼拉工厂将成为亚洲首家雪茄厂。',
    `genese_ar` = 'تبعت البذرةُ الإيمانَ: سنة 1592، تقول الصحافة الفلبينية، جلب الغليون سان كليمنتي خمسين كيلوغرامًا من البذور الكوبية، والرهبان المبشّرون هم من نشروها في الأرخبيل ووجدوا أنّها تزدهر في وادي كاغايان بمقاطعة إيسابيلا. واحتكرت إسبانيا التبغ هناك من 1782 حتّى إلغاء الاحتكار سنة 1881 — السنة نفسها التي أسّس فيها ماركيز كوميّاس في برشلونة الشركة التي خلفته، والتي سيكون مصنعها في مانيلا أوّل مصنع سيجار في آسيا.',
    `caracteres` = 'Ce n''est pas un cultivar mais une souche locale, l''Isabela, qui a donné son nom à la maison La Flor de la Isabela : ici, la marque et la plante sont la même chose. La presse philippine note que le nom désigne aujourd''hui surtout un Burley de cigarette ; le tabac à cigare de la vallée est le sombre séché à l''air que l''industrie asiatique attribue à Isabela. L''atlas écrivait deux autres souches, Cimaba et Viscaya : aucune source ne les nomme, et il les retire.',
    `caracteres_en` = 'Not a cultivar but a local strain, Isabela, which gave its name to the house of La Flor de la Isabela: here, the brand and the plant are one and the same. The Philippine press notes that the name today mostly designates a cigarette Burley; the valley''s cigar tobacco is the dark air-cured that the Asian industry attributes to Isabela. This atlas wrote two other strains, Cimaba and Viscaya: no source names them, and it withdraws them.',
    `caracteres_es` = 'No es un cultivar sino una cepa local, la Isabela, que dio su nombre a la casa La Flor de la Isabela: aquí, la marca y la planta son lo mismo. La prensa filipina anota que el nombre designa hoy sobre todo un Burley de cigarrillo; el tabaco de puro del valle es el oscuro curado al aire que la industria asiática atribuye a Isabela. El atlas escribía otras dos cepas, Cimaba y Viscaya: ninguna fuente las nombra, y las retira.',
    `caracteres_de` = 'Kein Kultivar, sondern ein örtlicher Stamm, Isabela, der dem Haus La Flor de la Isabela seinen Namen gab: Hier sind Marke und Pflanze dasselbe. Die philippinische Presse vermerkt, dass der Name heute vor allem einen Zigaretten-Burley bezeichnet; der Zigarrentabak des Tals ist der dunkle luftgetrocknete, den die asiatische Industrie Isabela zuschreibt. Dieser Atlas schrieb zwei weitere Stämme, Cimaba und Viscaya: Keine Quelle nennt sie, und er zieht sie zurück.',
    `caracteres_zh` = '它不是一个栽培品种，而是一个本地品系——伊莎贝拉，它把名字给了 La Flor de la Isabela 公司：在这里，品牌和植物是同一回事。菲律宾媒体指出，这个名字如今主要指一种卷烟用白肋烟；河谷的雪茄烟草是亚洲业界归于伊莎贝拉的深色晾制烟。本图集原先还写了两个品系 Cimaba 和 Viscaya：没有来源提到它们，予以撤回。',
    `caracteres_ar` = 'ليست صنفًا مستنبتًا بل سلالة محلية هي إيسابيلا، التي أعطت اسمها لدار La Flor de la Isabela: هنا العلامة والنبتة شيء واحد. وتلاحظ الصحافة الفلبينية أنّ الاسم يدلّ اليوم في المقام الأوّل على بيرلي للسجائر؛ أمّا تبغ السيجار في الوادي فهو الداكن المجفّف بالهواء الذي تنسبه الصناعة الآسيوية إلى إيسابيلا. وكان هذا الأطلس يكتب سلالتين أخريين، Cimaba وViscaya: لا يسمّيهما مصدر، ويسحبهما.' WHERE `id` = 'philippines-cagayan';

-- ── cote-d-ivoire-tiebissou ──
UPDATE `feuilles` SET `source` = 'lefagot.com (la maison attribue la cape du Fagot au département de Tiébissou — affirmation de la maison, la même source que la fiche Le Fagot Cigar) ; fr.wikipedia.org « Bélier (région) » (climat baouléen, deux saisons des pluies, 1 000 à 1 400 mm ; sols ferrallitiques sur granite) — aucune documentation agricole du tabac dans le Bélier n''a été trouvée ; la fiche n''a ni caractères ni notes, et c''est voulu' WHERE `id` = 'cote-d-ivoire-tiebissou';

-- ── cote-d-ivoire-didievi ──
UPDATE `feuilles` SET `source` = 'lefagot.com (la maison attribue la sous-cape et la tripe du Fagot au département de Didiévi — affirmation de la maison) ; fr.wikipedia.org « Bélier (région) » (climat et sols de la région) — aucune documentation agricole du tabac n''a été trouvée ; la fiche n''a ni caractères ni notes, et c''est voulu' WHERE `id` = 'cote-d-ivoire-didievi';


INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'feuilles', f.`id`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'genese' THEN f.`genese` WHEN 'culture' THEN f.`culture` ELSE f.`caracteres` END), 'machine', NOW()
  FROM `feuilles` f
  JOIN (SELECT 'genese' champ UNION ALL SELECT 'culture' UNION ALL SELECT 'caracteres') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE f.`id` IN ('cameroun-cape','canaries-la-palma','italie-kentucky','indonesie-deli','indonesie-besuki','philippines-cagayan','cote-d-ivoire-tiebissou','cote-d-ivoire-didievi') AND (c.champ <> 'caracteres' OR f.`caracteres` IS NOT NULL)
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 231';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 231','systeme','trente_deux_feuilles_sourcees','systeme',0,
   'Cameroun, La Palma, Kentucky, Deli, Besuki, Cagayan, Tiebissou, Didievi : les huit dernieres feuilles recoivent leur source. Les 32 en ont une. Le sixieme recensement est clos'),
  (NULL,'migration 231','systeme','cinq_feuilles_corrigees','systeme',0,
   'Deli : « semence native jamais importee » etait faux — Nienhuys apporta la culture depuis Java en 1863. Cagayan : les souches Cimaba et Viscaya ne venaient de nulle part, retirees. Cameroun : colons neerlandais (detaillants) ou SEITA et Masseron fin des annees 1950 (presse) — les deux ecrits. Besuki : Birnie, 1859. Kentucky : le sechage au feu precise');

SELECT
  (SELECT COUNT(*) FROM `feuilles` WHERE `source` IS NOT NULL AND `source` <> '') = 32 AS toutes_sourcees,
  (SELECT `genese` LIKE '%Nienhuys%' FROM `feuilles` WHERE `id` = 'indonesie-deli') AS deli_nienhuys,
  (SELECT `caracteres` NOT LIKE '%Cimaba%' OR `caracteres` LIKE '%retire%' FROM `feuilles` WHERE `id` = 'philippines-cagayan') AS cagayan_sans_souches_orphelines,
  (SELECT `genese_ar` LIKE '%1593%' OR `genese_ar` LIKE '%1592%' FROM `feuilles` WHERE `id` = 'philippines-cagayan') AS cagayan_ar,
  (SELECT `caracteres` IS NULL FROM `feuilles` WHERE `id` = 'cote-d-ivoire-didievi') AS didievi_sans_caracteres_voulu;
SELECT COUNT(*) AS feuilles, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `feuilles`;
