-- ════════════════════════════════════════════════════════
-- 249 — Huitième recensement : Malekö et Skull 77, deux marques du
--       Costa Rica (lot d'écriture 28)
-- ────────────────────────────────────────────────────────
-- D'OÙ ELLES VIENNENT. Du réexamen du groupe de Puriscal : six marques
-- roulées au Costa Rica, que les lots précédents avaient lues de façons
-- contradictoires, relues ensemble par un contradicteur.
--   Costa Rica        Malekö et Skull 77, roulées chez Tabacos de
--                     Costa Rica S.A., à Santiago de Puriscal
--
-- ── CE QUE LE RÉEXAMEN A ÉTABLI ─────────────────────────────────
-- Tabacos de Costa Rica S.A. est l'atelier que la fiche Vegas de
-- Santiago de l'atlas range sous ce nom : Casdagli écrit en 2021
-- « alors connue sous le nom de Vegas Santiago ». Mais il appartient à
-- la famille León Guzmán (La Nación en 2011, Cigar Coop en 2019 et
-- 2020), pas à Marc Niehaus : la fiche Vegas de Santiago, qui le lui
-- attribue, reste à corriger. Malekö et Skull 77 ne sont donc pas des
-- lignes de Vegas de Santiago : Malekö a son titulaire (Tabacos de
-- Costa Rica, lu sur Trademarkia), Skull 77 son propriétaire, Laurent
-- Taha.
--
-- ── CE QUI RESTE DEHORS ─────────────────────────────────────────
-- La Flor de Montenegro, bâtie sur Malekö, dont la main n'est écrite
-- nulle part (tripe Mediumfiller seule) ; Dominus, arrêtée, son stock
-- racheté par Cigarworld.de au printemps 2023 ; La Bavaria, arrêtée en
-- 2021 ; Kaneda, sans fabricant prouvé.
--
-- ── CE QUE LA RELECTURE A TRANCHÉ ───────────────────────────────
-- Skull 77 vit : en octobre 2026, deux détaillants suisses la vendent,
-- alors que le contradicteur n'en avait trouvé aucune trace datée de
-- 2025 ou 2026. La nationalité de Laurent Taha, que le tri disait
-- suisse, n'est écrite que si une page lue la donne : aucune ne la
-- donne. Les forces « sur 5 » et « sur 8 » sont dites pour ce qu'elles
-- sont, des niveaux d'échelles de force de détaillants.
--
-- ── DIVERGENCES ÉCRITES ─────────────────────────────────
-- Taha ou Tahla ; Tabacos de Costa Rica dite ancien nom de Vegas
-- Santiago par Casdagli alors que Casagranda les range sous deux
-- rubriques ; première utilisation de Malekö déclarée en 2016 au
-- registre américain, Custom Blend lancée en 2015 selon Casagranda ;
-- forces de Malekö selon Casagranda ou Tabakfreund.de ; cape de Skull
-- 77, colorado ou colorado maduro.
--
-- Rejouable : INSERT … ON DUPLICATE KEY UPDATE ; le `brands` des pays
-- touchés est relu en base et réécrit en littéral ; sceaux `machine`.
-- ════════════════════════════════════════════════════════

-- ── Malekö ──
INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `mentions`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Malekö',
        'costarica',
        'Non précisée — Tabacos de Costa Rica, Puriscal',
        'Chez Tabacos de Costa Rica S.A., Santiago de Puriscal (Costa Rica)',
        'smokersplanet.de « ''Malekö Custom Blend'' aus Costa Rica würdigen indigene Tabakkultur » (26 août 2025, article de détaillant en allemand : Malekö inspirée du peuple maleku ; Classic à succès au Moyen-Orient, surtout au Liban ; Custom Blend en 2015 avec cape rougeâtre, vitolas nouvelles et formes modernes ; cape Équateur H2000 Rosado, sous-cape Équateur H2000, tripe Pérou et Brésil ; Robusto 12,70 cm × 50, Wide Churchill 13,97 cm × 56, Emperator 15,24 cm × 60 ; distribution par Casagranda) ; casagranda-cigars.de « MALEKÖ » (octobre 2026, © 2026 Casagranda Cigars GmbH, pages allemande et anglaise : Malekö inspirée du peuple maleku ; Custom Blend lancée en 2015 après le succès de la Classic au Moyen-Orient, surtout au Liban ; cigares de la région de Puriscal ; Robusto 12,7 cm × 50, Wide Churchill 14 cm × 56, Emperador 15,2 cm × 60 ; cape Équateur H2000 Rosado, sous-cape Équateur H2000, tripe Pérou et Brésil ; force mittelkräftig sur la page allemande, medium-strong sur la page anglaise ; coffret de bois laqué ; Malekö rangée sous la rubrique Tabacos de Costa Rica) ; casagranda-cigars.de « TABACOS DE COSTA RICA » (octobre 2026 : manufacture familiale établie en 1997 dans la région montagneuse de Puriscal ; rubrique qui range Malekö) ; cigarworld.de « Malekö Custom Blend Emperador » (octobre 2026, © 2026 Tabac Benden GmbH : fabricant Tabacos de Costa Rica S.A., importateur Casagranda Cigars GmbH à Esslingen, Totalmente a mano en longfiller, Emperador 6 pouces × 60, au catalogue depuis le 11 août 2025) ; tabakfreund.de « Malekö Robusto Custom Blend » (© 2025 : Totalmente a Mano en longfiller ; cape Équateur H2000 Rosado, sous-cape Équateur H2000, tripe Pérou et Brésil ; force mittelkräftig, 3 sur 5 ; Robusto 127 mm × 50 ; Casagranda Cigars GmbH inscrite à la ligne fabricant) ; trademarkia.com « MALEKÖ Trademark » (octobre 2026, n° de série 88981460 : titulaire Tabacos de Costa Rica, S.A., adresse à Santiago, Puriscal, San José ; dépôt le 25 mars 2020, enregistrement n° 6451601 le 17 août 2021, classe 34 ; première utilisation déclarée le 27 juillet 2016) ; cigar-coop.com « Feature Story: Costa Rica In My Mind''s Eye » (17 mai 2019 : Andrés León, propriétaire et exploitant de Tabacos de Costa Rica ; fabrique à Santiago de Puriscal) ; casdaglicigars.com « Casdagli Cigars launches the Villa Casdagli line at TPE » (page non datée, ligne annoncée pour juin 2021 : coopération de Casdagli avec Tabacos de Costa Rica SA, alors connue sous le nom de Vegas Santiago, depuis 2012)',
        NULL,
        'Malekö est une marque costaricienne dont le nom rend hommage au peuple maleku, groupe autochtone des forêts tropicales du Costa Rica, dit Casagranda. Sa première ligne, Malekö Classic, a connu le succès au Moyen-Orient, surtout au Liban ; la Custom Blend lui succède en 2015, avec une cape rougeâtre, des vitolas nouvelles et des formes modernes, disent Casagranda et Smokersplanet.de.

Le titulaire de la marque est Tabacos de Costa Rica, S.A., dont l''adresse est à Santiago de Puriscal : le registre américain des marques, d''après Trademarkia, y consigne un dépôt le 25 mars 2020, un enregistrement le 17 août 2021 et une première utilisation déclarée le 27 juillet 2016. Cigarworld.de nomme la même société comme fabricant, et Casagranda range Malekö sous sa rubrique Tabacos de Costa Rica, qu''elle dit manufacture familiale établie en 1997 dans la région montagneuse de Puriscal. Cigar Coop nomme en 2019 Andrés León propriétaire et exploitant de la fabrique de Tabacos de Costa Rica, à Santiago de Puriscal ; Casdagli écrit que sa coopération avec Tabacos de Costa Rica SA, alors connue sous le nom de Vegas Santiago, a commencé en 2012.

En octobre 2026, Casagranda présente la Custom Blend en trois vitolas, en coffrets de bois laqué, et Cigarworld.de, qui nomme Casagranda Cigars GmbH, à Esslingen, comme importateur, la tient au catalogue, roulée Totalmente a mano en longfiller : l''Emperador y figure depuis le 11 août 2025. Smokersplanet.de lui consacre un article le 26 août 2025.',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"Équateur H2000 Rosado","vitolas":[],"story":"Cape Équateur H2000 Rosado, sous-cape Équateur H2000, tripe du Pérou et du Brésil, roulée Totalmente a mano en longfiller, en trois vitolas, Robusto (12,7 cm × 50), Wide Churchill (14 cm × 56) et Emperador (15,2 cm × 60), en coffrets de bois laqué ; force moyenne à soutenue, écrite mittelkräftig sur la page allemande de Casagranda et medium-strong sur sa page anglaise, et de niveau 3 sur 5 sur l''échelle de force de Tabakfreund.de ; lancée en 2015 après la Classic, dit Casagranda."}]',
        'Malekö is a Costa Rican brand whose name pays tribute to the Maleku people, an indigenous group of the tropical forests of Costa Rica, says Casagranda. Its first line, Malekö Classic, enjoyed success in the Middle East, particularly in Lebanon; the Custom Blend succeeded it in 2015, with a reddish wrapper, new vitolas and modern shapes, say Casagranda and Smokersplanet.de.

The holder of the trademark is Tabacos de Costa Rica, S.A., whose address is in Santiago de Puriscal: the American trademark register, according to Trademarkia, records a filing there on 25 March 2020, a registration on 17 August 2021 and a declared first use on 27 July 2016. Cigarworld.de names the same company as manufacturer, and Casagranda files Malekö under its Tabacos de Costa Rica heading, which it describes as a family factory established in 1997 in the mountainous region of Puriscal. Cigar Coop names Andrés León in 2019 as owner and operator of the Tabacos de Costa Rica factory, in Santiago de Puriscal; Casdagli writes that its cooperation with Tabacos de Costa Rica SA, then known as Vegas Santiago, began in 2012.

In October 2026, Casagranda presents the Custom Blend in three vitolas, in lacquered wooden boxes, and Cigarworld.de, which names Casagranda Cigars GmbH, in Esslingen, as importer, lists it in its catalogue, rolled Totalmente a mano in longfiller: the Emperador has appeared there since 11 August 2025. Smokersplanet.de devotes an article to it on 26 August 2025.',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"Ecuador H2000 Rosado","vitolas":[],"story":"Ecuadorian H2000 Rosado wrapper, Ecuadorian H2000 binder, Peruvian and Brazilian filler, rolled Totalmente a mano in longfiller, in three vitolas, Robusto (12.7 cm × 50), Wide Churchill (14 cm × 56) and Emperador (15.2 cm × 60), in lacquered wooden boxes; strength medium to medium-full, written mittelkräftig on Casagranda’s German page and medium-strong on its English page, and level 3 of 5 on Tabakfreund.de’s strength scale; launched in 2015 after the Classic, says Casagranda."}]',
        'Malekö es una marca costarricense cuyo nombre rinde homenaje al pueblo maleku, grupo indígena de los bosques tropicales de Costa Rica, dice Casagranda. Su primera línea, Malekö Classic, tuvo éxito en Oriente Medio, sobre todo en el Líbano; la Custom Blend le sucede en 2015, con una capa rojiza, vitolas nuevas y formas modernas, dicen Casagranda y Smokersplanet.de.

El titular de la marca es Tabacos de Costa Rica, S.A., cuya dirección está en Santiago de Puriscal: el registro estadounidense de marcas, según Trademarkia, consigna allí una solicitud el 25 de marzo de 2020, un registro el 17 de agosto de 2021 y un primer uso declarado el 27 de julio de 2016. Cigarworld.de nombra a la misma sociedad como fabricante, y Casagranda clasifica Malekö en su sección Tabacos de Costa Rica, que describe como una fábrica familiar establecida en 1997 en la región montañosa de Puriscal. Cigar Coop nombra en 2019 a Andrés León propietario y operador de la fábrica de Tabacos de Costa Rica, en Santiago de Puriscal; Casdagli escribe que su cooperación con Tabacos de Costa Rica SA, entonces conocida como Vegas Santiago, comenzó en 2012.

En octubre de 2026, Casagranda presenta la Custom Blend en tres vitolas, en cofres de madera lacada, y Cigarworld.de, que nombra a Casagranda Cigars GmbH, en Esslingen, como importador, la tiene en catálogo, torcida Totalmente a mano en longfiller: el Emperador figura allí desde el 11 de agosto de 2025. Smokersplanet.de le dedica un artículo el 26 de agosto de 2025.',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"Ecuador H2000 Rosado","vitolas":[],"story":"Capa de Ecuador H2000 Rosado, capote de Ecuador H2000, tripa de Perú y de Brasil, torcida Totalmente a mano en longfiller, en tres vitolas, Robusto (12,7 cm × 50), Wide Churchill (14 cm × 56) y Emperador (15,2 cm × 60), en cofres de madera lacada; fuerza de media a media-alta, escrita mittelkräftig en la página alemana de Casagranda y medium-strong en su página inglesa, y de nivel 3 sobre 5 en la escala de fuerza de Tabakfreund.de; lanzada en 2015 tras la Classic, dice Casagranda."}]',
        'Malekö ist eine costa-ricanische Marke, deren Name das Volk der Maleku ehrt, eine indigene Gruppe der tropischen Wälder Costa Ricas, sagt Casagranda. Ihre erste Linie, Malekö Classic, war im Nahen Osten erfolgreich, besonders im Libanon; die Custom Blend folgt ihr 2015 nach, mit einem rötlichen Deckblatt, neuen Vitolas und modernen Formen, sagen Casagranda und Smokersplanet.de.

Inhaberin der Marke ist Tabacos de Costa Rica, S.A., deren Adresse in Santiago de Puriscal liegt: Das US-amerikanische Markenregister verzeichnet dort laut Trademarkia eine Anmeldung am 25. März 2020, eine Eintragung am 17. August 2021 und eine erklärte Erstbenutzung am 27. Juli 2016. Cigarworld.de nennt dieselbe Gesellschaft als Hersteller, und Casagranda ordnet Malekö unter ihrer Rubrik Tabacos de Costa Rica ein, die sie als familiäre Fabrik bezeichnet, 1997 in der Bergregion Puriscal gegründet. Cigar Coop nennt 2019 Andrés León als Eigentümer und Betreiber der Fabrik von Tabacos de Costa Rica in Santiago de Puriscal; Casdagli schreibt, dass seine Zusammenarbeit mit Tabacos de Costa Rica SA, damals unter dem Namen Vegas Santiago bekannt, 2012 begonnen hat.

Im Oktober 2026 präsentiert Casagranda die Custom Blend in drei Vitolas, in Kassetten aus lackiertem Holz, und Cigarworld.de, wo Casagranda Cigars GmbH in Esslingen als Importeur genannt wird, führt sie im Katalog, gerollt Totalmente a mano in longfiller: Die Emperador ist dort seit dem 11. August 2025 verzeichnet. Smokersplanet.de widmet ihr am 26. August 2025 einen Artikel.',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"Ecuador H2000 Rosado","vitolas":[],"story":"Deckblatt Ecuador H2000 Rosado, Umblatt Ecuador H2000, Einlage aus Peru und Brasilien, gerollt Totalmente a mano in longfiller, in drei Vitolas, Robusto (12,7 cm × 50), Wide Churchill (14 cm × 56) und Emperador (15,2 cm × 60), in Kassetten aus lackiertem Holz; Stärke mittel bis kräftig, auf der deutschen Seite von Casagranda als mittelkräftig, auf der englischen als medium-strong angegeben und auf der Stärkeskala von Tabakfreund.de bei Stufe 3 von 5; 2015 nach der Classic eingeführt, sagt Casagranda."}]',
        'Malekö 是一个哥斯达黎加品牌，据 Casagranda 称，其名称是向马莱库（Maleku）人致敬，马莱库人是哥斯达黎加热带森林中的原住民群体。其首条产品线 Malekö Classic 曾在中东取得成功，尤其是在黎巴嫩；据 Casagranda 和 Smokersplanet.de 称，Custom Blend 于2015年接替它，采用泛红的茄衣、新的茄型和现代的造型。

该品牌的持有人是 Tabacos de Costa Rica S.A.，其地址在 Santiago de Puriscal：据 Trademarkia，美国商标注册簿在此记录了2020年三月25日的申请、2021年八月17日的注册，以及2016年七月27日申报的首次使用。Cigarworld.de 将同一家公司列为制造商，Casagranda 把 Malekö 归入其 Tabacos de Costa Rica 栏目，并称其为1997年在 Puriscal 山区设立的家族式工厂。Cigar Coop 于2019年称 Andrés León 为 Tabacos de Costa Rica 位于 Santiago de Puriscal 的工厂的所有者和经营者；Casdagli 写道，其与 Tabacos de Costa Rica SA（当时被称为 Vegas Santiago）的合作始于2012年。

2026年十月，Casagranda 介绍 Custom Blend 有三种茄型，以漆木盒包装；Cigarworld.de 将位于 Esslingen 的 Casagranda Cigars GmbH 列为进口商，并将其列入目录，以 Totalmente a mano 方式、用 longfiller 卷制：Emperador 自2025年八月11日起列于目录。Smokersplanet.de 于2025年八月26日发表了一篇专门介绍它的文章。',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"厄瓜多尔 H2000 Rosado","vitolas":[],"story":"茄衣为厄瓜多尔 H2000 Rosado，茄套为厄瓜多尔 H2000，茄芯来自秘鲁和巴西，以 Totalmente a mano 方式、用 longfiller 卷制，共三种茄型：Robusto（12.7 cm × 50）、Wide Churchill（14 cm × 56）和 Emperador（15.2 cm × 60），以漆木盒包装；力度由中等至中上，Casagranda 德语页面上写作 mittelkräftig，其英语页面上写作 medium-strong，在 Tabakfreund.de 的力度量表上为5级中的3级；据 Casagranda 称，于2015年在 Classic 之后推出。"}]',
        'Malekö علامة كوستاريكية يُكرّم اسمها شعب ماليكو (Maleku)، وهو مجموعة من السكان الأصليين لغابات كوستاريكا المدارية، كما تقول Casagranda. وقد حقق خطها الأول، Malekö Classic، نجاحًا في الشرق الأوسط، ولا سيما في لبنان؛ وتخلفه Custom Blend في عام 2015، بغلاف خارجي مائل إلى الحمرة ومقاسات جديدة وأشكال حديثة، كما تقول Casagranda و Smokersplanet.de.

صاحبة العلامة هي Tabacos de Costa Rica S.A.، وعنوانها في Santiago de Puriscal: وبحسب Trademarkia، يسجّل السجل الأمريكي للعلامات التجارية هناك إيداعًا في 25 مارس 2020، وتسجيلًا في 17 أغسطس 2021، وأول استخدام مُصرَّح به في 27 يوليو 2016. ويذكر Cigarworld.de الشركة نفسها بوصفها الجهة المصنِّعة، وتصنّف Casagranda علامة Malekö تحت قسم Tabacos de Costa Rica الخاص بها، وتصفه بأنه مصنع عائلي أُسّس عام 1997 في منطقة Puriscal الجبلية. ويسمّي Cigar Coop في عام 2019 Andrés León مالكًا ومشغّلًا لمصنع Tabacos de Costa Rica في Santiago de Puriscal؛ وتكتب Casdagli أن تعاونها مع Tabacos de Costa Rica SA، التي كانت تُعرف حينها باسم Vegas Santiago، بدأ في عام 2012.

في أكتوبر 2026، تعرض Casagranda تشكيلة Custom Blend في ثلاثة مقاسات وفي علب من الخشب المطلي بالورنيش؛ أما Cigarworld.de، الذي يسمّي Casagranda Cigars GmbH في Esslingen مستوردًا، فيُدرجها في كتالوجه، ملفوفة Totalmente a mano باستخدام longfiller، ويظهر فيه Emperador منذ 11 أغسطس 2025. ويخصص Smokersplanet.de لها مقالًا في 26 أغسطس 2025.',
        '[{"name":"Custom Blend","color":"#A0522D","force":"Medium","wrapper":"الإكوادور H2000 Rosado","vitolas":[],"story":"الغلاف الخارجي H2000 Rosado من الإكوادور، والغلاف الداخلي H2000 من الإكوادور، والحشوة من بيرو والبرازيل، ملفوفة Totalmente a mano باستخدام longfiller، في ثلاثة مقاسات: Robusto (12.7 cm × 50) و Wide Churchill (14 cm × 56) و Emperador (15.2 cm × 60)، في علب من الخشب المطلي بالورنيش؛ قوتها من المتوسطة إلى المرتفعة، وهي مكتوبة mittelkräftig في صفحة Casagranda الألمانية و medium-strong في صفحتها الإنجليزية، وبمستوى 3 من 5 على مقياس القوة لدى Tabakfreund.de؛ أُطلقت في عام 2015 بعد Classic، كما تقول Casagranda."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `mentions` = VALUES(`mentions`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── Skull 77 ──
INSERT INTO `brands` (`name`, `country_id`, `founded`, `factory`, `source`, `mentions`, `history`, `gamme`, `history_en`, `gamme_en`, `history_es`, `gamme_es`, `history_de`, `gamme_de`, `history_zh`, `gamme_zh`, `history_ar`, `gamme_ar`)
VALUES ('Skull 77',
        'costarica',
        '2014 — Laurent Taha',
        'Chez Tabacos de Costa Rica S.A., Santiago de Puriscal (Costa Rica)',
        'zigarrenversand.ch « Skull 77 Zigarren » (octobre 2026, détaillant suisse en allemand, © zigarrenversand.ch gmbh : Laurent Taha présenté comme l''homme derrière Skull 77 ; marque fondée le 7.7.2014, d''où le 77 ; quatre vitolas, El Volcano 158 mm, El Unico 140 mm, El Nino 83 mm et El Diablo 152 mm, roulées à la main, force 3 sur 5, cape Colorado Maduro ; fabrique Vegas de Santiago, au Costa Rica ; stock en octobre 2026 : El Volcano 19, El Nino 10, El Diablo 12, El Unico épuisé) ; rauchr.de « Skull 77 Zigarren Unicos » (octobre 2026 : fabricant Tabacos de Costa Rica S.A., importateur Casagranda Cigars GmbH à Esslingen ; Totalmente a mano en longfiller ; cape Équateur H-2000 Colorado, sous-cape Équateur, tripe République dominicaine, Nicaragua et Pérou ; 5,5 pouces × 58 ; au catalogue depuis le 27.06.2018 ; article en fin de série, treize pièces en stock, boîte de quinze épuisée ; texte : Laurent Tahla, plus de vingt ans de cigares, rencontre en 2014 lors d''une dégustation Marc Niehaus, propriétaire de Vegas de Santiago Cigars, et met au point le mélange avec un blendmaster dans une fabrique de cigares premium du Costa Rica) ; cigarworld.de « Skull 77 Zigarren Unicos » (octobre 2026, © 2026 Tabac Benden GmbH : fabricant Tabacalera Tabacos de Costa Rica S.A., importateur Casagranda Cigars GmbH, origine Costa Rica ; force 4 sur 8, aromatique, mild-würzig ; au catalogue depuis le 27.06.2018 ; article en fin de série, treize pièces) ; zigarrenwelt.de « Skull 77 Zigarren Ninos » (octobre 2026, © 2026 Tabac Benden GmbH : Niños 3,25 pouces × 58, Totalmente a mano en longfiller, au catalogue depuis le 20.12.2019, article en fin de série) ; humidor.ch « Zigarren Costa Rica Skull 77 » (octobre 2026, © 2026, détaillant suisse : El Nino, El Unico et El Volcano disponibles, El Diablo non disponible) ; cigar-coop.com « Feature Story: Costa Rica In My Mind''s Eye » (17 mai 2019 : fabrique de Tabacos de Costa Rica à Santiago de Puriscal, Andrés León propriétaire et exploitant) ; casdaglicigars.com « Casdagli Cigars launches the Villa Casdagli line at TPE » (page non datée, ligne annoncée pour juin 2021 : coopération de Casdagli avec Tabacos de Costa Rica SA, alors connue sous le nom de Vegas Santiago, depuis 2012)',
        NULL,
        'Skull 77 est une marque de Laurent Taha, que Zigarrenversand.ch présente comme l''homme derrière elle et dont rauchr.de écrit le nom Tahla. Zigarrenversand.ch la dit fondée le 7 juillet 2014, date dont vient le 77. Selon rauchr.de, Tahla, qui s''occupe de cigares et de goût depuis plus de vingt ans, rencontre en 2014, lors d''une dégustation, Marc Niehaus, qu''il présente comme le propriétaire de Vegas de Santiago Cigars ; les deux deviennent amis et mettent au point le mélange avec un blendmaster dans une fabrique de cigares premium du Costa Rica.

Cigarworld.de et rauchr.de donnent Tabacos de Costa Rica S.A. pour fabricant et Casagranda Cigars GmbH, à Esslingen, pour importateur ; Zigarrenversand.ch parle de la fabrique Vegas de Santiago, au Costa Rica. Casdagli écrit que sa coopération avec Tabacos de Costa Rica SA, alors connue sous le nom de Vegas Santiago, a commencé en 2012 ; Cigar Coop place la fabrique de Tabacos de Costa Rica à Santiago de Puriscal.

La marque compte quatre vitolas, roulées à la main en longfiller, à cape H-2000 d''Équateur. En octobre 2026, Zigarrenversand.ch et Humidor.ch les tiennent au catalogue, tandis que Cigarworld.de et rauchr.de gardent les Unicos, au catalogue depuis le 27 juin 2018, en article en fin de série, avec treize pièces en stock ; Zigarrenwelt.de signale de même les Niños, au catalogue depuis le 20 décembre 2019.',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"Équateur H-2000","vitolas":[],"story":"Cape H-2000 d''Équateur, colorado selon Cigarworld.de et rauchr.de, colorado maduro selon Zigarrenversand.ch, sous-cape d''Équateur, tripe de République dominicaine, du Nicaragua et du Pérou, roulée à la main en longfiller, en quatre vitolas, El Niño (83 mm × 58), El Unico (140 mm × 58), El Diablo (152 mm) et El Volcano (belicoso de 158 mm) ; force de niveau 4 sur 8 sur l''échelle de Cigarworld.de et de niveau 3 sur 5 sur celle de Zigarrenversand.ch."}]',
        'Skull 77 is a brand of Laurent Taha, whom Zigarrenversand.ch presents as the man behind it and whose name rauchr.de writes Tahla. Zigarrenversand.ch says it was founded on 7 July 2014, the date from which the 77 comes. According to rauchr.de, Tahla, who has been involved with cigars and taste for more than twenty years, meets, at a tasting in 2014, Marc Niehaus, whom he presents as the owner of Vegas de Santiago Cigars; the two become friends and develop the blend with a blendmaster in a premium cigar factory in Costa Rica.

Cigarworld.de and rauchr.de give Tabacos de Costa Rica S.A. as manufacturer and Casagranda Cigars GmbH, in Esslingen, as importer; Zigarrenversand.ch speaks of the Vegas de Santiago factory, in Costa Rica. Casdagli writes that its cooperation with Tabacos de Costa Rica SA, then known as Vegas Santiago, began in 2012; Cigar Coop places the Tabacos de Costa Rica factory in Santiago de Puriscal.

The brand has four vitolas, rolled by hand in longfiller, with an Ecuadorian H-2000 wrapper. In October 2026, Zigarrenversand.ch and Humidor.ch carry them in their catalogues, whereas Cigarworld.de and rauchr.de keep the Unicos, listed since 27 June 2018, as end-of-line items, with thirteen pieces in stock; Zigarrenwelt.de likewise flags the Niños, listed since 20 December 2019.',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"Ecuador H-2000","vitolas":[],"story":"H-2000 wrapper from Ecuador, colorado according to Cigarworld.de and rauchr.de, colorado maduro according to Zigarrenversand.ch, Ecuadorian binder, filler from the Dominican Republic, Nicaragua and Peru, rolled by hand in longfiller, in four vitolas, El Niño (83 mm × 58), El Unico (140 mm × 58), El Diablo (152 mm) and El Volcano (belicoso of 158 mm); strength level 4 of 8 on the Cigarworld.de scale and level 3 of 5 on that of Zigarrenversand.ch."}]',
        'Skull 77 es una marca de Laurent Taha, a quien Zigarrenversand.ch presenta como el hombre que está detrás de ella y cuyo nombre rauchr.de escribe Tahla. Zigarrenversand.ch dice que fue fundada el 7 de julio de 2014, fecha de la que procede el 77. Según rauchr.de, Tahla, que se dedica a los puros y al gusto desde hace más de veinte años, conoce en 2014, durante una cata, a Marc Niehaus, a quien presenta como el propietario de Vegas de Santiago Cigars; los dos se hacen amigos y ponen a punto la mezcla con un blendmaster en una fábrica de puros premium de Costa Rica.

Cigarworld.de y rauchr.de dan a Tabacos de Costa Rica S.A. como fabricante y a Casagranda Cigars GmbH, en Esslingen, como importador; Zigarrenversand.ch habla de la fábrica Vegas de Santiago, en Costa Rica. Casdagli escribe que su cooperación con Tabacos de Costa Rica SA, entonces conocida como Vegas Santiago, comenzó en 2012; Cigar Coop sitúa la fábrica de Tabacos de Costa Rica en Santiago de Puriscal.

La marca cuenta con cuatro vitolas, torcidas a mano en longfiller, con capa H-2000 de Ecuador. En octubre de 2026, Zigarrenversand.ch y Humidor.ch las tienen en catálogo, mientras que Cigarworld.de y rauchr.de conservan las Unicos, en catálogo desde el 27 de junio de 2018, como artículo de fin de serie, con trece piezas en stock; Zigarrenwelt.de señala igualmente las Niños, en catálogo desde el 20 de diciembre de 2019.',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"Ecuador H-2000","vitolas":[],"story":"Capa H-2000 de Ecuador, colorado según Cigarworld.de y rauchr.de, colorado maduro según Zigarrenversand.ch, capote de Ecuador, tripa de la República Dominicana, de Nicaragua y de Perú, torcida a mano en longfiller, en cuatro vitolas, El Niño (83 mm × 58), El Unico (140 mm × 58), El Diablo (152 mm) y El Volcano (belicoso de 158 mm); fuerza de nivel 4 sobre 8 en la escala de Cigarworld.de y de nivel 3 sobre 5 en la de Zigarrenversand.ch."}]',
        'Skull 77 ist eine Marke von Laurent Taha, den Zigarrenversand.ch als den Mann hinter ihr vorstellt und dessen Namen rauchr.de Tahla schreibt. Zigarrenversand.ch sagt, sie sei am 7. Juli 2014 gegründet worden, dem Datum, von dem die 77 stammt. Laut rauchr.de trifft Tahla, der sich seit mehr als zwanzig Jahren mit Zigarren und Geschmack beschäftigt, 2014 bei einer Verkostung Marc Niehaus, den er als Inhaber von Vegas de Santiago Cigars vorstellt; die beiden werden Freunde und entwickeln die Mischung mit einem Blendmaster in einer Premium-Zigarrenfabrik in Costa Rica.

Cigarworld.de und rauchr.de nennen Tabacos de Costa Rica S.A. als Hersteller und Casagranda Cigars GmbH in Esslingen als Importeur; Zigarrenversand.ch spricht von der Fabrik Vegas de Santiago in Costa Rica. Casdagli schreibt, dass seine Zusammenarbeit mit Tabacos de Costa Rica SA, damals unter dem Namen Vegas Santiago bekannt, 2012 begonnen hat; Cigar Coop verortet die Fabrik von Tabacos de Costa Rica in Santiago de Puriscal.

Die Marke zählt vier Vitolas, von Hand in longfiller gerollt, mit Deckblatt H-2000 aus Ecuador. Im Oktober 2026 haben Zigarrenversand.ch und Humidor.ch sie im Katalog, während Cigarworld.de und rauchr.de die Unicos, seit dem 27. Juni 2018 im Katalog, als Auslaufartikel führen, mit dreizehn Stück auf Lager; Zigarrenwelt.de weist ebenso auf die Niños hin, seit dem 20. Dezember 2019 im Katalog.',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"Ecuador H-2000","vitolas":[],"story":"Deckblatt H-2000 aus Ecuador, colorado laut Cigarworld.de und rauchr.de, colorado maduro laut Zigarrenversand.ch, Umblatt aus Ecuador, Einlage aus der Dominikanischen Republik, aus Nicaragua und aus Peru, von Hand in longfiller gerollt, in vier Vitolas, El Niño (83 mm × 58), El Unico (140 mm × 58), El Diablo (152 mm) und El Volcano (belicoso von 158 mm); Stärke Stufe 4 von 8 auf der Skala von Cigarworld.de und Stufe 3 von 5 auf der von Zigarrenversand.ch."}]',
        'Skull 77 是 Laurent Taha 的品牌，Zigarrenversand.ch 将他介绍为品牌背后的人，而 rauchr.de 将其姓名写作 Tahla。Zigarrenversand.ch 称该品牌创立于2014年七月7日，77 即取自这一日期。据 rauchr.de，Tahla 与雪茄和品味打交道已超过二十年，2014年在一次品鉴会上结识了 Marc Niehaus，称其为 Vegas de Santiago Cigars 的所有者；两人成为朋友，并与一位 blendmaster 在哥斯达黎加一家高端雪茄工厂共同研发出混合配方。

Cigarworld.de 和 rauchr.de 给出的制造商是 Tabacos de Costa Rica S.A.，进口商是位于 Esslingen 的 Casagranda Cigars GmbH；Zigarrenversand.ch 则提到位于哥斯达黎加的 Vegas de Santiago 工厂。Casdagli 写道，其与 Tabacos de Costa Rica SA（当时被称为 Vegas Santiago）的合作始于2012年；Cigar Coop 将 Tabacos de Costa Rica 的工厂置于 Santiago de Puriscal。

该品牌有四种茄型，以 longfiller 手工卷制，茄衣为厄瓜多尔的 H-2000。2026年十月，Zigarrenversand.ch 和 Humidor.ch 将它们列入目录，而 Cigarworld.de 和 rauchr.de 保留 Unicos，自2018年六月27日起列入目录，列为清仓款，库存十三支；Zigarrenwelt.de 同样标示 Niños，自2019年十二月20日起列入目录。',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"厄瓜多尔 H-2000","vitolas":[],"story":"茄衣 H-2000 来自厄瓜多尔，据 Cigarworld.de 和 rauchr.de 为 colorado，据 Zigarrenversand.ch 为 colorado maduro，茄套来自厄瓜多尔，茄芯来自多米尼加共和国、尼加拉瓜和秘鲁，以 longfiller 手工卷制，共四种茄型：El Niño（83 mm × 58）、El Unico（140 mm × 58）、El Diablo（152 mm）和 El Volcano（158 mm 的 belicoso）；力度在 Cigarworld.de 的量表上为8级中的4级，在 Zigarrenversand.ch 的量表上为5级中的3级。"}]',
        'Skull 77 هي علامة Laurent Taha، الذي يقدّمه Zigarrenversand.ch بوصفه الرجل الذي يقف وراءها، ويكتب rauchr.de اسمه Tahla. ويقول Zigarrenversand.ch إنها تأسست في 7 يوليو 2014، وهو التاريخ الذي جاء منه الرقم 77. وبحسب rauchr.de، فإن Tahla، الذي يعمل في مجال السيجار والذوق منذ أكثر من عشرين عامًا، يتعرّف في عام 2014، خلال جلسة تذوق، إلى Marc Niehaus، الذي يقدّمه بوصفه مالك Vegas de Santiago Cigars؛ ويصبح الاثنان صديقين ويطوّران الخلطة مع blendmaster في مصنع سيجار فاخر في كوستاريكا.

يذكر Cigarworld.de و rauchr.de أن الجهة المصنِّعة هي Tabacos de Costa Rica S.A.، وأن المستورد هو Casagranda Cigars GmbH في Esslingen؛ ويتحدث Zigarrenversand.ch عن مصنع Vegas de Santiago في كوستاريكا. وتكتب Casdagli أن تعاونها مع Tabacos de Costa Rica SA، التي كانت تُعرف حينها باسم Vegas Santiago، بدأ في عام 2012؛ ويضع Cigar Coop مصنع Tabacos de Costa Rica في Santiago de Puriscal.

تضم العلامة أربعة مقاسات، ملفوفة يدويًا باستخدام longfiller، بغلاف خارجي H-2000 من الإكوادور. وفي أكتوبر 2026، يُدرج Zigarrenversand.ch و Humidor.ch هذه المقاسات في كتالوجهما، بينما يُبقي Cigarworld.de و rauchr.de على Unicos، المدرجة في الكتالوج منذ 27 يونيو 2018، بوصفها أصنافًا من نهاية السلسلة، مع ثلاث عشرة قطعة في المخزون؛ ويشير Zigarrenwelt.de كذلك إلى Niños، المدرجة في الكتالوج منذ 20 ديسمبر 2019.',
        '[{"name":"Colorado","color":"#8B5A2B","force":"Medium","wrapper":"الإكوادور H-2000","vitolas":[],"story":"الغلاف الخارجي H-2000 من الإكوادور، وهو colorado بحسب Cigarworld.de و rauchr.de، و colorado maduro بحسب Zigarrenversand.ch، والغلاف الداخلي من الإكوادور، والحشوة من جمهورية الدومينيكان ونيكاراغوا وبيرو، ملفوفة يدويًا باستخدام longfiller، في أربعة مقاسات: El Niño (83 mm × 58) و El Unico (140 mm × 58) و El Diablo (152 mm) و El Volcano (belicoso بمقاس 158 mm)؛ قوتها من المستوى 4 من 8 على مقياس Cigarworld.de، ومن المستوى 3 من 5 على مقياس Zigarrenversand.ch."}]')
ON DUPLICATE KEY UPDATE `country_id` = VALUES(`country_id`), `founded` = VALUES(`founded`), `factory` = VALUES(`factory`), `source` = VALUES(`source`), `mentions` = VALUES(`mentions`), `history` = VALUES(`history`), `gamme` = VALUES(`gamme`), `history_en` = VALUES(`history_en`), `gamme_en` = VALUES(`gamme_en`), `history_es` = VALUES(`history_es`), `gamme_es` = VALUES(`gamme_es`), `history_de` = VALUES(`history_de`), `gamme_de` = VALUES(`gamme_de`), `history_zh` = VALUES(`history_zh`), `gamme_zh` = VALUES(`gamme_zh`), `history_ar` = VALUES(`history_ar`), `gamme_ar` = VALUES(`gamme_ar`);

-- ── COSTARICA : `brands` relu dans la base et réécrit en littéral complet (12 entrées) ──
UPDATE `producer_countries` SET `brands` = '[{"desc":"Du dessinateur du Behike à sa propre maison","name":"Atabey","iconic":true},{"desc":"Le versant classique de Selected Tobacco","name":"Byron","iconic":false},{"desc":"Des tabacs mûris cinq ans avant roulage","name":"Bandolero","iconic":false},{"desc":"Maison britannique sans champs, roulée au Costa Rica","name":"Casdagli","iconic":false},{"name":"Selected Tobacco","desc":"Nelson Alfonso — la maison derrière Atabey, Byron et Bandolero","iconic":false},{"name":"Vegas de Santiago","desc":"La seule du pays qui cultive ce qu''elle roule","iconic":true},{"name":"Bombay Tobak","desc":"2014 — MBombay, troisième marque sortie de Puriscal","iconic":false},{"name":"Brun del Ré","desc":"Carlo Corazza, 2006 — usine propre à Escazú ; 1787 Libertad en tabac costaricien","iconic":true},{"name":"El Septimo","desc":"Genève 2005, Younan depuis 2019 — le luxe roulé au Costa Rica","iconic":false},{"name":"IGM Cigars","desc":"San José, 1997 selon la maison — la fabrique boutique qui roule Casdagli","iconic":false},{"name":"Malekö","desc":"Custom Blend lancée en 2015 ; roulée chez Tabacos de Costa Rica, à Santiago de Puriscal","iconic":false},{"name":"Skull 77","desc":"2014 — Laurent Taha ; roulée chez Tabacos de Costa Rica, à Santiago de Puriscal","iconic":false}]' WHERE `id` = 'costarica';

INSERT INTO `translation_status` (`entite`, `entite_id`, `champ`, `lang`, `source_hash`, `statut`, `maj`)
SELECT 'brands', b.`name`, c.champ, l.lang,
       SHA1(CASE c.champ WHEN 'history' THEN b.`history` ELSE b.`gamme` END), 'machine', NOW()
  FROM `brands` b
  JOIN (SELECT 'history' champ UNION ALL SELECT 'gamme') c
  JOIN (SELECT 'en' lang UNION ALL SELECT 'es' UNION ALL SELECT 'de' UNION ALL SELECT 'zh' UNION ALL SELECT 'ar') l
 WHERE b.`name` IN ('Malekö','Skull 77')
    ON DUPLICATE KEY UPDATE `source_hash` = VALUES(`source_hash`), `statut` = 'machine', `maj` = NOW();

DELETE FROM `moderation_log` WHERE `acteur_nom` = 'migration 249';
INSERT INTO `moderation_log`
  (`acteur_id`, `acteur_nom`, `portee`, `action`, `cible_type`, `cible_id`, `detail`)
VALUES
  (NULL,'migration 249','systeme','recensement_8_fiches','marque',0,
   'costarica : Malekö, Skull 77');

SELECT
  (SELECT COUNT(*) FROM `brands` WHERE `name` IN ('Malekö','Skull 77')) = 2 AS fiches,
  (SELECT JSON_CONTAINS(JSON_EXTRACT(`brands`, '$[*].name'), '"Malekö"') AND JSON_CONTAINS(JSON_EXTRACT(`brands`, '$[*].name'), '"Skull 77"') FROM `producer_countries` WHERE `id` = 'costarica') AS costarica_annonce,
  (SELECT COUNT(*) FROM `translation_status` WHERE `entite` = 'brands' AND `entite_id` IN ('Malekö','Skull 77')) = 20 AS sceaux,
  (SELECT SUM(CHAR_LENGTH(`detail`) >= 255) = 0 FROM `moderation_log` WHERE `acteur_nom` = 'migration 249') AS journal_non_tronque;
SELECT COUNT(*) AS marques, SUM(TRIM(COALESCE(`source`,'')) = '') AS sans_source FROM `brands`;
